// SPDX-License-Identifier: AGPL-3.0
//
// federated-meetup client RPC surface — the open client protobuf standard.
//
// ConnectRPC (https://connectrpc.com) over HTTP/2. Implementations:
//   - Client: any ConnectRPC client. We ship a Go reference impl (OSS).
//   - Server: any host that speaks the protocol. We ship a Go reference impl
//     (OSS for the wire layer; closed-source for the product features).
//
// Server-to-server federation traffic uses a SEPARATE WireGuard-only transport.
// It is intentionally NOT exposed here. See docs/02-PROTOCOL.md section 5.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: federated_meetup/v1/rpc.proto

package federatedmeetupv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either a public key (preferred) or a canonical name. If name, the host
	// resolves it via the public directory it has been configured with.
	//
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetGroupRequest_GroupKey
	//	*GetGroupRequest_CanonicalName
	Identifier    isGetGroupRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetGroupRequest) GetIdentifier() isGetGroupRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetGroupRequest) GetGroupKey() *PublicKey {
	if x != nil {
		if x, ok := x.Identifier.(*GetGroupRequest_GroupKey); ok {
			return x.GroupKey
		}
	}
	return nil
}

func (x *GetGroupRequest) GetCanonicalName() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetGroupRequest_CanonicalName); ok {
			return x.CanonicalName
		}
	}
	return ""
}

type isGetGroupRequest_Identifier interface {
	isGetGroupRequest_Identifier()
}

type GetGroupRequest_GroupKey struct {
	GroupKey *PublicKey `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3,oneof"`
}

type GetGroupRequest_CanonicalName struct {
	CanonicalName string `protobuf:"bytes,2,opt,name=canonical_name,json=canonicalName,proto3,oneof"`
}

func (*GetGroupRequest_GroupKey) isGetGroupRequest_Identifier() {}

func (*GetGroupRequest_CanonicalName) isGetGroupRequest_Identifier() {}

type GetGroupResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Snapshot *StateSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// Current steward set + threshold, for client-side verification.
	Stewards      []*PublicKey `protobuf:"bytes,2,rep,name=stewards,proto3" json:"stewards,omitempty"`
	Threshold     uint32       `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupResponse) Reset() {
	*x = GetGroupResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupResponse) ProtoMessage() {}

func (x *GetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupResponse.ProtoReflect.Descriptor instead.
func (*GetGroupResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupResponse) GetSnapshot() *StateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *GetGroupResponse) GetStewards() []*PublicKey {
	if x != nil {
		return x.Stewards
	}
	return nil
}

func (x *GetGroupResponse) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupKey      *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetEventRequest) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *GetEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Event *CreateEventPayload    `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Current RSVP list (public keys only).
	Rsvps         []*PublicKey `protobuf:"bytes,2,rep,name=rsvps,proto3" json:"rsvps,omitempty"`
	Cancelled     bool         `protobuf:"varint,3,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventResponse) GetEvent() *CreateEventPayload {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GetEventResponse) GetRsvps() []*PublicKey {
	if x != nil {
		return x.Rsvps
	}
	return nil
}

func (x *GetEventResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type ListEventsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GroupKey *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// Pagination cursor — opaque to the client.
	Cursor        string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsRequest) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *ListEventsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListEventsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*CreateEventPayload  `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListEventsResponse) GetEvents() []*CreateEventPayload {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ListGroupsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional substring filter on canonical name.
	NameContains  string `protobuf:"bytes,1,opt,name=name_contains,json=nameContains,proto3" json:"name_contains,omitempty"`
	Cursor        string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListGroupsRequest) GetNameContains() string {
	if x != nil {
		return x.NameContains
	}
	return ""
}

func (x *ListGroupsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListGroupsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Groups        []*ListGroupsResponse_GroupSummary `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	NextCursor    string                             `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ListGroupsResponse) GetGroups() []*ListGroupsResponse_GroupSummary {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListGroupsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type SubmitTransitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupKey      *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	Transition    *Transition            `protobuf:"bytes,2,opt,name=transition,proto3" json:"transition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTransitionRequest) Reset() {
	*x = SubmitTransitionRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransitionRequest) ProtoMessage() {}

func (x *SubmitTransitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransitionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransitionRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitTransitionRequest) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *SubmitTransitionRequest) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

type SubmitTransitionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewSnapshot     *StateSnapshot         `protobuf:"bytes,1,opt,name=new_snapshot,json=newSnapshot,proto3" json:"new_snapshot,omitempty"`
	TransitionIndex uint64                 `protobuf:"varint,2,opt,name=transition_index,json=transitionIndex,proto3" json:"transition_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitTransitionResponse) Reset() {
	*x = SubmitTransitionResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransitionResponse) ProtoMessage() {}

func (x *SubmitTransitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransitionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransitionResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitTransitionResponse) GetNewSnapshot() *StateSnapshot {
	if x != nil {
		return x.NewSnapshot
	}
	return nil
}

func (x *SubmitTransitionResponse) GetTransitionIndex() uint64 {
	if x != nil {
		return x.TransitionIndex
	}
	return 0
}

type SubmitUserActionRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	GroupKey     *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	Type         TransitionType         `protobuf:"varint,2,opt,name=type,proto3,enum=federated_meetup.v1.TransitionType" json:"type,omitempty"`
	UserEnvelope *SignedEnvelope        `protobuf:"bytes,3,opt,name=user_envelope,json=userEnvelope,proto3" json:"user_envelope,omitempty"`
	// The transition payload, embedded for convenience. Hosts re-derive this
	// from the signed bytes for verification.
	TransitionPayload []byte `protobuf:"bytes,4,opt,name=transition_payload,json=transitionPayload,proto3" json:"transition_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubmitUserActionRequest) Reset() {
	*x = SubmitUserActionRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUserActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUserActionRequest) ProtoMessage() {}

func (x *SubmitUserActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUserActionRequest.ProtoReflect.Descriptor instead.
func (*SubmitUserActionRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitUserActionRequest) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *SubmitUserActionRequest) GetType() TransitionType {
	if x != nil {
		return x.Type
	}
	return TransitionType_TRANSITION_TYPE_UNSPECIFIED
}

func (x *SubmitUserActionRequest) GetUserEnvelope() *SignedEnvelope {
	if x != nil {
		return x.UserEnvelope
	}
	return nil
}

func (x *SubmitUserActionRequest) GetTransitionPayload() []byte {
	if x != nil {
		return x.TransitionPayload
	}
	return nil
}

type SubmitUserActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewSnapshot   *StateSnapshot         `protobuf:"bytes,1,opt,name=new_snapshot,json=newSnapshot,proto3" json:"new_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitUserActionResponse) Reset() {
	*x = SubmitUserActionResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUserActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUserActionResponse) ProtoMessage() {}

func (x *SubmitUserActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUserActionResponse.ProtoReflect.Descriptor instead.
func (*SubmitUserActionResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitUserActionResponse) GetNewSnapshot() *StateSnapshot {
	if x != nil {
		return x.NewSnapshot
	}
	return nil
}

type ResolveNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanonicalName string                 `protobuf:"bytes,1,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveNameRequest) Reset() {
	*x = ResolveNameRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveNameRequest) ProtoMessage() {}

func (x *ResolveNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveNameRequest.ProtoReflect.Descriptor instead.
func (*ResolveNameRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveNameRequest) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

type ResolveNameResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GroupKey *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// The hosts currently serving this group, ordered by canonicalness.
	Hosts         []string `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveNameResponse) Reset() {
	*x = ResolveNameResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveNameResponse) ProtoMessage() {}

func (x *ResolveNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveNameResponse.ProtoReflect.Descriptor instead.
func (*ResolveNameResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveNameResponse) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *ResolveNameResponse) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type GetLogRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GroupKey *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// Return transitions with index > since_cursor. 0 = from the beginning.
	SinceCursor uint64 `protobuf:"varint,2,opt,name=since_cursor,json=sinceCursor,proto3" json:"since_cursor,omitempty"`
	// Max transitions to return (server may cap). Default 100.
	Limit         uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetLogRequest) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *GetLogRequest) GetSinceCursor() uint64 {
	if x != nil {
		return x.SinceCursor
	}
	return 0
}

func (x *GetLogRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLogResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Transitions []*Transition          `protobuf:"bytes,1,rep,name=transitions,proto3" json:"transitions,omitempty"`
	// Index of the next transition after this batch. Use as since_cursor
	// for the next page. 0 if no more.
	NextCursor uint64 `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Total transitions in the group's log (at response time).
	Total         uint64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogResponse) Reset() {
	*x = GetLogResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogResponse) ProtoMessage() {}

func (x *GetLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogResponse.ProtoReflect.Descriptor instead.
func (*GetLogResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *GetLogResponse) GetTransitions() []*Transition {
	if x != nil {
		return x.Transitions
	}
	return nil
}

func (x *GetLogResponse) GetNextCursor() uint64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *GetLogResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetSnapshotRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GroupKey *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// If set, return the snapshot at this root. If nil, return current head.
	Root          *StateRoot `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *GetSnapshotRequest) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *GetSnapshotRequest) GetRoot() *StateRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

type GetSnapshotResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Snapshot *StateSnapshot         `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// The transition index at which this snapshot was taken.
	TransitionIndex uint64 `protobuf:"varint,2,opt,name=transition_index,json=transitionIndex,proto3" json:"transition_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *GetSnapshotResponse) GetSnapshot() *StateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *GetSnapshotResponse) GetTransitionIndex() uint64 {
	if x != nil {
		return x.TransitionIndex
	}
	return 0
}

type SubscribeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	GroupKey *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	// If non-zero, only transitions with index > since_index are streamed.
	// Clients pass the last index they saw (from SubmitTransitionResponse
	// or a prior Subscribe) to resume after disconnect.
	SinceIndex    uint64 `protobuf:"varint,2,opt,name=since_index,json=sinceIndex,proto3" json:"since_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *SubscribeRequest) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *SubscribeRequest) GetSinceIndex() uint64 {
	if x != nil {
		return x.SinceIndex
	}
	return 0
}

type TransitionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transition that was applied.
	Transition *Transition `protobuf:"bytes,1,opt,name=transition,proto3" json:"transition,omitempty"`
	// The new state root after applying the transition.
	NewStateRoot *StateRoot `protobuf:"bytes,2,opt,name=new_state_root,json=newStateRoot,proto3" json:"new_state_root,omitempty"`
	// The index of this transition in the group's log.
	TransitionIndex uint64 `protobuf:"varint,3,opt,name=transition_index,json=transitionIndex,proto3" json:"transition_index,omitempty"`
	// The group's GroupID (so clients multiplexing multiple groups
	// can route without re-deriving from the transition).
	GroupKey      *PublicKey `protobuf:"bytes,4,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionEvent) Reset() {
	*x = TransitionEvent{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionEvent) ProtoMessage() {}

func (x *TransitionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionEvent.ProtoReflect.Descriptor instead.
func (*TransitionEvent) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *TransitionEvent) GetTransition() *Transition {
	if x != nil {
		return x.Transition
	}
	return nil
}

func (x *TransitionEvent) GetNewStateRoot() *StateRoot {
	if x != nil {
		return x.NewStateRoot
	}
	return nil
}

func (x *TransitionEvent) GetTransitionIndex() uint64 {
	if x != nil {
		return x.TransitionIndex
	}
	return 0
}

func (x *TransitionEvent) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

type ListGroupsResponse_GroupSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupKey      *PublicKey             `protobuf:"bytes,1,opt,name=group_key,json=groupKey,proto3" json:"group_key,omitempty"`
	CanonicalName string                 `protobuf:"bytes,2,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse_GroupSummary) Reset() {
	*x = ListGroupsResponse_GroupSummary{}
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse_GroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse_GroupSummary) ProtoMessage() {}

func (x *ListGroupsResponse_GroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_v1_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse_GroupSummary.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse_GroupSummary) Descriptor() ([]byte, []int) {
	return file_federated_meetup_v1_rpc_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListGroupsResponse_GroupSummary) GetGroupKey() *PublicKey {
	if x != nil {
		return x.GroupKey
	}
	return nil
}

func (x *ListGroupsResponse_GroupSummary) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *ListGroupsResponse_GroupSummary) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_federated_meetup_v1_rpc_proto protoreflect.FileDescriptor

const file_federated_meetup_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1dfederated_meetup/v1/rpc.proto\x12\x13federated_meetup.v1\x1a\x1ffederated_meetup/v1/state.proto\"\x87\x01\n" +
	"\x0fGetGroupRequest\x12=\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyH\x00R\bgroupKey\x12'\n" +
	"\x0ecanonical_name\x18\x02 \x01(\tH\x00R\rcanonicalNameB\f\n" +
	"\n" +
	"identifier\"\xac\x01\n" +
	"\x10GetGroupResponse\x12>\n" +
	"\bsnapshot\x18\x01 \x01(\v2\".federated_meetup.v1.StateSnapshotR\bsnapshot\x12:\n" +
	"\bstewards\x18\x02 \x03(\v2\x1e.federated_meetup.v1.PublicKeyR\bstewards\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\rR\tthreshold\"i\n" +
	"\x0fGetEventRequest\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\"\xa5\x01\n" +
	"\x10GetEventResponse\x12=\n" +
	"\x05event\x18\x01 \x01(\v2'.federated_meetup.v1.CreateEventPayloadR\x05event\x124\n" +
	"\x05rsvps\x18\x02 \x03(\v2\x1e.federated_meetup.v1.PublicKeyR\x05rsvps\x12\x1c\n" +
	"\tcancelled\x18\x03 \x01(\bR\tcancelled\"\x85\x01\n" +
	"\x11ListEventsRequest\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"v\n" +
	"\x12ListEventsResponse\x12?\n" +
	"\x06events\x18\x01 \x03(\v2'.federated_meetup.v1.CreateEventPayloadR\x06events\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"m\n" +
	"\x11ListGroupsRequest\x12#\n" +
	"\rname_contains\x18\x01 \x01(\tR\fnameContains\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x9b\x02\n" +
	"\x12ListGroupsResponse\x12L\n" +
	"\x06groups\x18\x01 \x03(\v24.federated_meetup.v1.ListGroupsResponse.GroupSummaryR\x06groups\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x1a\x95\x01\n" +
	"\fGroupSummary\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x12%\n" +
	"\x0ecanonical_name\x18\x02 \x01(\tR\rcanonicalName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"\x97\x01\n" +
	"\x17SubmitTransitionRequest\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x12?\n" +
	"\n" +
	"transition\x18\x02 \x01(\v2\x1f.federated_meetup.v1.TransitionR\n" +
	"transition\"\x8c\x01\n" +
	"\x18SubmitTransitionResponse\x12E\n" +
	"\fnew_snapshot\x18\x01 \x01(\v2\".federated_meetup.v1.StateSnapshotR\vnewSnapshot\x12)\n" +
	"\x10transition_index\x18\x02 \x01(\x04R\x0ftransitionIndex\"\x88\x02\n" +
	"\x17SubmitUserActionRequest\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.federated_meetup.v1.TransitionTypeR\x04type\x12H\n" +
	"\ruser_envelope\x18\x03 \x01(\v2#.federated_meetup.v1.SignedEnvelopeR\fuserEnvelope\x12-\n" +
	"\x12transition_payload\x18\x04 \x01(\fR\x11transitionPayload\"a\n" +
	"\x18SubmitUserActionResponse\x12E\n" +
	"\fnew_snapshot\x18\x01 \x01(\v2\".federated_meetup.v1.StateSnapshotR\vnewSnapshot\";\n" +
	"\x12ResolveNameRequest\x12%\n" +
	"\x0ecanonical_name\x18\x01 \x01(\tR\rcanonicalName\"h\n" +
	"\x13ResolveNameResponse\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x12\x14\n" +
	"\x05hosts\x18\x02 \x03(\tR\x05hosts\"\x85\x01\n" +
	"\rGetLogRequest\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x12!\n" +
	"\fsince_cursor\x18\x02 \x01(\x04R\vsinceCursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\x8a\x01\n" +
	"\x0eGetLogResponse\x12A\n" +
	"\vtransitions\x18\x01 \x03(\v2\x1f.federated_meetup.v1.TransitionR\vtransitions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x04R\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"\x85\x01\n" +
	"\x12GetSnapshotRequest\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x122\n" +
	"\x04root\x18\x02 \x01(\v2\x1e.federated_meetup.v1.StateRootR\x04root\"\x80\x01\n" +
	"\x13GetSnapshotResponse\x12>\n" +
	"\bsnapshot\x18\x01 \x01(\v2\".federated_meetup.v1.StateSnapshotR\bsnapshot\x12)\n" +
	"\x10transition_index\x18\x02 \x01(\x04R\x0ftransitionIndex\"p\n" +
	"\x10SubscribeRequest\x12;\n" +
	"\tgroup_key\x18\x01 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey\x12\x1f\n" +
	"\vsince_index\x18\x02 \x01(\x04R\n" +
	"sinceIndex\"\x80\x02\n" +
	"\x0fTransitionEvent\x12?\n" +
	"\n" +
	"transition\x18\x01 \x01(\v2\x1f.federated_meetup.v1.TransitionR\n" +
	"transition\x12D\n" +
	"\x0enew_state_root\x18\x02 \x01(\v2\x1e.federated_meetup.v1.StateRootR\fnewStateRoot\x12)\n" +
	"\x10transition_index\x18\x03 \x01(\x04R\x0ftransitionIndex\x12;\n" +
	"\tgroup_key\x18\x04 \x01(\v2\x1e.federated_meetup.v1.PublicKeyR\bgroupKey2\xa5\b\n" +
	"\vHostService\x12W\n" +
	"\bGetGroup\x12$.federated_meetup.v1.GetGroupRequest\x1a%.federated_meetup.v1.GetGroupResponse\x12W\n" +
	"\bGetEvent\x12$.federated_meetup.v1.GetEventRequest\x1a%.federated_meetup.v1.GetEventResponse\x12]\n" +
	"\n" +
	"ListEvents\x12&.federated_meetup.v1.ListEventsRequest\x1a'.federated_meetup.v1.ListEventsResponse\x12]\n" +
	"\n" +
	"ListGroups\x12&.federated_meetup.v1.ListGroupsRequest\x1a'.federated_meetup.v1.ListGroupsResponse\x12Q\n" +
	"\x06GetLog\x12\".federated_meetup.v1.GetLogRequest\x1a#.federated_meetup.v1.GetLogResponse\x12`\n" +
	"\vGetSnapshot\x12'.federated_meetup.v1.GetSnapshotRequest\x1a(.federated_meetup.v1.GetSnapshotResponse\x12o\n" +
	"\x10SubmitTransition\x12,.federated_meetup.v1.SubmitTransitionRequest\x1a-.federated_meetup.v1.SubmitTransitionResponse\x12o\n" +
	"\x10SubmitUserAction\x12,.federated_meetup.v1.SubmitUserActionRequest\x1a-.federated_meetup.v1.SubmitUserActionResponse\x12`\n" +
	"\vResolveName\x12'.federated_meetup.v1.ResolveNameRequest\x1a(.federated_meetup.v1.ResolveNameResponse\x12Z\n" +
	"\tSubscribe\x12%.federated_meetup.v1.SubscribeRequest\x1a$.federated_meetup.v1.TransitionEvent0\x01\x12Q\n" +
	"\x0eSubmitEvidence\x12%.federated_meetup.v1.EvidenceEnvelope\x1a\x18.federated_meetup.v1.AckBQZOgithub.com/sscoble/federated-meetup/proto/federated_meetup/v1;federatedmeetupv1b\x06proto3"

var (
	file_federated_meetup_v1_rpc_proto_rawDescOnce sync.Once
	file_federated_meetup_v1_rpc_proto_rawDescData []byte
)

func file_federated_meetup_v1_rpc_proto_rawDescGZIP() []byte {
	file_federated_meetup_v1_rpc_proto_rawDescOnce.Do(func() {
		file_federated_meetup_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federated_meetup_v1_rpc_proto_rawDesc), len(file_federated_meetup_v1_rpc_proto_rawDesc)))
	})
	return file_federated_meetup_v1_rpc_proto_rawDescData
}

var file_federated_meetup_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_federated_meetup_v1_rpc_proto_goTypes = []any{
	(*GetGroupRequest)(nil),                 // 0: federated_meetup.v1.GetGroupRequest
	(*GetGroupResponse)(nil),                // 1: federated_meetup.v1.GetGroupResponse
	(*GetEventRequest)(nil),                 // 2: federated_meetup.v1.GetEventRequest
	(*GetEventResponse)(nil),                // 3: federated_meetup.v1.GetEventResponse
	(*ListEventsRequest)(nil),               // 4: federated_meetup.v1.ListEventsRequest
	(*ListEventsResponse)(nil),              // 5: federated_meetup.v1.ListEventsResponse
	(*ListGroupsRequest)(nil),               // 6: federated_meetup.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),              // 7: federated_meetup.v1.ListGroupsResponse
	(*SubmitTransitionRequest)(nil),         // 8: federated_meetup.v1.SubmitTransitionRequest
	(*SubmitTransitionResponse)(nil),        // 9: federated_meetup.v1.SubmitTransitionResponse
	(*SubmitUserActionRequest)(nil),         // 10: federated_meetup.v1.SubmitUserActionRequest
	(*SubmitUserActionResponse)(nil),        // 11: federated_meetup.v1.SubmitUserActionResponse
	(*ResolveNameRequest)(nil),              // 12: federated_meetup.v1.ResolveNameRequest
	(*ResolveNameResponse)(nil),             // 13: federated_meetup.v1.ResolveNameResponse
	(*GetLogRequest)(nil),                   // 14: federated_meetup.v1.GetLogRequest
	(*GetLogResponse)(nil),                  // 15: federated_meetup.v1.GetLogResponse
	(*GetSnapshotRequest)(nil),              // 16: federated_meetup.v1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),             // 17: federated_meetup.v1.GetSnapshotResponse
	(*SubscribeRequest)(nil),                // 18: federated_meetup.v1.SubscribeRequest
	(*TransitionEvent)(nil),                 // 19: federated_meetup.v1.TransitionEvent
	(*ListGroupsResponse_GroupSummary)(nil), // 20: federated_meetup.v1.ListGroupsResponse.GroupSummary
	(*PublicKey)(nil),                       // 21: federated_meetup.v1.PublicKey
	(*StateSnapshot)(nil),                   // 22: federated_meetup.v1.StateSnapshot
	(*CreateEventPayload)(nil),              // 23: federated_meetup.v1.CreateEventPayload
	(*Transition)(nil),                      // 24: federated_meetup.v1.Transition
	(TransitionType)(0),                     // 25: federated_meetup.v1.TransitionType
	(*SignedEnvelope)(nil),                  // 26: federated_meetup.v1.SignedEnvelope
	(*StateRoot)(nil),                       // 27: federated_meetup.v1.StateRoot
	(*EvidenceEnvelope)(nil),                // 28: federated_meetup.v1.EvidenceEnvelope
	(*Ack)(nil),                             // 29: federated_meetup.v1.Ack
}
var file_federated_meetup_v1_rpc_proto_depIdxs = []int32{
	21, // 0: federated_meetup.v1.GetGroupRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	22, // 1: federated_meetup.v1.GetGroupResponse.snapshot:type_name -> federated_meetup.v1.StateSnapshot
	21, // 2: federated_meetup.v1.GetGroupResponse.stewards:type_name -> federated_meetup.v1.PublicKey
	21, // 3: federated_meetup.v1.GetEventRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	23, // 4: federated_meetup.v1.GetEventResponse.event:type_name -> federated_meetup.v1.CreateEventPayload
	21, // 5: federated_meetup.v1.GetEventResponse.rsvps:type_name -> federated_meetup.v1.PublicKey
	21, // 6: federated_meetup.v1.ListEventsRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	23, // 7: federated_meetup.v1.ListEventsResponse.events:type_name -> federated_meetup.v1.CreateEventPayload
	20, // 8: federated_meetup.v1.ListGroupsResponse.groups:type_name -> federated_meetup.v1.ListGroupsResponse.GroupSummary
	21, // 9: federated_meetup.v1.SubmitTransitionRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	24, // 10: federated_meetup.v1.SubmitTransitionRequest.transition:type_name -> federated_meetup.v1.Transition
	22, // 11: federated_meetup.v1.SubmitTransitionResponse.new_snapshot:type_name -> federated_meetup.v1.StateSnapshot
	21, // 12: federated_meetup.v1.SubmitUserActionRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	25, // 13: federated_meetup.v1.SubmitUserActionRequest.type:type_name -> federated_meetup.v1.TransitionType
	26, // 14: federated_meetup.v1.SubmitUserActionRequest.user_envelope:type_name -> federated_meetup.v1.SignedEnvelope
	22, // 15: federated_meetup.v1.SubmitUserActionResponse.new_snapshot:type_name -> federated_meetup.v1.StateSnapshot
	21, // 16: federated_meetup.v1.ResolveNameResponse.group_key:type_name -> federated_meetup.v1.PublicKey
	21, // 17: federated_meetup.v1.GetLogRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	24, // 18: federated_meetup.v1.GetLogResponse.transitions:type_name -> federated_meetup.v1.Transition
	21, // 19: federated_meetup.v1.GetSnapshotRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	27, // 20: federated_meetup.v1.GetSnapshotRequest.root:type_name -> federated_meetup.v1.StateRoot
	22, // 21: federated_meetup.v1.GetSnapshotResponse.snapshot:type_name -> federated_meetup.v1.StateSnapshot
	21, // 22: federated_meetup.v1.SubscribeRequest.group_key:type_name -> federated_meetup.v1.PublicKey
	24, // 23: federated_meetup.v1.TransitionEvent.transition:type_name -> federated_meetup.v1.Transition
	27, // 24: federated_meetup.v1.TransitionEvent.new_state_root:type_name -> federated_meetup.v1.StateRoot
	21, // 25: federated_meetup.v1.TransitionEvent.group_key:type_name -> federated_meetup.v1.PublicKey
	21, // 26: federated_meetup.v1.ListGroupsResponse.GroupSummary.group_key:type_name -> federated_meetup.v1.PublicKey
	0,  // 27: federated_meetup.v1.HostService.GetGroup:input_type -> federated_meetup.v1.GetGroupRequest
	2,  // 28: federated_meetup.v1.HostService.GetEvent:input_type -> federated_meetup.v1.GetEventRequest
	4,  // 29: federated_meetup.v1.HostService.ListEvents:input_type -> federated_meetup.v1.ListEventsRequest
	6,  // 30: federated_meetup.v1.HostService.ListGroups:input_type -> federated_meetup.v1.ListGroupsRequest
	14, // 31: federated_meetup.v1.HostService.GetLog:input_type -> federated_meetup.v1.GetLogRequest
	16, // 32: federated_meetup.v1.HostService.GetSnapshot:input_type -> federated_meetup.v1.GetSnapshotRequest
	8,  // 33: federated_meetup.v1.HostService.SubmitTransition:input_type -> federated_meetup.v1.SubmitTransitionRequest
	10, // 34: federated_meetup.v1.HostService.SubmitUserAction:input_type -> federated_meetup.v1.SubmitUserActionRequest
	12, // 35: federated_meetup.v1.HostService.ResolveName:input_type -> federated_meetup.v1.ResolveNameRequest
	18, // 36: federated_meetup.v1.HostService.Subscribe:input_type -> federated_meetup.v1.SubscribeRequest
	28, // 37: federated_meetup.v1.HostService.SubmitEvidence:input_type -> federated_meetup.v1.EvidenceEnvelope
	1,  // 38: federated_meetup.v1.HostService.GetGroup:output_type -> federated_meetup.v1.GetGroupResponse
	3,  // 39: federated_meetup.v1.HostService.GetEvent:output_type -> federated_meetup.v1.GetEventResponse
	5,  // 40: federated_meetup.v1.HostService.ListEvents:output_type -> federated_meetup.v1.ListEventsResponse
	7,  // 41: federated_meetup.v1.HostService.ListGroups:output_type -> federated_meetup.v1.ListGroupsResponse
	15, // 42: federated_meetup.v1.HostService.GetLog:output_type -> federated_meetup.v1.GetLogResponse
	17, // 43: federated_meetup.v1.HostService.GetSnapshot:output_type -> federated_meetup.v1.GetSnapshotResponse
	9,  // 44: federated_meetup.v1.HostService.SubmitTransition:output_type -> federated_meetup.v1.SubmitTransitionResponse
	11, // 45: federated_meetup.v1.HostService.SubmitUserAction:output_type -> federated_meetup.v1.SubmitUserActionResponse
	13, // 46: federated_meetup.v1.HostService.ResolveName:output_type -> federated_meetup.v1.ResolveNameResponse
	19, // 47: federated_meetup.v1.HostService.Subscribe:output_type -> federated_meetup.v1.TransitionEvent
	29, // 48: federated_meetup.v1.HostService.SubmitEvidence:output_type -> federated_meetup.v1.Ack
	38, // [38:49] is the sub-list for method output_type
	27, // [27:38] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_federated_meetup_v1_rpc_proto_init() }
func file_federated_meetup_v1_rpc_proto_init() {
	if File_federated_meetup_v1_rpc_proto != nil {
		return
	}
	file_federated_meetup_v1_state_proto_init()
	file_federated_meetup_v1_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*GetGroupRequest_GroupKey)(nil),
		(*GetGroupRequest_CanonicalName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federated_meetup_v1_rpc_proto_rawDesc), len(file_federated_meetup_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federated_meetup_v1_rpc_proto_goTypes,
		DependencyIndexes: file_federated_meetup_v1_rpc_proto_depIdxs,
		MessageInfos:      file_federated_meetup_v1_rpc_proto_msgTypes,
	}.Build()
	File_federated_meetup_v1_rpc_proto = out.File
	file_federated_meetup_v1_rpc_proto_goTypes = nil
	file_federated_meetup_v1_rpc_proto_depIdxs = nil
}
