// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: federated_meetup/v1/rpc.proto

package federatedmeetupv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetGroupRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetGroupRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupRequestMultiError, or nil if none found.
func (m *GetGroupRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Identifier.(type) {
	case *GetGroupRequest_GroupKey:
		if v == nil {
			err := GetGroupRequestValidationError{
				field:  "Identifier",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetGroupKey()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetGroupRequestValidationError{
						field:  "GroupKey",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetGroupRequestValidationError{
						field:  "GroupKey",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetGroupRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *GetGroupRequest_CanonicalName:
		if v == nil {
			err := GetGroupRequestValidationError{
				field:  "Identifier",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for CanonicalName
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return GetGroupRequestMultiError(errors)
	}

	return nil
}

// GetGroupRequestMultiError is an error wrapping multiple validation errors
// returned by GetGroupRequest.ValidateAll() if the designated constraints
// aren't met.
type GetGroupRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupRequestMultiError) AllErrors() []error { return m }

// GetGroupRequestValidationError is the validation error returned by
// GetGroupRequest.Validate if the designated constraints aren't met.
type GetGroupRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupRequestValidationError) ErrorName() string { return "GetGroupRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetGroupRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupRequestValidationError{}

// Validate checks the field values on GetGroupResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetGroupResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupResponseMultiError, or nil if none found.
func (m *GetGroupResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSnapshot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetGroupResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetGroupResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetGroupResponseValidationError{
				field:  "Snapshot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetStewards() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetGroupResponseValidationError{
						field:  fmt.Sprintf("Stewards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetGroupResponseValidationError{
						field:  fmt.Sprintf("Stewards[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetGroupResponseValidationError{
					field:  fmt.Sprintf("Stewards[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Threshold

	if len(errors) > 0 {
		return GetGroupResponseMultiError(errors)
	}

	return nil
}

// GetGroupResponseMultiError is an error wrapping multiple validation errors
// returned by GetGroupResponse.ValidateAll() if the designated constraints
// aren't met.
type GetGroupResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupResponseMultiError) AllErrors() []error { return m }

// GetGroupResponseValidationError is the validation error returned by
// GetGroupResponse.Validate if the designated constraints aren't met.
type GetGroupResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupResponseValidationError) ErrorName() string { return "GetGroupResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetGroupResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupResponseValidationError{}

// Validate checks the field values on GetEventRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEventRequestMultiError, or nil if none found.
func (m *GetEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetEventRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetEventRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetEventRequestValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for EventId

	if len(errors) > 0 {
		return GetEventRequestMultiError(errors)
	}

	return nil
}

// GetEventRequestMultiError is an error wrapping multiple validation errors
// returned by GetEventRequest.ValidateAll() if the designated constraints
// aren't met.
type GetEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEventRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEventRequestMultiError) AllErrors() []error { return m }

// GetEventRequestValidationError is the validation error returned by
// GetEventRequest.Validate if the designated constraints aren't met.
type GetEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEventRequestValidationError) ErrorName() string { return "GetEventRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEventRequestValidationError{}

// Validate checks the field values on GetEventResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEventResponseMultiError, or nil if none found.
func (m *GetEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetEventResponseValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetEventResponseValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetEventResponseValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetRsvps() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetEventResponseValidationError{
						field:  fmt.Sprintf("Rsvps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetEventResponseValidationError{
						field:  fmt.Sprintf("Rsvps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetEventResponseValidationError{
					field:  fmt.Sprintf("Rsvps[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Cancelled

	if len(errors) > 0 {
		return GetEventResponseMultiError(errors)
	}

	return nil
}

// GetEventResponseMultiError is an error wrapping multiple validation errors
// returned by GetEventResponse.ValidateAll() if the designated constraints
// aren't met.
type GetEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEventResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEventResponseMultiError) AllErrors() []error { return m }

// GetEventResponseValidationError is the validation error returned by
// GetEventResponse.Validate if the designated constraints aren't met.
type GetEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEventResponseValidationError) ErrorName() string { return "GetEventResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEventResponseValidationError{}

// Validate checks the field values on ListEventsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListEventsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListEventsRequestMultiError, or nil if none found.
func (m *ListEventsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListEventsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListEventsRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListEventsRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListEventsRequestValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Cursor

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListEventsRequestMultiError(errors)
	}

	return nil
}

// ListEventsRequestMultiError is an error wrapping multiple validation errors
// returned by ListEventsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListEventsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListEventsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListEventsRequestMultiError) AllErrors() []error { return m }

// ListEventsRequestValidationError is the validation error returned by
// ListEventsRequest.Validate if the designated constraints aren't met.
type ListEventsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEventsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEventsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEventsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEventsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEventsRequestValidationError) ErrorName() string {
	return "ListEventsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListEventsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEventsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEventsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEventsRequestValidationError{}

// Validate checks the field values on ListEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListEventsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListEventsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListEventsResponseMultiError, or nil if none found.
func (m *ListEventsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListEventsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListEventsResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListEventsResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListEventsResponseValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextCursor

	if len(errors) > 0 {
		return ListEventsResponseMultiError(errors)
	}

	return nil
}

// ListEventsResponseMultiError is an error wrapping multiple validation errors
// returned by ListEventsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListEventsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListEventsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListEventsResponseMultiError) AllErrors() []error { return m }

// ListEventsResponseValidationError is the validation error returned by
// ListEventsResponse.Validate if the designated constraints aren't met.
type ListEventsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListEventsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListEventsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListEventsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListEventsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListEventsResponseValidationError) ErrorName() string {
	return "ListEventsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListEventsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListEventsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListEventsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListEventsResponseValidationError{}

// Validate checks the field values on ListGroupsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListGroupsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListGroupsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListGroupsRequestMultiError, or nil if none found.
func (m *ListGroupsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListGroupsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NameContains

	// no validation rules for Cursor

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListGroupsRequestMultiError(errors)
	}

	return nil
}

// ListGroupsRequestMultiError is an error wrapping multiple validation errors
// returned by ListGroupsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListGroupsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListGroupsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListGroupsRequestMultiError) AllErrors() []error { return m }

// ListGroupsRequestValidationError is the validation error returned by
// ListGroupsRequest.Validate if the designated constraints aren't met.
type ListGroupsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGroupsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGroupsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGroupsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGroupsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGroupsRequestValidationError) ErrorName() string {
	return "ListGroupsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListGroupsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGroupsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGroupsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGroupsRequestValidationError{}

// Validate checks the field values on ListGroupsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListGroupsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListGroupsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListGroupsResponseMultiError, or nil if none found.
func (m *ListGroupsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListGroupsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetGroups() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListGroupsResponseValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListGroupsResponseValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListGroupsResponseValidationError{
					field:  fmt.Sprintf("Groups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextCursor

	if len(errors) > 0 {
		return ListGroupsResponseMultiError(errors)
	}

	return nil
}

// ListGroupsResponseMultiError is an error wrapping multiple validation errors
// returned by ListGroupsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListGroupsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListGroupsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListGroupsResponseMultiError) AllErrors() []error { return m }

// ListGroupsResponseValidationError is the validation error returned by
// ListGroupsResponse.Validate if the designated constraints aren't met.
type ListGroupsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGroupsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGroupsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGroupsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGroupsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGroupsResponseValidationError) ErrorName() string {
	return "ListGroupsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListGroupsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGroupsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGroupsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGroupsResponseValidationError{}

// Validate checks the field values on SubmitTransitionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitTransitionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitTransitionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitTransitionRequestMultiError, or nil if none found.
func (m *SubmitTransitionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitTransitionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitTransitionRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitTransitionRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitTransitionRequestValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTransition()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitTransitionRequestValidationError{
					field:  "Transition",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitTransitionRequestValidationError{
					field:  "Transition",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransition()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitTransitionRequestValidationError{
				field:  "Transition",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SubmitTransitionRequestMultiError(errors)
	}

	return nil
}

// SubmitTransitionRequestMultiError is an error wrapping multiple validation
// errors returned by SubmitTransitionRequest.ValidateAll() if the designated
// constraints aren't met.
type SubmitTransitionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitTransitionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitTransitionRequestMultiError) AllErrors() []error { return m }

// SubmitTransitionRequestValidationError is the validation error returned by
// SubmitTransitionRequest.Validate if the designated constraints aren't met.
type SubmitTransitionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitTransitionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitTransitionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitTransitionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitTransitionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitTransitionRequestValidationError) ErrorName() string {
	return "SubmitTransitionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitTransitionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitTransitionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitTransitionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitTransitionRequestValidationError{}

// Validate checks the field values on SubmitTransitionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitTransitionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitTransitionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitTransitionResponseMultiError, or nil if none found.
func (m *SubmitTransitionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitTransitionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetNewSnapshot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitTransitionResponseValidationError{
					field:  "NewSnapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitTransitionResponseValidationError{
					field:  "NewSnapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNewSnapshot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitTransitionResponseValidationError{
				field:  "NewSnapshot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TransitionIndex

	if len(errors) > 0 {
		return SubmitTransitionResponseMultiError(errors)
	}

	return nil
}

// SubmitTransitionResponseMultiError is an error wrapping multiple validation
// errors returned by SubmitTransitionResponse.ValidateAll() if the designated
// constraints aren't met.
type SubmitTransitionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitTransitionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitTransitionResponseMultiError) AllErrors() []error { return m }

// SubmitTransitionResponseValidationError is the validation error returned by
// SubmitTransitionResponse.Validate if the designated constraints aren't met.
type SubmitTransitionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitTransitionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitTransitionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitTransitionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitTransitionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitTransitionResponseValidationError) ErrorName() string {
	return "SubmitTransitionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitTransitionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitTransitionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitTransitionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitTransitionResponseValidationError{}

// Validate checks the field values on SubmitUserActionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitUserActionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitUserActionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitUserActionRequestMultiError, or nil if none found.
func (m *SubmitUserActionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitUserActionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitUserActionRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitUserActionRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitUserActionRequestValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetUserEnvelope()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitUserActionRequestValidationError{
					field:  "UserEnvelope",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitUserActionRequestValidationError{
					field:  "UserEnvelope",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserEnvelope()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitUserActionRequestValidationError{
				field:  "UserEnvelope",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TransitionPayload

	if len(errors) > 0 {
		return SubmitUserActionRequestMultiError(errors)
	}

	return nil
}

// SubmitUserActionRequestMultiError is an error wrapping multiple validation
// errors returned by SubmitUserActionRequest.ValidateAll() if the designated
// constraints aren't met.
type SubmitUserActionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitUserActionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitUserActionRequestMultiError) AllErrors() []error { return m }

// SubmitUserActionRequestValidationError is the validation error returned by
// SubmitUserActionRequest.Validate if the designated constraints aren't met.
type SubmitUserActionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitUserActionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitUserActionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitUserActionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitUserActionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitUserActionRequestValidationError) ErrorName() string {
	return "SubmitUserActionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitUserActionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitUserActionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitUserActionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitUserActionRequestValidationError{}

// Validate checks the field values on SubmitUserActionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitUserActionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitUserActionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitUserActionResponseMultiError, or nil if none found.
func (m *SubmitUserActionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitUserActionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetNewSnapshot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitUserActionResponseValidationError{
					field:  "NewSnapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitUserActionResponseValidationError{
					field:  "NewSnapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNewSnapshot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitUserActionResponseValidationError{
				field:  "NewSnapshot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SubmitUserActionResponseMultiError(errors)
	}

	return nil
}

// SubmitUserActionResponseMultiError is an error wrapping multiple validation
// errors returned by SubmitUserActionResponse.ValidateAll() if the designated
// constraints aren't met.
type SubmitUserActionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitUserActionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitUserActionResponseMultiError) AllErrors() []error { return m }

// SubmitUserActionResponseValidationError is the validation error returned by
// SubmitUserActionResponse.Validate if the designated constraints aren't met.
type SubmitUserActionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitUserActionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitUserActionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitUserActionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitUserActionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitUserActionResponseValidationError) ErrorName() string {
	return "SubmitUserActionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitUserActionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitUserActionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitUserActionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitUserActionResponseValidationError{}

// Validate checks the field values on ResolveNameRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResolveNameRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResolveNameRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResolveNameRequestMultiError, or nil if none found.
func (m *ResolveNameRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResolveNameRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CanonicalName

	if len(errors) > 0 {
		return ResolveNameRequestMultiError(errors)
	}

	return nil
}

// ResolveNameRequestMultiError is an error wrapping multiple validation errors
// returned by ResolveNameRequest.ValidateAll() if the designated constraints
// aren't met.
type ResolveNameRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResolveNameRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResolveNameRequestMultiError) AllErrors() []error { return m }

// ResolveNameRequestValidationError is the validation error returned by
// ResolveNameRequest.Validate if the designated constraints aren't met.
type ResolveNameRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResolveNameRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResolveNameRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResolveNameRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResolveNameRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResolveNameRequestValidationError) ErrorName() string {
	return "ResolveNameRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResolveNameRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResolveNameRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResolveNameRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResolveNameRequestValidationError{}

// Validate checks the field values on ResolveNameResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResolveNameResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResolveNameResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResolveNameResponseMultiError, or nil if none found.
func (m *ResolveNameResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResolveNameResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResolveNameResponseValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResolveNameResponseValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResolveNameResponseValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ResolveNameResponseMultiError(errors)
	}

	return nil
}

// ResolveNameResponseMultiError is an error wrapping multiple validation
// errors returned by ResolveNameResponse.ValidateAll() if the designated
// constraints aren't met.
type ResolveNameResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResolveNameResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResolveNameResponseMultiError) AllErrors() []error { return m }

// ResolveNameResponseValidationError is the validation error returned by
// ResolveNameResponse.Validate if the designated constraints aren't met.
type ResolveNameResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResolveNameResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResolveNameResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResolveNameResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResolveNameResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResolveNameResponseValidationError) ErrorName() string {
	return "ResolveNameResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResolveNameResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResolveNameResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResolveNameResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResolveNameResponseValidationError{}

// Validate checks the field values on GetLogRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetLogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLogRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetLogRequestMultiError, or
// nil if none found.
func (m *GetLogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetLogRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetLogRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetLogRequestValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SinceCursor

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetLogRequestMultiError(errors)
	}

	return nil
}

// GetLogRequestMultiError is an error wrapping multiple validation errors
// returned by GetLogRequest.ValidateAll() if the designated constraints
// aren't met.
type GetLogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLogRequestMultiError) AllErrors() []error { return m }

// GetLogRequestValidationError is the validation error returned by
// GetLogRequest.Validate if the designated constraints aren't met.
type GetLogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLogRequestValidationError) ErrorName() string { return "GetLogRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetLogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLogRequestValidationError{}

// Validate checks the field values on GetLogResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetLogResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLogResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetLogResponseMultiError,
// or nil if none found.
func (m *GetLogResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLogResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTransitions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetLogResponseValidationError{
						field:  fmt.Sprintf("Transitions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetLogResponseValidationError{
						field:  fmt.Sprintf("Transitions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetLogResponseValidationError{
					field:  fmt.Sprintf("Transitions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextCursor

	// no validation rules for Total

	if len(errors) > 0 {
		return GetLogResponseMultiError(errors)
	}

	return nil
}

// GetLogResponseMultiError is an error wrapping multiple validation errors
// returned by GetLogResponse.ValidateAll() if the designated constraints
// aren't met.
type GetLogResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLogResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLogResponseMultiError) AllErrors() []error { return m }

// GetLogResponseValidationError is the validation error returned by
// GetLogResponse.Validate if the designated constraints aren't met.
type GetLogResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLogResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLogResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLogResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLogResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLogResponseValidationError) ErrorName() string { return "GetLogResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetLogResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLogResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLogResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLogResponseValidationError{}

// Validate checks the field values on GetSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSnapshotRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSnapshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSnapshotRequestMultiError, or nil if none found.
func (m *GetSnapshotRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSnapshotRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSnapshotRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSnapshotRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSnapshotRequestValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRoot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSnapshotRequestValidationError{
					field:  "Root",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSnapshotRequestValidationError{
					field:  "Root",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRoot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSnapshotRequestValidationError{
				field:  "Root",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSnapshotRequestMultiError(errors)
	}

	return nil
}

// GetSnapshotRequestMultiError is an error wrapping multiple validation errors
// returned by GetSnapshotRequest.ValidateAll() if the designated constraints
// aren't met.
type GetSnapshotRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSnapshotRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSnapshotRequestMultiError) AllErrors() []error { return m }

// GetSnapshotRequestValidationError is the validation error returned by
// GetSnapshotRequest.Validate if the designated constraints aren't met.
type GetSnapshotRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSnapshotRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSnapshotRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSnapshotRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSnapshotRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSnapshotRequestValidationError) ErrorName() string {
	return "GetSnapshotRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSnapshotRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSnapshotRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSnapshotRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSnapshotRequestValidationError{}

// Validate checks the field values on GetSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSnapshotResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSnapshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSnapshotResponseMultiError, or nil if none found.
func (m *GetSnapshotResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSnapshotResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSnapshot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSnapshotResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSnapshotResponseValidationError{
					field:  "Snapshot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSnapshot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSnapshotResponseValidationError{
				field:  "Snapshot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TransitionIndex

	if len(errors) > 0 {
		return GetSnapshotResponseMultiError(errors)
	}

	return nil
}

// GetSnapshotResponseMultiError is an error wrapping multiple validation
// errors returned by GetSnapshotResponse.ValidateAll() if the designated
// constraints aren't met.
type GetSnapshotResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSnapshotResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSnapshotResponseMultiError) AllErrors() []error { return m }

// GetSnapshotResponseValidationError is the validation error returned by
// GetSnapshotResponse.Validate if the designated constraints aren't met.
type GetSnapshotResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSnapshotResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSnapshotResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSnapshotResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSnapshotResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSnapshotResponseValidationError) ErrorName() string {
	return "GetSnapshotResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSnapshotResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSnapshotResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSnapshotResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSnapshotResponseValidationError{}

// Validate checks the field values on SubscribeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubscribeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubscribeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubscribeRequestMultiError, or nil if none found.
func (m *SubscribeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubscribeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubscribeRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubscribeRequestValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubscribeRequestValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SinceIndex

	if len(errors) > 0 {
		return SubscribeRequestMultiError(errors)
	}

	return nil
}

// SubscribeRequestMultiError is an error wrapping multiple validation errors
// returned by SubscribeRequest.ValidateAll() if the designated constraints
// aren't met.
type SubscribeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubscribeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubscribeRequestMultiError) AllErrors() []error { return m }

// SubscribeRequestValidationError is the validation error returned by
// SubscribeRequest.Validate if the designated constraints aren't met.
type SubscribeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubscribeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubscribeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubscribeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubscribeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubscribeRequestValidationError) ErrorName() string { return "SubscribeRequestValidationError" }

// Error satisfies the builtin error interface
func (e SubscribeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubscribeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubscribeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubscribeRequestValidationError{}

// Validate checks the field values on TransitionEvent with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TransitionEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransitionEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TransitionEventMultiError, or nil if none found.
func (m *TransitionEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *TransitionEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTransition()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransitionEventValidationError{
					field:  "Transition",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransitionEventValidationError{
					field:  "Transition",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransition()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransitionEventValidationError{
				field:  "Transition",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetNewStateRoot()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransitionEventValidationError{
					field:  "NewStateRoot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransitionEventValidationError{
					field:  "NewStateRoot",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNewStateRoot()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransitionEventValidationError{
				field:  "NewStateRoot",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TransitionIndex

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransitionEventValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransitionEventValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransitionEventValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TransitionEventMultiError(errors)
	}

	return nil
}

// TransitionEventMultiError is an error wrapping multiple validation errors
// returned by TransitionEvent.ValidateAll() if the designated constraints
// aren't met.
type TransitionEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransitionEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransitionEventMultiError) AllErrors() []error { return m }

// TransitionEventValidationError is the validation error returned by
// TransitionEvent.Validate if the designated constraints aren't met.
type TransitionEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransitionEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransitionEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransitionEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransitionEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransitionEventValidationError) ErrorName() string { return "TransitionEventValidationError" }

// Error satisfies the builtin error interface
func (e TransitionEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransitionEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransitionEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransitionEventValidationError{}

// Validate checks the field values on ListGroupsResponse_GroupSummary with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListGroupsResponse_GroupSummary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListGroupsResponse_GroupSummary with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListGroupsResponse_GroupSummaryMultiError, or nil if none found.
func (m *ListGroupsResponse_GroupSummary) ValidateAll() error {
	return m.validate(true)
}

func (m *ListGroupsResponse_GroupSummary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGroupKey()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListGroupsResponse_GroupSummaryValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListGroupsResponse_GroupSummaryValidationError{
					field:  "GroupKey",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGroupKey()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListGroupsResponse_GroupSummaryValidationError{
				field:  "GroupKey",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CanonicalName

	// no validation rules for DisplayName

	if len(errors) > 0 {
		return ListGroupsResponse_GroupSummaryMultiError(errors)
	}

	return nil
}

// ListGroupsResponse_GroupSummaryMultiError is an error wrapping multiple
// validation errors returned by ListGroupsResponse_GroupSummary.ValidateAll()
// if the designated constraints aren't met.
type ListGroupsResponse_GroupSummaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListGroupsResponse_GroupSummaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListGroupsResponse_GroupSummaryMultiError) AllErrors() []error { return m }

// ListGroupsResponse_GroupSummaryValidationError is the validation error
// returned by ListGroupsResponse_GroupSummary.Validate if the designated
// constraints aren't met.
type ListGroupsResponse_GroupSummaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGroupsResponse_GroupSummaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGroupsResponse_GroupSummaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGroupsResponse_GroupSummaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGroupsResponse_GroupSummaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGroupsResponse_GroupSummaryValidationError) ErrorName() string {
	return "ListGroupsResponse_GroupSummaryValidationError"
}

// Error satisfies the builtin error interface
func (e ListGroupsResponse_GroupSummaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGroupsResponse_GroupSummary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGroupsResponse_GroupSummaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGroupsResponse_GroupSummaryValidationError{}
