// SPDX-License-Identifier: AGPL-3.0
//
// federated-meetup product RPC surface — organizer + attendee facing.
// ConnectRPC over HTTP/2. Auth via magic-link tokens (attendee) or
// organizer tokens (organizer). Public event pages need no auth.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: federated_meetup/product/v1/rpc.proto

package federatedmeetupproductv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublicEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicEventRequest) Reset() {
	*x = GetPublicEventRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicEventRequest) ProtoMessage() {}

func (x *GetPublicEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicEventRequest.ProtoReflect.Descriptor instead.
func (*GetPublicEventRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetPublicEventRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *GetPublicEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetPublicEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Tickets       []*Ticket              `protobuf:"bytes,4,rep,name=tickets,proto3" json:"tickets,omitempty"`
	RsvpCount     uint64                 `protobuf:"varint,3,opt,name=rsvp_count,json=rsvpCount,proto3" json:"rsvp_count,omitempty"`
	Capacity      uint64                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicEventResponse) Reset() {
	*x = GetPublicEventResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicEventResponse) ProtoMessage() {}

func (x *GetPublicEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicEventResponse.ProtoReflect.Descriptor instead.
func (*GetPublicEventResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetPublicEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GetPublicEventResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

func (x *GetPublicEventResponse) GetRsvpCount() uint64 {
	if x != nil {
		return x.RsvpCount
	}
	return 0
}

func (x *GetPublicEventResponse) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type ListUpcomingEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpcomingEventsRequest) Reset() {
	*x = ListUpcomingEventsRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpcomingEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpcomingEventsRequest) ProtoMessage() {}

func (x *ListUpcomingEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpcomingEventsRequest.ProtoReflect.Descriptor instead.
func (*ListUpcomingEventsRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ListUpcomingEventsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListUpcomingEventsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListUpcomingEventsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUpcomingEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpcomingEventsResponse) Reset() {
	*x = ListUpcomingEventsResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpcomingEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpcomingEventsResponse) ProtoMessage() {}

func (x *ListUpcomingEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpcomingEventsResponse.ProtoReflect.Descriptor instead.
func (*ListUpcomingEventsResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ListUpcomingEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListUpcomingEventsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type SubmitRsvpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRsvpRequest) Reset() {
	*x = SubmitRsvpRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRsvpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRsvpRequest) ProtoMessage() {}

func (x *SubmitRsvpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRsvpRequest.ProtoReflect.Descriptor instead.
func (*SubmitRsvpRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitRsvpRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SubmitRsvpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubmitRsvpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SubmitRsvpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rsvp          *Rsvp                  `protobuf:"bytes,2,opt,name=rsvp,proto3" json:"rsvp,omitempty"`
	MagicLink     string                 `protobuf:"bytes,1,opt,name=magic_link,json=magicLink,proto3" json:"magic_link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRsvpResponse) Reset() {
	*x = SubmitRsvpResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRsvpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRsvpResponse) ProtoMessage() {}

func (x *SubmitRsvpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRsvpResponse.ProtoReflect.Descriptor instead.
func (*SubmitRsvpResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitRsvpResponse) GetRsvp() *Rsvp {
	if x != nil {
		return x.Rsvp
	}
	return nil
}

func (x *SubmitRsvpResponse) GetMagicLink() string {
	if x != nil {
		return x.MagicLink
	}
	return ""
}

type CancelRsvpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRsvpRequest) Reset() {
	*x = CancelRsvpRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRsvpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRsvpRequest) ProtoMessage() {}

func (x *CancelRsvpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRsvpRequest.ProtoReflect.Descriptor instead.
func (*CancelRsvpRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRsvpRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CancelRsvpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CancelRsvpRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CancelRsvpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRsvpResponse) Reset() {
	*x = CancelRsvpResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRsvpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRsvpResponse) ProtoMessage() {}

func (x *CancelRsvpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRsvpResponse.ProtoReflect.Descriptor instead.
func (*CancelRsvpResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRsvpResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type ListMyRsvpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRsvpsRequest) Reset() {
	*x = ListMyRsvpsRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRsvpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRsvpsRequest) ProtoMessage() {}

func (x *ListMyRsvpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRsvpsRequest.ProtoReflect.Descriptor instead.
func (*ListMyRsvpsRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *ListMyRsvpsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListMyRsvpsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListMyRsvpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rsvps         []*Rsvp                `protobuf:"bytes,1,rep,name=rsvps,proto3" json:"rsvps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyRsvpsResponse) Reset() {
	*x = ListMyRsvpsResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyRsvpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyRsvpsResponse) ProtoMessage() {}

func (x *ListMyRsvpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyRsvpsResponse.ProtoReflect.Descriptor instead.
func (*ListMyRsvpsResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *ListMyRsvpsResponse) GetRsvps() []*Rsvp {
	if x != nil {
		return x.Rsvps
	}
	return nil
}

type GetOrganizerDashboardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupId        string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OrganizerToken string                 `protobuf:"bytes,2,opt,name=organizer_token,json=organizerToken,proto3" json:"organizer_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizerDashboardRequest) Reset() {
	*x = GetOrganizerDashboardRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizerDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizerDashboardRequest) ProtoMessage() {}

func (x *GetOrganizerDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizerDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizerDashboardRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrganizerDashboardRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetOrganizerDashboardRequest) GetOrganizerToken() string {
	if x != nil {
		return x.OrganizerToken
	}
	return ""
}

type GetOrganizerDashboardResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpcomingEvents []*Event               `protobuf:"bytes,4,rep,name=upcoming_events,json=upcomingEvents,proto3" json:"upcoming_events,omitempty"`
	TotalRsvps     uint64                 `protobuf:"varint,3,opt,name=total_rsvps,json=totalRsvps,proto3" json:"total_rsvps,omitempty"`
	TotalRevenue   *Money                 `protobuf:"bytes,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	PendingActions []string               `protobuf:"bytes,1,rep,name=pending_actions,json=pendingActions,proto3" json:"pending_actions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizerDashboardResponse) Reset() {
	*x = GetOrganizerDashboardResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizerDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizerDashboardResponse) ProtoMessage() {}

func (x *GetOrganizerDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizerDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizerDashboardResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrganizerDashboardResponse) GetUpcomingEvents() []*Event {
	if x != nil {
		return x.UpcomingEvents
	}
	return nil
}

func (x *GetOrganizerDashboardResponse) GetTotalRsvps() uint64 {
	if x != nil {
		return x.TotalRsvps
	}
	return 0
}

func (x *GetOrganizerDashboardResponse) GetTotalRevenue() *Money {
	if x != nil {
		return x.TotalRevenue
	}
	return nil
}

func (x *GetOrganizerDashboardResponse) GetPendingActions() []string {
	if x != nil {
		return x.PendingActions
	}
	return nil
}

type ListAttendeesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OrganizerToken string                 `protobuf:"bytes,2,opt,name=organizer_token,json=organizerToken,proto3" json:"organizer_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAttendeesRequest) Reset() {
	*x = ListAttendeesRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttendeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttendeesRequest) ProtoMessage() {}

func (x *ListAttendeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttendeesRequest.ProtoReflect.Descriptor instead.
func (*ListAttendeesRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *ListAttendeesRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ListAttendeesRequest) GetOrganizerToken() string {
	if x != nil {
		return x.OrganizerToken
	}
	return ""
}

type ListAttendeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendees     []*Rsvp                `protobuf:"bytes,1,rep,name=attendees,proto3" json:"attendees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttendeesResponse) Reset() {
	*x = ListAttendeesResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttendeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttendeesResponse) ProtoMessage() {}

func (x *ListAttendeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttendeesResponse.ProtoReflect.Descriptor instead.
func (*ListAttendeesResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *ListAttendeesResponse) GetAttendees() []*Rsvp {
	if x != nil {
		return x.Attendees
	}
	return nil
}

type CreateTicketRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OrganizerToken string                 `protobuf:"bytes,2,opt,name=organizer_token,json=organizerToken,proto3" json:"organizer_token,omitempty"`
	Ticket         *Ticket                `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTicketRequest) Reset() {
	*x = CreateTicketRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketRequest) ProtoMessage() {}

func (x *CreateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateTicketRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTicketRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateTicketRequest) GetOrganizerToken() string {
	if x != nil {
		return x.OrganizerToken
	}
	return ""
}

func (x *CreateTicketRequest) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type CreateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketResponse) Reset() {
	*x = CreateTicketResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketResponse) ProtoMessage() {}

func (x *CreateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketResponse.ProtoReflect.Descriptor instead.
func (*CreateTicketResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *CreateTicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type ListTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsRequest) Reset() {
	*x = ListTicketsRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsRequest) ProtoMessage() {}

func (x *ListTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsRequest.ProtoReflect.Descriptor instead.
func (*ListTicketsRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *ListTicketsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ListTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickets       []*Ticket              `protobuf:"bytes,1,rep,name=tickets,proto3" json:"tickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketsResponse) Reset() {
	*x = ListTicketsResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketsResponse) ProtoMessage() {}

func (x *ListTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketsResponse.ProtoReflect.Descriptor instead.
func (*ListTicketsResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *ListTicketsResponse) GetTickets() []*Ticket {
	if x != nil {
		return x.Tickets
	}
	return nil
}

type PurchaseTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,4,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	AttendeeEmail string                 `protobuf:"bytes,1,opt,name=attendee_email,json=attendeeEmail,proto3" json:"attendee_email,omitempty"`
	AttendeeName  string                 `protobuf:"bytes,2,opt,name=attendee_name,json=attendeeName,proto3" json:"attendee_name,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseTicketRequest) Reset() {
	*x = PurchaseTicketRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketRequest) ProtoMessage() {}

func (x *PurchaseTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketRequest.ProtoReflect.Descriptor instead.
func (*PurchaseTicketRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *PurchaseTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *PurchaseTicketRequest) GetAttendeeEmail() string {
	if x != nil {
		return x.AttendeeEmail
	}
	return ""
}

func (x *PurchaseTicketRequest) GetAttendeeName() string {
	if x != nil {
		return x.AttendeeName
	}
	return ""
}

func (x *PurchaseTicketRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type PurchaseTicketResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderId           string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StripeCheckoutUrl string                 `protobuf:"bytes,2,opt,name=stripe_checkout_url,json=stripeCheckoutUrl,proto3" json:"stripe_checkout_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PurchaseTicketResponse) Reset() {
	*x = PurchaseTicketResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketResponse) ProtoMessage() {}

func (x *PurchaseTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketResponse.ProtoReflect.Descriptor instead.
func (*PurchaseTicketResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *PurchaseTicketResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PurchaseTicketResponse) GetStripeCheckoutUrl() string {
	if x != nil {
		return x.StripeCheckoutUrl
	}
	return ""
}

type RefundOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrganizerToken string                 `protobuf:"bytes,3,opt,name=organizer_token,json=organizerToken,proto3" json:"organizer_token,omitempty"`
	Amount         uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason         string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundOrderRequest) Reset() {
	*x = RefundOrderRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderRequest) ProtoMessage() {}

func (x *RefundOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderRequest.ProtoReflect.Descriptor instead.
func (*RefundOrderRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *RefundOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RefundOrderRequest) GetOrganizerToken() string {
	if x != nil {
		return x.OrganizerToken
	}
	return ""
}

func (x *RefundOrderRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderResponse) Reset() {
	*x = RefundOrderResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderResponse) ProtoMessage() {}

func (x *RefundOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderResponse.ProtoReflect.Descriptor instead.
func (*RefundOrderResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *RefundOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OrganizerToken string                 `protobuf:"bytes,3,opt,name=organizer_token,json=organizerToken,proto3" json:"organizer_token,omitempty"`
	Cursor         string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize       uint32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *ListOrdersRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ListOrdersRequest) GetOrganizerToken() string {
	if x != nil {
		return x.OrganizerToken
	}
	return ""
}

func (x *ListOrdersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListOrdersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type CheckInAttendeeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AttendeeEmail  string                 `protobuf:"bytes,1,opt,name=attendee_email,json=attendeeEmail,proto3" json:"attendee_email,omitempty"`
	OrganizerToken string                 `protobuf:"bytes,3,opt,name=organizer_token,json=organizerToken,proto3" json:"organizer_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckInAttendeeRequest) Reset() {
	*x = CheckInAttendeeRequest{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInAttendeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInAttendeeRequest) ProtoMessage() {}

func (x *CheckInAttendeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInAttendeeRequest.ProtoReflect.Descriptor instead.
func (*CheckInAttendeeRequest) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *CheckInAttendeeRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CheckInAttendeeRequest) GetAttendeeEmail() string {
	if x != nil {
		return x.AttendeeEmail
	}
	return ""
}

func (x *CheckInAttendeeRequest) GetOrganizerToken() string {
	if x != nil {
		return x.OrganizerToken
	}
	return ""
}

type CheckInAttendeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckedIn     bool                   `protobuf:"varint,1,opt,name=checked_in,json=checkedIn,proto3" json:"checked_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckInAttendeeResponse) Reset() {
	*x = CheckInAttendeeResponse{}
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckInAttendeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInAttendeeResponse) ProtoMessage() {}

func (x *CheckInAttendeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInAttendeeResponse.ProtoReflect.Descriptor instead.
func (*CheckInAttendeeResponse) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_rpc_proto_rawDescGZIP(), []int{25}
}

func (x *CheckInAttendeeResponse) GetCheckedIn() bool {
	if x != nil {
		return x.CheckedIn
	}
	return false
}

var File_federated_meetup_product_v1_rpc_proto protoreflect.FileDescriptor

const file_federated_meetup_product_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"%federated_meetup/product/v1/rpc.proto\x12\x1bfederated_meetup.product.v1\x1a'federated_meetup/product/v1/state.proto\"F\n" +
	"\x15GetPublicEventRequest\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\xcc\x01\n" +
	"\x16GetPublicEventResponse\x128\n" +
	"\x05event\x18\x02 \x01(\v2\".federated_meetup.product.v1.EventR\x05event\x12=\n" +
	"\atickets\x18\x04 \x03(\v2#.federated_meetup.product.v1.TicketR\atickets\x12\x1d\n" +
	"\n" +
	"rsvp_count\x18\x03 \x01(\x04R\trsvpCount\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x04R\bcapacity\"k\n" +
	"\x19ListUpcomingEventsRequest\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"y\n" +
	"\x1aListUpcomingEventsResponse\x12:\n" +
	"\x06events\x18\x01 \x03(\v2\".federated_meetup.product.v1.EventR\x06events\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"X\n" +
	"\x11SubmitRsvpRequest\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"j\n" +
	"\x12SubmitRsvpResponse\x125\n" +
	"\x04rsvp\x18\x02 \x01(\v2!.federated_meetup.product.v1.RsvpR\x04rsvp\x12\x1d\n" +
	"\n" +
	"magic_link\x18\x01 \x01(\tR\tmagicLink\"Z\n" +
	"\x11CancelRsvpRequest\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"2\n" +
	"\x12CancelRsvpResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"@\n" +
	"\x12ListMyRsvpsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"N\n" +
	"\x13ListMyRsvpsResponse\x127\n" +
	"\x05rsvps\x18\x01 \x03(\v2!.federated_meetup.product.v1.RsvpR\x05rsvps\"b\n" +
	"\x1cGetOrganizerDashboardRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12'\n" +
	"\x0forganizer_token\x18\x02 \x01(\tR\x0eorganizerToken\"\xff\x01\n" +
	"\x1dGetOrganizerDashboardResponse\x12K\n" +
	"\x0fupcoming_events\x18\x04 \x03(\v2\".federated_meetup.product.v1.EventR\x0eupcomingEvents\x12\x1f\n" +
	"\vtotal_rsvps\x18\x03 \x01(\x04R\n" +
	"totalRsvps\x12G\n" +
	"\rtotal_revenue\x18\x02 \x01(\v2\".federated_meetup.product.v1.MoneyR\ftotalRevenue\x12'\n" +
	"\x0fpending_actions\x18\x01 \x03(\tR\x0ependingActions\"Z\n" +
	"\x14ListAttendeesRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0forganizer_token\x18\x02 \x01(\tR\x0eorganizerToken\"X\n" +
	"\x15ListAttendeesResponse\x12?\n" +
	"\tattendees\x18\x01 \x03(\v2!.federated_meetup.product.v1.RsvpR\tattendees\"\x96\x01\n" +
	"\x13CreateTicketRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0forganizer_token\x18\x02 \x01(\tR\x0eorganizerToken\x12;\n" +
	"\x06ticket\x18\x03 \x01(\v2#.federated_meetup.product.v1.TicketR\x06ticket\"3\n" +
	"\x14CreateTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"/\n" +
	"\x12ListTicketsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"T\n" +
	"\x13ListTicketsResponse\x12=\n" +
	"\atickets\x18\x01 \x03(\v2#.federated_meetup.product.v1.TicketR\atickets\"\x9c\x01\n" +
	"\x15PurchaseTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x04 \x01(\tR\bticketId\x12%\n" +
	"\x0eattendee_email\x18\x01 \x01(\tR\rattendeeEmail\x12#\n" +
	"\rattendee_name\x18\x02 \x01(\tR\fattendeeName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\"c\n" +
	"\x16PurchaseTicketResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12.\n" +
	"\x13stripe_checkout_url\x18\x02 \x01(\tR\x11stripeCheckoutUrl\"\x88\x01\n" +
	"\x12RefundOrderRequest\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12'\n" +
	"\x0forganizer_token\x18\x03 \x01(\tR\x0eorganizerToken\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"O\n" +
	"\x13RefundOrderResponse\x128\n" +
	"\x05order\x18\x01 \x01(\v2\".federated_meetup.product.v1.OrderR\x05order\"\x8c\x01\n" +
	"\x11ListOrdersRequest\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12'\n" +
	"\x0forganizer_token\x18\x03 \x01(\tR\x0eorganizerToken\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\rR\bpageSize\"q\n" +
	"\x12ListOrdersResponse\x12:\n" +
	"\x06orders\x18\x02 \x03(\v2\".federated_meetup.product.v1.OrderR\x06orders\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\"\x83\x01\n" +
	"\x16CheckInAttendeeRequest\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12%\n" +
	"\x0eattendee_email\x18\x01 \x01(\tR\rattendeeEmail\x12'\n" +
	"\x0forganizer_token\x18\x03 \x01(\tR\x0eorganizerToken\"8\n" +
	"\x17CheckInAttendeeResponse\x12\x1d\n" +
	"\n" +
	"checked_in\x18\x01 \x01(\bR\tcheckedIn2\xad\f\n" +
	"\x0eProductService\x12y\n" +
	"\x0eGetPublicEvent\x122.federated_meetup.product.v1.GetPublicEventRequest\x1a3.federated_meetup.product.v1.GetPublicEventResponse\x12\x85\x01\n" +
	"\x12ListUpcomingEvents\x126.federated_meetup.product.v1.ListUpcomingEventsRequest\x1a7.federated_meetup.product.v1.ListUpcomingEventsResponse\x12p\n" +
	"\vListTickets\x12/.federated_meetup.product.v1.ListTicketsRequest\x1a0.federated_meetup.product.v1.ListTicketsResponse\x12m\n" +
	"\n" +
	"SubmitRsvp\x12..federated_meetup.product.v1.SubmitRsvpRequest\x1a/.federated_meetup.product.v1.SubmitRsvpResponse\x12m\n" +
	"\n" +
	"CancelRsvp\x12..federated_meetup.product.v1.CancelRsvpRequest\x1a/.federated_meetup.product.v1.CancelRsvpResponse\x12p\n" +
	"\vListMyRsvps\x12/.federated_meetup.product.v1.ListMyRsvpsRequest\x1a0.federated_meetup.product.v1.ListMyRsvpsResponse\x12y\n" +
	"\x0ePurchaseTicket\x122.federated_meetup.product.v1.PurchaseTicketRequest\x1a3.federated_meetup.product.v1.PurchaseTicketResponse\x12\x8e\x01\n" +
	"\x15GetOrganizerDashboard\x129.federated_meetup.product.v1.GetOrganizerDashboardRequest\x1a:.federated_meetup.product.v1.GetOrganizerDashboardResponse\x12v\n" +
	"\rListAttendees\x121.federated_meetup.product.v1.ListAttendeesRequest\x1a2.federated_meetup.product.v1.ListAttendeesResponse\x12s\n" +
	"\fCreateTicket\x120.federated_meetup.product.v1.CreateTicketRequest\x1a1.federated_meetup.product.v1.CreateTicketResponse\x12p\n" +
	"\vRefundOrder\x12/.federated_meetup.product.v1.RefundOrderRequest\x1a0.federated_meetup.product.v1.RefundOrderResponse\x12m\n" +
	"\n" +
	"ListOrders\x12..federated_meetup.product.v1.ListOrdersRequest\x1a/.federated_meetup.product.v1.ListOrdersResponse\x12|\n" +
	"\x0fCheckInAttendee\x123.federated_meetup.product.v1.CheckInAttendeeRequest\x1a4.federated_meetup.product.v1.CheckInAttendeeResponseB`Z^github.com/sscoble/federated-meetup/proto/federated_meetup/product/v1;federatedmeetupproductv1b\x06proto3"

var (
	file_federated_meetup_product_v1_rpc_proto_rawDescOnce sync.Once
	file_federated_meetup_product_v1_rpc_proto_rawDescData []byte
)

func file_federated_meetup_product_v1_rpc_proto_rawDescGZIP() []byte {
	file_federated_meetup_product_v1_rpc_proto_rawDescOnce.Do(func() {
		file_federated_meetup_product_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federated_meetup_product_v1_rpc_proto_rawDesc), len(file_federated_meetup_product_v1_rpc_proto_rawDesc)))
	})
	return file_federated_meetup_product_v1_rpc_proto_rawDescData
}

var file_federated_meetup_product_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_federated_meetup_product_v1_rpc_proto_goTypes = []any{
	(*GetPublicEventRequest)(nil),         // 0: federated_meetup.product.v1.GetPublicEventRequest
	(*GetPublicEventResponse)(nil),        // 1: federated_meetup.product.v1.GetPublicEventResponse
	(*ListUpcomingEventsRequest)(nil),     // 2: federated_meetup.product.v1.ListUpcomingEventsRequest
	(*ListUpcomingEventsResponse)(nil),    // 3: federated_meetup.product.v1.ListUpcomingEventsResponse
	(*SubmitRsvpRequest)(nil),             // 4: federated_meetup.product.v1.SubmitRsvpRequest
	(*SubmitRsvpResponse)(nil),            // 5: federated_meetup.product.v1.SubmitRsvpResponse
	(*CancelRsvpRequest)(nil),             // 6: federated_meetup.product.v1.CancelRsvpRequest
	(*CancelRsvpResponse)(nil),            // 7: federated_meetup.product.v1.CancelRsvpResponse
	(*ListMyRsvpsRequest)(nil),            // 8: federated_meetup.product.v1.ListMyRsvpsRequest
	(*ListMyRsvpsResponse)(nil),           // 9: federated_meetup.product.v1.ListMyRsvpsResponse
	(*GetOrganizerDashboardRequest)(nil),  // 10: federated_meetup.product.v1.GetOrganizerDashboardRequest
	(*GetOrganizerDashboardResponse)(nil), // 11: federated_meetup.product.v1.GetOrganizerDashboardResponse
	(*ListAttendeesRequest)(nil),          // 12: federated_meetup.product.v1.ListAttendeesRequest
	(*ListAttendeesResponse)(nil),         // 13: federated_meetup.product.v1.ListAttendeesResponse
	(*CreateTicketRequest)(nil),           // 14: federated_meetup.product.v1.CreateTicketRequest
	(*CreateTicketResponse)(nil),          // 15: federated_meetup.product.v1.CreateTicketResponse
	(*ListTicketsRequest)(nil),            // 16: federated_meetup.product.v1.ListTicketsRequest
	(*ListTicketsResponse)(nil),           // 17: federated_meetup.product.v1.ListTicketsResponse
	(*PurchaseTicketRequest)(nil),         // 18: federated_meetup.product.v1.PurchaseTicketRequest
	(*PurchaseTicketResponse)(nil),        // 19: federated_meetup.product.v1.PurchaseTicketResponse
	(*RefundOrderRequest)(nil),            // 20: federated_meetup.product.v1.RefundOrderRequest
	(*RefundOrderResponse)(nil),           // 21: federated_meetup.product.v1.RefundOrderResponse
	(*ListOrdersRequest)(nil),             // 22: federated_meetup.product.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),            // 23: federated_meetup.product.v1.ListOrdersResponse
	(*CheckInAttendeeRequest)(nil),        // 24: federated_meetup.product.v1.CheckInAttendeeRequest
	(*CheckInAttendeeResponse)(nil),       // 25: federated_meetup.product.v1.CheckInAttendeeResponse
	(*Event)(nil),                         // 26: federated_meetup.product.v1.Event
	(*Ticket)(nil),                        // 27: federated_meetup.product.v1.Ticket
	(*Rsvp)(nil),                          // 28: federated_meetup.product.v1.Rsvp
	(*Money)(nil),                         // 29: federated_meetup.product.v1.Money
	(*Order)(nil),                         // 30: federated_meetup.product.v1.Order
}
var file_federated_meetup_product_v1_rpc_proto_depIdxs = []int32{
	26, // 0: federated_meetup.product.v1.GetPublicEventResponse.event:type_name -> federated_meetup.product.v1.Event
	27, // 1: federated_meetup.product.v1.GetPublicEventResponse.tickets:type_name -> federated_meetup.product.v1.Ticket
	26, // 2: federated_meetup.product.v1.ListUpcomingEventsResponse.events:type_name -> federated_meetup.product.v1.Event
	28, // 3: federated_meetup.product.v1.SubmitRsvpResponse.rsvp:type_name -> federated_meetup.product.v1.Rsvp
	28, // 4: federated_meetup.product.v1.ListMyRsvpsResponse.rsvps:type_name -> federated_meetup.product.v1.Rsvp
	26, // 5: federated_meetup.product.v1.GetOrganizerDashboardResponse.upcoming_events:type_name -> federated_meetup.product.v1.Event
	29, // 6: federated_meetup.product.v1.GetOrganizerDashboardResponse.total_revenue:type_name -> federated_meetup.product.v1.Money
	28, // 7: federated_meetup.product.v1.ListAttendeesResponse.attendees:type_name -> federated_meetup.product.v1.Rsvp
	27, // 8: federated_meetup.product.v1.CreateTicketRequest.ticket:type_name -> federated_meetup.product.v1.Ticket
	27, // 9: federated_meetup.product.v1.ListTicketsResponse.tickets:type_name -> federated_meetup.product.v1.Ticket
	30, // 10: federated_meetup.product.v1.RefundOrderResponse.order:type_name -> federated_meetup.product.v1.Order
	30, // 11: federated_meetup.product.v1.ListOrdersResponse.orders:type_name -> federated_meetup.product.v1.Order
	0,  // 12: federated_meetup.product.v1.ProductService.GetPublicEvent:input_type -> federated_meetup.product.v1.GetPublicEventRequest
	2,  // 13: federated_meetup.product.v1.ProductService.ListUpcomingEvents:input_type -> federated_meetup.product.v1.ListUpcomingEventsRequest
	16, // 14: federated_meetup.product.v1.ProductService.ListTickets:input_type -> federated_meetup.product.v1.ListTicketsRequest
	4,  // 15: federated_meetup.product.v1.ProductService.SubmitRsvp:input_type -> federated_meetup.product.v1.SubmitRsvpRequest
	6,  // 16: federated_meetup.product.v1.ProductService.CancelRsvp:input_type -> federated_meetup.product.v1.CancelRsvpRequest
	8,  // 17: federated_meetup.product.v1.ProductService.ListMyRsvps:input_type -> federated_meetup.product.v1.ListMyRsvpsRequest
	18, // 18: federated_meetup.product.v1.ProductService.PurchaseTicket:input_type -> federated_meetup.product.v1.PurchaseTicketRequest
	10, // 19: federated_meetup.product.v1.ProductService.GetOrganizerDashboard:input_type -> federated_meetup.product.v1.GetOrganizerDashboardRequest
	12, // 20: federated_meetup.product.v1.ProductService.ListAttendees:input_type -> federated_meetup.product.v1.ListAttendeesRequest
	14, // 21: federated_meetup.product.v1.ProductService.CreateTicket:input_type -> federated_meetup.product.v1.CreateTicketRequest
	20, // 22: federated_meetup.product.v1.ProductService.RefundOrder:input_type -> federated_meetup.product.v1.RefundOrderRequest
	22, // 23: federated_meetup.product.v1.ProductService.ListOrders:input_type -> federated_meetup.product.v1.ListOrdersRequest
	24, // 24: federated_meetup.product.v1.ProductService.CheckInAttendee:input_type -> federated_meetup.product.v1.CheckInAttendeeRequest
	1,  // 25: federated_meetup.product.v1.ProductService.GetPublicEvent:output_type -> federated_meetup.product.v1.GetPublicEventResponse
	3,  // 26: federated_meetup.product.v1.ProductService.ListUpcomingEvents:output_type -> federated_meetup.product.v1.ListUpcomingEventsResponse
	17, // 27: federated_meetup.product.v1.ProductService.ListTickets:output_type -> federated_meetup.product.v1.ListTicketsResponse
	5,  // 28: federated_meetup.product.v1.ProductService.SubmitRsvp:output_type -> federated_meetup.product.v1.SubmitRsvpResponse
	7,  // 29: federated_meetup.product.v1.ProductService.CancelRsvp:output_type -> federated_meetup.product.v1.CancelRsvpResponse
	9,  // 30: federated_meetup.product.v1.ProductService.ListMyRsvps:output_type -> federated_meetup.product.v1.ListMyRsvpsResponse
	19, // 31: federated_meetup.product.v1.ProductService.PurchaseTicket:output_type -> federated_meetup.product.v1.PurchaseTicketResponse
	11, // 32: federated_meetup.product.v1.ProductService.GetOrganizerDashboard:output_type -> federated_meetup.product.v1.GetOrganizerDashboardResponse
	13, // 33: federated_meetup.product.v1.ProductService.ListAttendees:output_type -> federated_meetup.product.v1.ListAttendeesResponse
	15, // 34: federated_meetup.product.v1.ProductService.CreateTicket:output_type -> federated_meetup.product.v1.CreateTicketResponse
	21, // 35: federated_meetup.product.v1.ProductService.RefundOrder:output_type -> federated_meetup.product.v1.RefundOrderResponse
	23, // 36: federated_meetup.product.v1.ProductService.ListOrders:output_type -> federated_meetup.product.v1.ListOrdersResponse
	25, // 37: federated_meetup.product.v1.ProductService.CheckInAttendee:output_type -> federated_meetup.product.v1.CheckInAttendeeResponse
	25, // [25:38] is the sub-list for method output_type
	12, // [12:25] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_federated_meetup_product_v1_rpc_proto_init() }
func file_federated_meetup_product_v1_rpc_proto_init() {
	if File_federated_meetup_product_v1_rpc_proto != nil {
		return
	}
	file_federated_meetup_product_v1_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federated_meetup_product_v1_rpc_proto_rawDesc), len(file_federated_meetup_product_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federated_meetup_product_v1_rpc_proto_goTypes,
		DependencyIndexes: file_federated_meetup_product_v1_rpc_proto_depIdxs,
		MessageInfos:      file_federated_meetup_product_v1_rpc_proto_msgTypes,
	}.Build()
	File_federated_meetup_product_v1_rpc_proto = out.File
	file_federated_meetup_product_v1_rpc_proto_goTypes = nil
	file_federated_meetup_product_v1_rpc_proto_depIdxs = nil
}
