// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: federated_meetup/product/v1/rpc.proto

package federatedmeetupproductv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetPublicEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPublicEventRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPublicEventRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPublicEventRequestMultiError, or nil if none found.
func (m *GetPublicEventRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPublicEventRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Slug

	// no validation rules for EventId

	if len(errors) > 0 {
		return GetPublicEventRequestMultiError(errors)
	}

	return nil
}

// GetPublicEventRequestMultiError is an error wrapping multiple validation
// errors returned by GetPublicEventRequest.ValidateAll() if the designated
// constraints aren't met.
type GetPublicEventRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPublicEventRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPublicEventRequestMultiError) AllErrors() []error { return m }

// GetPublicEventRequestValidationError is the validation error returned by
// GetPublicEventRequest.Validate if the designated constraints aren't met.
type GetPublicEventRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPublicEventRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPublicEventRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPublicEventRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPublicEventRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPublicEventRequestValidationError) ErrorName() string {
	return "GetPublicEventRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetPublicEventRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPublicEventRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPublicEventRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPublicEventRequestValidationError{}

// Validate checks the field values on GetPublicEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetPublicEventResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetPublicEventResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetPublicEventResponseMultiError, or nil if none found.
func (m *GetPublicEventResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetPublicEventResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetEvent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetPublicEventResponseValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetPublicEventResponseValidationError{
					field:  "Event",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEvent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetPublicEventResponseValidationError{
				field:  "Event",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetTickets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetPublicEventResponseValidationError{
						field:  fmt.Sprintf("Tickets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetPublicEventResponseValidationError{
						field:  fmt.Sprintf("Tickets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetPublicEventResponseValidationError{
					field:  fmt.Sprintf("Tickets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for RsvpCount

	// no validation rules for Capacity

	if len(errors) > 0 {
		return GetPublicEventResponseMultiError(errors)
	}

	return nil
}

// GetPublicEventResponseMultiError is an error wrapping multiple validation
// errors returned by GetPublicEventResponse.ValidateAll() if the designated
// constraints aren't met.
type GetPublicEventResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetPublicEventResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetPublicEventResponseMultiError) AllErrors() []error { return m }

// GetPublicEventResponseValidationError is the validation error returned by
// GetPublicEventResponse.Validate if the designated constraints aren't met.
type GetPublicEventResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetPublicEventResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetPublicEventResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetPublicEventResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetPublicEventResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetPublicEventResponseValidationError) ErrorName() string {
	return "GetPublicEventResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetPublicEventResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetPublicEventResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetPublicEventResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetPublicEventResponseValidationError{}

// Validate checks the field values on ListUpcomingEventsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUpcomingEventsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUpcomingEventsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUpcomingEventsRequestMultiError, or nil if none found.
func (m *ListUpcomingEventsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUpcomingEventsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for Cursor

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListUpcomingEventsRequestMultiError(errors)
	}

	return nil
}

// ListUpcomingEventsRequestMultiError is an error wrapping multiple validation
// errors returned by ListUpcomingEventsRequest.ValidateAll() if the
// designated constraints aren't met.
type ListUpcomingEventsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUpcomingEventsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUpcomingEventsRequestMultiError) AllErrors() []error { return m }

// ListUpcomingEventsRequestValidationError is the validation error returned by
// ListUpcomingEventsRequest.Validate if the designated constraints aren't met.
type ListUpcomingEventsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUpcomingEventsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUpcomingEventsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUpcomingEventsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUpcomingEventsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUpcomingEventsRequestValidationError) ErrorName() string {
	return "ListUpcomingEventsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListUpcomingEventsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUpcomingEventsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUpcomingEventsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUpcomingEventsRequestValidationError{}

// Validate checks the field values on ListUpcomingEventsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUpcomingEventsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUpcomingEventsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUpcomingEventsResponseMultiError, or nil if none found.
func (m *ListUpcomingEventsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUpcomingEventsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListUpcomingEventsResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListUpcomingEventsResponseValidationError{
						field:  fmt.Sprintf("Events[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListUpcomingEventsResponseValidationError{
					field:  fmt.Sprintf("Events[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextCursor

	if len(errors) > 0 {
		return ListUpcomingEventsResponseMultiError(errors)
	}

	return nil
}

// ListUpcomingEventsResponseMultiError is an error wrapping multiple
// validation errors returned by ListUpcomingEventsResponse.ValidateAll() if
// the designated constraints aren't met.
type ListUpcomingEventsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUpcomingEventsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUpcomingEventsResponseMultiError) AllErrors() []error { return m }

// ListUpcomingEventsResponseValidationError is the validation error returned
// by ListUpcomingEventsResponse.Validate if the designated constraints aren't met.
type ListUpcomingEventsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUpcomingEventsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUpcomingEventsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUpcomingEventsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUpcomingEventsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUpcomingEventsResponseValidationError) ErrorName() string {
	return "ListUpcomingEventsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListUpcomingEventsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUpcomingEventsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUpcomingEventsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUpcomingEventsResponseValidationError{}

// Validate checks the field values on SubmitRsvpRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SubmitRsvpRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitRsvpRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitRsvpRequestMultiError, or nil if none found.
func (m *SubmitRsvpRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitRsvpRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for Email

	// no validation rules for Name

	if len(errors) > 0 {
		return SubmitRsvpRequestMultiError(errors)
	}

	return nil
}

// SubmitRsvpRequestMultiError is an error wrapping multiple validation errors
// returned by SubmitRsvpRequest.ValidateAll() if the designated constraints
// aren't met.
type SubmitRsvpRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitRsvpRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitRsvpRequestMultiError) AllErrors() []error { return m }

// SubmitRsvpRequestValidationError is the validation error returned by
// SubmitRsvpRequest.Validate if the designated constraints aren't met.
type SubmitRsvpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitRsvpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitRsvpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitRsvpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitRsvpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitRsvpRequestValidationError) ErrorName() string {
	return "SubmitRsvpRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitRsvpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitRsvpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitRsvpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitRsvpRequestValidationError{}

// Validate checks the field values on SubmitRsvpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmitRsvpResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmitRsvpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmitRsvpResponseMultiError, or nil if none found.
func (m *SubmitRsvpResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmitRsvpResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRsvp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SubmitRsvpResponseValidationError{
					field:  "Rsvp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SubmitRsvpResponseValidationError{
					field:  "Rsvp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRsvp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SubmitRsvpResponseValidationError{
				field:  "Rsvp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for MagicLink

	if len(errors) > 0 {
		return SubmitRsvpResponseMultiError(errors)
	}

	return nil
}

// SubmitRsvpResponseMultiError is an error wrapping multiple validation errors
// returned by SubmitRsvpResponse.ValidateAll() if the designated constraints
// aren't met.
type SubmitRsvpResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmitRsvpResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmitRsvpResponseMultiError) AllErrors() []error { return m }

// SubmitRsvpResponseValidationError is the validation error returned by
// SubmitRsvpResponse.Validate if the designated constraints aren't met.
type SubmitRsvpResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmitRsvpResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmitRsvpResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmitRsvpResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmitRsvpResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmitRsvpResponseValidationError) ErrorName() string {
	return "SubmitRsvpResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SubmitRsvpResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmitRsvpResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmitRsvpResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmitRsvpResponseValidationError{}

// Validate checks the field values on CancelRsvpRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CancelRsvpRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelRsvpRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelRsvpRequestMultiError, or nil if none found.
func (m *CancelRsvpRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelRsvpRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for Email

	// no validation rules for Token

	if len(errors) > 0 {
		return CancelRsvpRequestMultiError(errors)
	}

	return nil
}

// CancelRsvpRequestMultiError is an error wrapping multiple validation errors
// returned by CancelRsvpRequest.ValidateAll() if the designated constraints
// aren't met.
type CancelRsvpRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelRsvpRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelRsvpRequestMultiError) AllErrors() []error { return m }

// CancelRsvpRequestValidationError is the validation error returned by
// CancelRsvpRequest.Validate if the designated constraints aren't met.
type CancelRsvpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelRsvpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelRsvpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelRsvpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelRsvpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelRsvpRequestValidationError) ErrorName() string {
	return "CancelRsvpRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CancelRsvpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelRsvpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelRsvpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelRsvpRequestValidationError{}

// Validate checks the field values on CancelRsvpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CancelRsvpResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CancelRsvpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CancelRsvpResponseMultiError, or nil if none found.
func (m *CancelRsvpResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CancelRsvpResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Cancelled

	if len(errors) > 0 {
		return CancelRsvpResponseMultiError(errors)
	}

	return nil
}

// CancelRsvpResponseMultiError is an error wrapping multiple validation errors
// returned by CancelRsvpResponse.ValidateAll() if the designated constraints
// aren't met.
type CancelRsvpResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CancelRsvpResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CancelRsvpResponseMultiError) AllErrors() []error { return m }

// CancelRsvpResponseValidationError is the validation error returned by
// CancelRsvpResponse.Validate if the designated constraints aren't met.
type CancelRsvpResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CancelRsvpResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CancelRsvpResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CancelRsvpResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CancelRsvpResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CancelRsvpResponseValidationError) ErrorName() string {
	return "CancelRsvpResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CancelRsvpResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCancelRsvpResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CancelRsvpResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CancelRsvpResponseValidationError{}

// Validate checks the field values on ListMyRsvpsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMyRsvpsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMyRsvpsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMyRsvpsRequestMultiError, or nil if none found.
func (m *ListMyRsvpsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMyRsvpsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Email

	// no validation rules for Token

	if len(errors) > 0 {
		return ListMyRsvpsRequestMultiError(errors)
	}

	return nil
}

// ListMyRsvpsRequestMultiError is an error wrapping multiple validation errors
// returned by ListMyRsvpsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListMyRsvpsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMyRsvpsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMyRsvpsRequestMultiError) AllErrors() []error { return m }

// ListMyRsvpsRequestValidationError is the validation error returned by
// ListMyRsvpsRequest.Validate if the designated constraints aren't met.
type ListMyRsvpsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMyRsvpsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMyRsvpsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMyRsvpsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMyRsvpsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMyRsvpsRequestValidationError) ErrorName() string {
	return "ListMyRsvpsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListMyRsvpsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMyRsvpsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMyRsvpsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMyRsvpsRequestValidationError{}

// Validate checks the field values on ListMyRsvpsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListMyRsvpsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListMyRsvpsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListMyRsvpsResponseMultiError, or nil if none found.
func (m *ListMyRsvpsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListMyRsvpsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRsvps() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListMyRsvpsResponseValidationError{
						field:  fmt.Sprintf("Rsvps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListMyRsvpsResponseValidationError{
						field:  fmt.Sprintf("Rsvps[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListMyRsvpsResponseValidationError{
					field:  fmt.Sprintf("Rsvps[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListMyRsvpsResponseMultiError(errors)
	}

	return nil
}

// ListMyRsvpsResponseMultiError is an error wrapping multiple validation
// errors returned by ListMyRsvpsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListMyRsvpsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListMyRsvpsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListMyRsvpsResponseMultiError) AllErrors() []error { return m }

// ListMyRsvpsResponseValidationError is the validation error returned by
// ListMyRsvpsResponse.Validate if the designated constraints aren't met.
type ListMyRsvpsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListMyRsvpsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListMyRsvpsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListMyRsvpsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListMyRsvpsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListMyRsvpsResponseValidationError) ErrorName() string {
	return "ListMyRsvpsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListMyRsvpsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListMyRsvpsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListMyRsvpsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListMyRsvpsResponseValidationError{}

// Validate checks the field values on GetOrganizerDashboardRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetOrganizerDashboardRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOrganizerDashboardRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetOrganizerDashboardRequestMultiError, or nil if none found.
func (m *GetOrganizerDashboardRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOrganizerDashboardRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	// no validation rules for OrganizerToken

	if len(errors) > 0 {
		return GetOrganizerDashboardRequestMultiError(errors)
	}

	return nil
}

// GetOrganizerDashboardRequestMultiError is an error wrapping multiple
// validation errors returned by GetOrganizerDashboardRequest.ValidateAll() if
// the designated constraints aren't met.
type GetOrganizerDashboardRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOrganizerDashboardRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOrganizerDashboardRequestMultiError) AllErrors() []error { return m }

// GetOrganizerDashboardRequestValidationError is the validation error returned
// by GetOrganizerDashboardRequest.Validate if the designated constraints
// aren't met.
type GetOrganizerDashboardRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrganizerDashboardRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrganizerDashboardRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrganizerDashboardRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrganizerDashboardRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrganizerDashboardRequestValidationError) ErrorName() string {
	return "GetOrganizerDashboardRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrganizerDashboardRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrganizerDashboardRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrganizerDashboardRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrganizerDashboardRequestValidationError{}

// Validate checks the field values on GetOrganizerDashboardResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetOrganizerDashboardResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOrganizerDashboardResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetOrganizerDashboardResponseMultiError, or nil if none found.
func (m *GetOrganizerDashboardResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOrganizerDashboardResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetUpcomingEvents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetOrganizerDashboardResponseValidationError{
						field:  fmt.Sprintf("UpcomingEvents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetOrganizerDashboardResponseValidationError{
						field:  fmt.Sprintf("UpcomingEvents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetOrganizerDashboardResponseValidationError{
					field:  fmt.Sprintf("UpcomingEvents[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalRsvps

	if all {
		switch v := interface{}(m.GetTotalRevenue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetOrganizerDashboardResponseValidationError{
					field:  "TotalRevenue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetOrganizerDashboardResponseValidationError{
					field:  "TotalRevenue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTotalRevenue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetOrganizerDashboardResponseValidationError{
				field:  "TotalRevenue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetOrganizerDashboardResponseMultiError(errors)
	}

	return nil
}

// GetOrganizerDashboardResponseMultiError is an error wrapping multiple
// validation errors returned by GetOrganizerDashboardResponse.ValidateAll()
// if the designated constraints aren't met.
type GetOrganizerDashboardResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOrganizerDashboardResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOrganizerDashboardResponseMultiError) AllErrors() []error { return m }

// GetOrganizerDashboardResponseValidationError is the validation error
// returned by GetOrganizerDashboardResponse.Validate if the designated
// constraints aren't met.
type GetOrganizerDashboardResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrganizerDashboardResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrganizerDashboardResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrganizerDashboardResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrganizerDashboardResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrganizerDashboardResponseValidationError) ErrorName() string {
	return "GetOrganizerDashboardResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrganizerDashboardResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrganizerDashboardResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrganizerDashboardResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrganizerDashboardResponseValidationError{}

// Validate checks the field values on ListAttendeesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAttendeesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAttendeesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAttendeesRequestMultiError, or nil if none found.
func (m *ListAttendeesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAttendeesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for OrganizerToken

	if len(errors) > 0 {
		return ListAttendeesRequestMultiError(errors)
	}

	return nil
}

// ListAttendeesRequestMultiError is an error wrapping multiple validation
// errors returned by ListAttendeesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAttendeesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAttendeesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAttendeesRequestMultiError) AllErrors() []error { return m }

// ListAttendeesRequestValidationError is the validation error returned by
// ListAttendeesRequest.Validate if the designated constraints aren't met.
type ListAttendeesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAttendeesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAttendeesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAttendeesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAttendeesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAttendeesRequestValidationError) ErrorName() string {
	return "ListAttendeesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAttendeesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAttendeesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAttendeesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAttendeesRequestValidationError{}

// Validate checks the field values on ListAttendeesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAttendeesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAttendeesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAttendeesResponseMultiError, or nil if none found.
func (m *ListAttendeesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAttendeesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAttendees() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAttendeesResponseValidationError{
						field:  fmt.Sprintf("Attendees[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAttendeesResponseValidationError{
						field:  fmt.Sprintf("Attendees[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAttendeesResponseValidationError{
					field:  fmt.Sprintf("Attendees[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListAttendeesResponseMultiError(errors)
	}

	return nil
}

// ListAttendeesResponseMultiError is an error wrapping multiple validation
// errors returned by ListAttendeesResponse.ValidateAll() if the designated
// constraints aren't met.
type ListAttendeesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAttendeesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAttendeesResponseMultiError) AllErrors() []error { return m }

// ListAttendeesResponseValidationError is the validation error returned by
// ListAttendeesResponse.Validate if the designated constraints aren't met.
type ListAttendeesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAttendeesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAttendeesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAttendeesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAttendeesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAttendeesResponseValidationError) ErrorName() string {
	return "ListAttendeesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAttendeesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAttendeesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAttendeesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAttendeesResponseValidationError{}

// Validate checks the field values on CreateTicketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTicketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTicketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTicketRequestMultiError, or nil if none found.
func (m *CreateTicketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTicketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for OrganizerToken

	if all {
		switch v := interface{}(m.GetTicket()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateTicketRequestValidationError{
					field:  "Ticket",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateTicketRequestValidationError{
					field:  "Ticket",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTicket()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateTicketRequestValidationError{
				field:  "Ticket",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateTicketRequestMultiError(errors)
	}

	return nil
}

// CreateTicketRequestMultiError is an error wrapping multiple validation
// errors returned by CreateTicketRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateTicketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTicketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTicketRequestMultiError) AllErrors() []error { return m }

// CreateTicketRequestValidationError is the validation error returned by
// CreateTicketRequest.Validate if the designated constraints aren't met.
type CreateTicketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTicketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTicketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTicketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTicketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTicketRequestValidationError) ErrorName() string {
	return "CreateTicketRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTicketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTicketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTicketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTicketRequestValidationError{}

// Validate checks the field values on CreateTicketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateTicketResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateTicketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateTicketResponseMultiError, or nil if none found.
func (m *CreateTicketResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateTicketResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TicketId

	if len(errors) > 0 {
		return CreateTicketResponseMultiError(errors)
	}

	return nil
}

// CreateTicketResponseMultiError is an error wrapping multiple validation
// errors returned by CreateTicketResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateTicketResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateTicketResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateTicketResponseMultiError) AllErrors() []error { return m }

// CreateTicketResponseValidationError is the validation error returned by
// CreateTicketResponse.Validate if the designated constraints aren't met.
type CreateTicketResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateTicketResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateTicketResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateTicketResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateTicketResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateTicketResponseValidationError) ErrorName() string {
	return "CreateTicketResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateTicketResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateTicketResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateTicketResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateTicketResponseValidationError{}

// Validate checks the field values on ListTicketsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTicketsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTicketsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTicketsRequestMultiError, or nil if none found.
func (m *ListTicketsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTicketsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	if len(errors) > 0 {
		return ListTicketsRequestMultiError(errors)
	}

	return nil
}

// ListTicketsRequestMultiError is an error wrapping multiple validation errors
// returned by ListTicketsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListTicketsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTicketsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTicketsRequestMultiError) AllErrors() []error { return m }

// ListTicketsRequestValidationError is the validation error returned by
// ListTicketsRequest.Validate if the designated constraints aren't met.
type ListTicketsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTicketsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTicketsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTicketsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTicketsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTicketsRequestValidationError) ErrorName() string {
	return "ListTicketsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListTicketsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTicketsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTicketsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTicketsRequestValidationError{}

// Validate checks the field values on ListTicketsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListTicketsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListTicketsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListTicketsResponseMultiError, or nil if none found.
func (m *ListTicketsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListTicketsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTickets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListTicketsResponseValidationError{
						field:  fmt.Sprintf("Tickets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListTicketsResponseValidationError{
						field:  fmt.Sprintf("Tickets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListTicketsResponseValidationError{
					field:  fmt.Sprintf("Tickets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListTicketsResponseMultiError(errors)
	}

	return nil
}

// ListTicketsResponseMultiError is an error wrapping multiple validation
// errors returned by ListTicketsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListTicketsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListTicketsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListTicketsResponseMultiError) AllErrors() []error { return m }

// ListTicketsResponseValidationError is the validation error returned by
// ListTicketsResponse.Validate if the designated constraints aren't met.
type ListTicketsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListTicketsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListTicketsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListTicketsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListTicketsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListTicketsResponseValidationError) ErrorName() string {
	return "ListTicketsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListTicketsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListTicketsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListTicketsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListTicketsResponseValidationError{}

// Validate checks the field values on PurchaseTicketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PurchaseTicketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseTicketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseTicketRequestMultiError, or nil if none found.
func (m *PurchaseTicketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseTicketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TicketId

	// no validation rules for AttendeeEmail

	// no validation rules for AttendeeName

	// no validation rules for Quantity

	if len(errors) > 0 {
		return PurchaseTicketRequestMultiError(errors)
	}

	return nil
}

// PurchaseTicketRequestMultiError is an error wrapping multiple validation
// errors returned by PurchaseTicketRequest.ValidateAll() if the designated
// constraints aren't met.
type PurchaseTicketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseTicketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseTicketRequestMultiError) AllErrors() []error { return m }

// PurchaseTicketRequestValidationError is the validation error returned by
// PurchaseTicketRequest.Validate if the designated constraints aren't met.
type PurchaseTicketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseTicketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseTicketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseTicketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseTicketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseTicketRequestValidationError) ErrorName() string {
	return "PurchaseTicketRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PurchaseTicketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseTicketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseTicketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseTicketRequestValidationError{}

// Validate checks the field values on PurchaseTicketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PurchaseTicketResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PurchaseTicketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PurchaseTicketResponseMultiError, or nil if none found.
func (m *PurchaseTicketResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PurchaseTicketResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderId

	// no validation rules for StripeCheckoutUrl

	if len(errors) > 0 {
		return PurchaseTicketResponseMultiError(errors)
	}

	return nil
}

// PurchaseTicketResponseMultiError is an error wrapping multiple validation
// errors returned by PurchaseTicketResponse.ValidateAll() if the designated
// constraints aren't met.
type PurchaseTicketResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PurchaseTicketResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PurchaseTicketResponseMultiError) AllErrors() []error { return m }

// PurchaseTicketResponseValidationError is the validation error returned by
// PurchaseTicketResponse.Validate if the designated constraints aren't met.
type PurchaseTicketResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseTicketResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseTicketResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseTicketResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseTicketResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseTicketResponseValidationError) ErrorName() string {
	return "PurchaseTicketResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PurchaseTicketResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseTicketResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseTicketResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseTicketResponseValidationError{}

// Validate checks the field values on RefundOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RefundOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefundOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RefundOrderRequestMultiError, or nil if none found.
func (m *RefundOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RefundOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderId

	// no validation rules for OrganizerToken

	// no validation rules for Amount

	// no validation rules for Reason

	if len(errors) > 0 {
		return RefundOrderRequestMultiError(errors)
	}

	return nil
}

// RefundOrderRequestMultiError is an error wrapping multiple validation errors
// returned by RefundOrderRequest.ValidateAll() if the designated constraints
// aren't met.
type RefundOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefundOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefundOrderRequestMultiError) AllErrors() []error { return m }

// RefundOrderRequestValidationError is the validation error returned by
// RefundOrderRequest.Validate if the designated constraints aren't met.
type RefundOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefundOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefundOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefundOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefundOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefundOrderRequestValidationError) ErrorName() string {
	return "RefundOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RefundOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefundOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefundOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefundOrderRequestValidationError{}

// Validate checks the field values on RefundOrderResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RefundOrderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefundOrderResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RefundOrderResponseMultiError, or nil if none found.
func (m *RefundOrderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RefundOrderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOrder()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RefundOrderResponseValidationError{
					field:  "Order",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RefundOrderResponseValidationError{
					field:  "Order",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOrder()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RefundOrderResponseValidationError{
				field:  "Order",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RefundOrderResponseMultiError(errors)
	}

	return nil
}

// RefundOrderResponseMultiError is an error wrapping multiple validation
// errors returned by RefundOrderResponse.ValidateAll() if the designated
// constraints aren't met.
type RefundOrderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefundOrderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefundOrderResponseMultiError) AllErrors() []error { return m }

// RefundOrderResponseValidationError is the validation error returned by
// RefundOrderResponse.Validate if the designated constraints aren't met.
type RefundOrderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefundOrderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefundOrderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefundOrderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefundOrderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefundOrderResponseValidationError) ErrorName() string {
	return "RefundOrderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RefundOrderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefundOrderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefundOrderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefundOrderResponseValidationError{}

// Validate checks the field values on ListOrdersRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListOrdersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrdersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOrdersRequestMultiError, or nil if none found.
func (m *ListOrdersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrdersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for OrganizerToken

	// no validation rules for Cursor

	// no validation rules for PageSize

	if len(errors) > 0 {
		return ListOrdersRequestMultiError(errors)
	}

	return nil
}

// ListOrdersRequestMultiError is an error wrapping multiple validation errors
// returned by ListOrdersRequest.ValidateAll() if the designated constraints
// aren't met.
type ListOrdersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrdersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrdersRequestMultiError) AllErrors() []error { return m }

// ListOrdersRequestValidationError is the validation error returned by
// ListOrdersRequest.Validate if the designated constraints aren't met.
type ListOrdersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrdersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrdersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrdersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrdersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrdersRequestValidationError) ErrorName() string {
	return "ListOrdersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrdersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrdersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrdersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrdersRequestValidationError{}

// Validate checks the field values on ListOrdersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListOrdersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListOrdersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListOrdersResponseMultiError, or nil if none found.
func (m *ListOrdersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListOrdersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetOrders() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListOrdersResponseValidationError{
						field:  fmt.Sprintf("Orders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListOrdersResponseValidationError{
						field:  fmt.Sprintf("Orders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListOrdersResponseValidationError{
					field:  fmt.Sprintf("Orders[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextCursor

	if len(errors) > 0 {
		return ListOrdersResponseMultiError(errors)
	}

	return nil
}

// ListOrdersResponseMultiError is an error wrapping multiple validation errors
// returned by ListOrdersResponse.ValidateAll() if the designated constraints
// aren't met.
type ListOrdersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListOrdersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListOrdersResponseMultiError) AllErrors() []error { return m }

// ListOrdersResponseValidationError is the validation error returned by
// ListOrdersResponse.Validate if the designated constraints aren't met.
type ListOrdersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListOrdersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListOrdersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListOrdersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListOrdersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListOrdersResponseValidationError) ErrorName() string {
	return "ListOrdersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListOrdersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListOrdersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListOrdersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListOrdersResponseValidationError{}

// Validate checks the field values on CheckInAttendeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckInAttendeeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckInAttendeeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckInAttendeeRequestMultiError, or nil if none found.
func (m *CheckInAttendeeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckInAttendeeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventId

	// no validation rules for AttendeeEmail

	// no validation rules for OrganizerToken

	if len(errors) > 0 {
		return CheckInAttendeeRequestMultiError(errors)
	}

	return nil
}

// CheckInAttendeeRequestMultiError is an error wrapping multiple validation
// errors returned by CheckInAttendeeRequest.ValidateAll() if the designated
// constraints aren't met.
type CheckInAttendeeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckInAttendeeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckInAttendeeRequestMultiError) AllErrors() []error { return m }

// CheckInAttendeeRequestValidationError is the validation error returned by
// CheckInAttendeeRequest.Validate if the designated constraints aren't met.
type CheckInAttendeeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckInAttendeeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckInAttendeeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckInAttendeeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckInAttendeeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckInAttendeeRequestValidationError) ErrorName() string {
	return "CheckInAttendeeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CheckInAttendeeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckInAttendeeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckInAttendeeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckInAttendeeRequestValidationError{}

// Validate checks the field values on CheckInAttendeeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CheckInAttendeeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CheckInAttendeeResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CheckInAttendeeResponseMultiError, or nil if none found.
func (m *CheckInAttendeeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CheckInAttendeeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CheckedIn

	if len(errors) > 0 {
		return CheckInAttendeeResponseMultiError(errors)
	}

	return nil
}

// CheckInAttendeeResponseMultiError is an error wrapping multiple validation
// errors returned by CheckInAttendeeResponse.ValidateAll() if the designated
// constraints aren't met.
type CheckInAttendeeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CheckInAttendeeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CheckInAttendeeResponseMultiError) AllErrors() []error { return m }

// CheckInAttendeeResponseValidationError is the validation error returned by
// CheckInAttendeeResponse.Validate if the designated constraints aren't met.
type CheckInAttendeeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CheckInAttendeeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CheckInAttendeeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CheckInAttendeeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CheckInAttendeeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CheckInAttendeeResponseValidationError) ErrorName() string {
	return "CheckInAttendeeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CheckInAttendeeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCheckInAttendeeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CheckInAttendeeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CheckInAttendeeResponseValidationError{}
