// SPDX-License-Identifier: AGPL-3.0
//
// federated-meetup product state schema — the closed-source product layer.
// This is NOT part of the open protocol standard. The protocol (state.proto)
// handles federation, steward signatures, and transitions. This file handles
// the product: tickets, orders, packages, hosting tiers, RSVPs, recurrence.
//
// The Speckl spec (specs/FederatedMeetupProduct.speckdl) is a drift-check
// against this file. If the .speckdl drifts from this .proto, the drift-check
// script catches it before buf generate silently regenerates from the wrong
// schema.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: federated_meetup/product/v1/state.proto

package federatedmeetupproductv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Package int32

const (
	Package_PACKAGE_UNSPECIFIED       Package = 0
	Package_PACKAGE_FREE_COMMUNITY    Package = 1
	Package_PACKAGE_RECURRING_CLUB    Package = 2
	Package_PACKAGE_TICKETED_WORKSHOP Package = 3
	Package_PACKAGE_CONFERENCE        Package = 4
)

// Enum value maps for Package.
var (
	Package_name = map[int32]string{
		0: "PACKAGE_UNSPECIFIED",
		1: "PACKAGE_FREE_COMMUNITY",
		2: "PACKAGE_RECURRING_CLUB",
		3: "PACKAGE_TICKETED_WORKSHOP",
		4: "PACKAGE_CONFERENCE",
	}
	Package_value = map[string]int32{
		"PACKAGE_UNSPECIFIED":       0,
		"PACKAGE_FREE_COMMUNITY":    1,
		"PACKAGE_RECURRING_CLUB":    2,
		"PACKAGE_TICKETED_WORKSHOP": 3,
		"PACKAGE_CONFERENCE":        4,
	}
)

func (x Package) Enum() *Package {
	p := new(Package)
	*p = x
	return p
}

func (x Package) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Package) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[0].Descriptor()
}

func (Package) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[0]
}

func (x Package) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Package.Descriptor instead.
func (Package) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{0}
}

type HostingMode int32

const (
	HostingMode_HOSTING_MODE_UNSPECIFIED HostingMode = 0
	HostingMode_HOSTING_MODE_SELF_HOST   HostingMode = 1
	HostingMode_HOSTING_MODE_PAID_HOST   HostingMode = 2
)

// Enum value maps for HostingMode.
var (
	HostingMode_name = map[int32]string{
		0: "HOSTING_MODE_UNSPECIFIED",
		1: "HOSTING_MODE_SELF_HOST",
		2: "HOSTING_MODE_PAID_HOST",
	}
	HostingMode_value = map[string]int32{
		"HOSTING_MODE_UNSPECIFIED": 0,
		"HOSTING_MODE_SELF_HOST":   1,
		"HOSTING_MODE_PAID_HOST":   2,
	}
)

func (x HostingMode) Enum() *HostingMode {
	p := new(HostingMode)
	*p = x
	return p
}

func (x HostingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[1].Descriptor()
}

func (HostingMode) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[1]
}

func (x HostingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostingMode.Descriptor instead.
func (HostingMode) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{1}
}

type HostingTier int32

const (
	HostingTier_HOSTING_TIER_UNSPECIFIED HostingTier = 0
	HostingTier_HOSTING_TIER_FREE        HostingTier = 1
	HostingTier_HOSTING_TIER_COMMUNITY   HostingTier = 2
	HostingTier_HOSTING_TIER_PRO         HostingTier = 3
	HostingTier_HOSTING_TIER_STUDIO      HostingTier = 4
)

// Enum value maps for HostingTier.
var (
	HostingTier_name = map[int32]string{
		0: "HOSTING_TIER_UNSPECIFIED",
		1: "HOSTING_TIER_FREE",
		2: "HOSTING_TIER_COMMUNITY",
		3: "HOSTING_TIER_PRO",
		4: "HOSTING_TIER_STUDIO",
	}
	HostingTier_value = map[string]int32{
		"HOSTING_TIER_UNSPECIFIED": 0,
		"HOSTING_TIER_FREE":        1,
		"HOSTING_TIER_COMMUNITY":   2,
		"HOSTING_TIER_PRO":         3,
		"HOSTING_TIER_STUDIO":      4,
	}
)

func (x HostingTier) Enum() *HostingTier {
	p := new(HostingTier)
	*p = x
	return p
}

func (x HostingTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostingTier) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[2].Descriptor()
}

func (HostingTier) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[2]
}

func (x HostingTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostingTier.Descriptor instead.
func (HostingTier) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{2}
}

type EventVisibility int32

const (
	EventVisibility_EVENT_VISIBILITY_UNSPECIFIED EventVisibility = 0
	EventVisibility_EVENT_VISIBILITY_PUBLIC      EventVisibility = 1
	EventVisibility_EVENT_VISIBILITY_UNLISTED    EventVisibility = 2
	EventVisibility_EVENT_VISIBILITY_PRIVATE     EventVisibility = 3
	EventVisibility_EVENT_VISIBILITY_INVITE_ONLY EventVisibility = 4
)

// Enum value maps for EventVisibility.
var (
	EventVisibility_name = map[int32]string{
		0: "EVENT_VISIBILITY_UNSPECIFIED",
		1: "EVENT_VISIBILITY_PUBLIC",
		2: "EVENT_VISIBILITY_UNLISTED",
		3: "EVENT_VISIBILITY_PRIVATE",
		4: "EVENT_VISIBILITY_INVITE_ONLY",
	}
	EventVisibility_value = map[string]int32{
		"EVENT_VISIBILITY_UNSPECIFIED": 0,
		"EVENT_VISIBILITY_PUBLIC":      1,
		"EVENT_VISIBILITY_UNLISTED":    2,
		"EVENT_VISIBILITY_PRIVATE":     3,
		"EVENT_VISIBILITY_INVITE_ONLY": 4,
	}
)

func (x EventVisibility) Enum() *EventVisibility {
	p := new(EventVisibility)
	*p = x
	return p
}

func (x EventVisibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventVisibility) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[3].Descriptor()
}

func (EventVisibility) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[3]
}

func (x EventVisibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventVisibility.Descriptor instead.
func (EventVisibility) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{3}
}

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_OWNER       Role = 1
	Role_ROLE_ORGANIZER   Role = 2
	Role_ROLE_MODERATOR   Role = 3
	Role_ROLE_TREASURER   Role = 4
	Role_ROLE_MEMBER      Role = 5
	Role_ROLE_PENDING     Role = 6
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_OWNER",
		2: "ROLE_ORGANIZER",
		3: "ROLE_MODERATOR",
		4: "ROLE_TREASURER",
		5: "ROLE_MEMBER",
		6: "ROLE_PENDING",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_OWNER":       1,
		"ROLE_ORGANIZER":   2,
		"ROLE_MODERATOR":   3,
		"ROLE_TREASURER":   4,
		"ROLE_MEMBER":      5,
		"ROLE_PENDING":     6,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[4].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[4]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{4}
}

type TicketTierType int32

const (
	TicketTierType_TICKET_TIER_TYPE_UNSPECIFIED TicketTierType = 0
	TicketTierType_TICKET_TIER_TYPE_EARLY_BIRD  TicketTierType = 1
	TicketTierType_TICKET_TIER_TYPE_REGULAR     TicketTierType = 2
	TicketTierType_TICKET_TIER_TYPE_SUPPORTER   TicketTierType = 3
	TicketTierType_TICKET_TIER_TYPE_CUSTOM      TicketTierType = 4
)

// Enum value maps for TicketTierType.
var (
	TicketTierType_name = map[int32]string{
		0: "TICKET_TIER_TYPE_UNSPECIFIED",
		1: "TICKET_TIER_TYPE_EARLY_BIRD",
		2: "TICKET_TIER_TYPE_REGULAR",
		3: "TICKET_TIER_TYPE_SUPPORTER",
		4: "TICKET_TIER_TYPE_CUSTOM",
	}
	TicketTierType_value = map[string]int32{
		"TICKET_TIER_TYPE_UNSPECIFIED": 0,
		"TICKET_TIER_TYPE_EARLY_BIRD":  1,
		"TICKET_TIER_TYPE_REGULAR":     2,
		"TICKET_TIER_TYPE_SUPPORTER":   3,
		"TICKET_TIER_TYPE_CUSTOM":      4,
	}
)

func (x TicketTierType) Enum() *TicketTierType {
	p := new(TicketTierType)
	*p = x
	return p
}

func (x TicketTierType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketTierType) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[5].Descriptor()
}

func (TicketTierType) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[5]
}

func (x TicketTierType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketTierType.Descriptor instead.
func (TicketTierType) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{5}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED        OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING            OrderStatus = 1
	OrderStatus_ORDER_STATUS_COMPLETED          OrderStatus = 2
	OrderStatus_ORDER_STATUS_REFUNDED           OrderStatus = 3
	OrderStatus_ORDER_STATUS_PARTIALLY_REFUNDED OrderStatus = 4
	OrderStatus_ORDER_STATUS_DISPUTED           OrderStatus = 5
	OrderStatus_ORDER_STATUS_FAILED             OrderStatus = 6
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_COMPLETED",
		3: "ORDER_STATUS_REFUNDED",
		4: "ORDER_STATUS_PARTIALLY_REFUNDED",
		5: "ORDER_STATUS_DISPUTED",
		6: "ORDER_STATUS_FAILED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":        0,
		"ORDER_STATUS_PENDING":            1,
		"ORDER_STATUS_COMPLETED":          2,
		"ORDER_STATUS_REFUNDED":           3,
		"ORDER_STATUS_PARTIALLY_REFUNDED": 4,
		"ORDER_STATUS_DISPUTED":           5,
		"ORDER_STATUS_FAILED":             6,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[6].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[6]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{6}
}

type RsvpStatus int32

const (
	RsvpStatus_RSVP_STATUS_UNSPECIFIED RsvpStatus = 0
	RsvpStatus_RSVP_STATUS_GOING       RsvpStatus = 1
	RsvpStatus_RSVP_STATUS_WAITLIST    RsvpStatus = 2
	RsvpStatus_RSVP_STATUS_MAYBE       RsvpStatus = 3
	RsvpStatus_RSVP_STATUS_NOT_GOING   RsvpStatus = 4
)

// Enum value maps for RsvpStatus.
var (
	RsvpStatus_name = map[int32]string{
		0: "RSVP_STATUS_UNSPECIFIED",
		1: "RSVP_STATUS_GOING",
		2: "RSVP_STATUS_WAITLIST",
		3: "RSVP_STATUS_MAYBE",
		4: "RSVP_STATUS_NOT_GOING",
	}
	RsvpStatus_value = map[string]int32{
		"RSVP_STATUS_UNSPECIFIED": 0,
		"RSVP_STATUS_GOING":       1,
		"RSVP_STATUS_WAITLIST":    2,
		"RSVP_STATUS_MAYBE":       3,
		"RSVP_STATUS_NOT_GOING":   4,
	}
)

func (x RsvpStatus) Enum() *RsvpStatus {
	p := new(RsvpStatus)
	*p = x
	return p
}

func (x RsvpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RsvpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[7].Descriptor()
}

func (RsvpStatus) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[7]
}

func (x RsvpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RsvpStatus.Descriptor instead.
func (RsvpStatus) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{7}
}

type ProductTransitionType int32

const (
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_UNSPECIFIED       ProductTransitionType = 0
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_CREATE_TICKET     ProductTransitionType = 1
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_UPDATE_TICKET     ProductTransitionType = 2
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_PURCHASE_TICKET   ProductTransitionType = 3
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_REFUND_ORDER      ProductTransitionType = 4
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_CREATE_RECURRENCE ProductTransitionType = 5
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_ADD_EXCEPTION     ProductTransitionType = 6
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_SET_GROUP_PACKAGE ProductTransitionType = 7
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_SET_HOSTING_TIER  ProductTransitionType = 8
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_UPDATE_VISIBILITY ProductTransitionType = 9
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_SET_MEMBER_ROLE   ProductTransitionType = 10
	ProductTransitionType_PRODUCT_TRANSITION_TYPE_MARK_ATTENDED     ProductTransitionType = 11
)

// Enum value maps for ProductTransitionType.
var (
	ProductTransitionType_name = map[int32]string{
		0:  "PRODUCT_TRANSITION_TYPE_UNSPECIFIED",
		1:  "PRODUCT_TRANSITION_TYPE_CREATE_TICKET",
		2:  "PRODUCT_TRANSITION_TYPE_UPDATE_TICKET",
		3:  "PRODUCT_TRANSITION_TYPE_PURCHASE_TICKET",
		4:  "PRODUCT_TRANSITION_TYPE_REFUND_ORDER",
		5:  "PRODUCT_TRANSITION_TYPE_CREATE_RECURRENCE",
		6:  "PRODUCT_TRANSITION_TYPE_ADD_EXCEPTION",
		7:  "PRODUCT_TRANSITION_TYPE_SET_GROUP_PACKAGE",
		8:  "PRODUCT_TRANSITION_TYPE_SET_HOSTING_TIER",
		9:  "PRODUCT_TRANSITION_TYPE_UPDATE_VISIBILITY",
		10: "PRODUCT_TRANSITION_TYPE_SET_MEMBER_ROLE",
		11: "PRODUCT_TRANSITION_TYPE_MARK_ATTENDED",
	}
	ProductTransitionType_value = map[string]int32{
		"PRODUCT_TRANSITION_TYPE_UNSPECIFIED":       0,
		"PRODUCT_TRANSITION_TYPE_CREATE_TICKET":     1,
		"PRODUCT_TRANSITION_TYPE_UPDATE_TICKET":     2,
		"PRODUCT_TRANSITION_TYPE_PURCHASE_TICKET":   3,
		"PRODUCT_TRANSITION_TYPE_REFUND_ORDER":      4,
		"PRODUCT_TRANSITION_TYPE_CREATE_RECURRENCE": 5,
		"PRODUCT_TRANSITION_TYPE_ADD_EXCEPTION":     6,
		"PRODUCT_TRANSITION_TYPE_SET_GROUP_PACKAGE": 7,
		"PRODUCT_TRANSITION_TYPE_SET_HOSTING_TIER":  8,
		"PRODUCT_TRANSITION_TYPE_UPDATE_VISIBILITY": 9,
		"PRODUCT_TRANSITION_TYPE_SET_MEMBER_ROLE":   10,
		"PRODUCT_TRANSITION_TYPE_MARK_ATTENDED":     11,
	}
)

func (x ProductTransitionType) Enum() *ProductTransitionType {
	p := new(ProductTransitionType)
	*p = x
	return p
}

func (x ProductTransitionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductTransitionType) Descriptor() protoreflect.EnumDescriptor {
	return file_federated_meetup_product_v1_state_proto_enumTypes[8].Descriptor()
}

func (ProductTransitionType) Type() protoreflect.EnumType {
	return &file_federated_meetup_product_v1_state_proto_enumTypes[8]
}

func (x ProductTransitionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductTransitionType.Descriptor instead.
func (ProductTransitionType) EnumDescriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{8}
}

// Money: integer cents + ISO 4217 currency code. Avoids floating point.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Ticket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,7,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TierType      TicketTierType         `protobuf:"varint,8,opt,name=tier_type,json=tierType,proto3,enum=federated_meetup.product.v1.TicketTierType" json:"tier_type,omitempty"`
	Price         *Money                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Capacity      uint64                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Sold          uint64                 `protobuf:"varint,6,opt,name=sold,proto3" json:"sold,omitempty"`
	SaleStartsAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sale_starts_at,json=saleStartsAt,proto3" json:"sale_starts_at,omitempty"`
	SaleEndsAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=sale_ends_at,json=saleEndsAt,proto3" json:"sale_ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *Ticket) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Ticket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ticket) GetTierType() TicketTierType {
	if x != nil {
		return x.TierType
	}
	return TicketTierType_TICKET_TIER_TYPE_UNSPECIFIED
}

func (x *Ticket) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Ticket) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Ticket) GetSold() uint64 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *Ticket) GetSaleStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleStartsAt
	}
	return nil
}

func (x *Ticket) GetSaleEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleEndsAt
	}
	return nil
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TicketId        string                 `protobuf:"bytes,8,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	AttendeeEmail   string                 `protobuf:"bytes,2,opt,name=attendee_email,json=attendeeEmail,proto3" json:"attendee_email,omitempty"`
	Status          OrderStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=federated_meetup.product.v1.OrderStatus" json:"status,omitempty"`
	StripeSessionId string                 `protobuf:"bytes,7,opt,name=stripe_session_id,json=stripeSessionId,proto3" json:"stripe_session_id,omitempty"`
	AmountPaid      *Money                 `protobuf:"bytes,1,opt,name=amount_paid,json=amountPaid,proto3" json:"amount_paid,omitempty"`
	RefundedAmount  *Money                 `protobuf:"bytes,9,opt,name=refunded_amount,json=refundedAmount,proto3" json:"refunded_amount,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RefundedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *Order) GetAttendeeEmail() string {
	if x != nil {
		return x.AttendeeEmail
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetStripeSessionId() string {
	if x != nil {
		return x.StripeSessionId
	}
	return ""
}

func (x *Order) GetAmountPaid() *Money {
	if x != nil {
		return x.AmountPaid
	}
	return nil
}

func (x *Order) GetRefundedAmount() *Money {
	if x != nil {
		return x.RefundedAmount
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetRefundedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefundedAt
	}
	return nil
}

type RecurrenceRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rrule         string                 `protobuf:"bytes,2,opt,name=rrule,proto3" json:"rrule,omitempty"`
	Exceptions    []string               `protobuf:"bytes,1,rep,name=exceptions,proto3" json:"exceptions,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecurrenceRule) Reset() {
	*x = RecurrenceRule{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecurrenceRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecurrenceRule) ProtoMessage() {}

func (x *RecurrenceRule) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecurrenceRule.ProtoReflect.Descriptor instead.
func (*RecurrenceRule) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *RecurrenceRule) GetRrule() string {
	if x != nil {
		return x.Rrule
	}
	return ""
}

func (x *RecurrenceRule) GetExceptions() []string {
	if x != nil {
		return x.Exceptions
	}
	return nil
}

func (x *RecurrenceRule) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type Vendor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VendorId           string                 `protobuf:"bytes,5,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category           string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Website            string                 `protobuf:"bytes,7,opt,name=website,proto3" json:"website,omitempty"`
	Rating             uint64                 `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Verified           bool                   `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	ReferralFeePercent uint64                 `protobuf:"varint,4,opt,name=referral_fee_percent,json=referralFeePercent,proto3" json:"referral_fee_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *Vendor) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *Vendor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vendor) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Vendor) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Vendor) GetRating() uint64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Vendor) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Vendor) GetReferralFeePercent() uint64 {
	if x != nil {
		return x.ReferralFeePercent
	}
	return 0
}

type Sponsorship struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SponsorId      string                 `protobuf:"bytes,4,opt,name=sponsor_id,json=sponsorId,proto3" json:"sponsor_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tier           string                 `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	LogoUrl        string                 `protobuf:"bytes,2,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Website        string                 `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	AttendeeAccess bool                   `protobuf:"varint,1,opt,name=attendee_access,json=attendeeAccess,proto3" json:"attendee_access,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Sponsorship) Reset() {
	*x = Sponsorship{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sponsorship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sponsorship) ProtoMessage() {}

func (x *Sponsorship) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sponsorship.ProtoReflect.Descriptor instead.
func (*Sponsorship) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *Sponsorship) GetSponsorId() string {
	if x != nil {
		return x.SponsorId
	}
	return ""
}

func (x *Sponsorship) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sponsorship) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Sponsorship) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Sponsorship) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Sponsorship) GetAttendeeAccess() bool {
	if x != nil {
		return x.AttendeeAccess
	}
	return false
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Title         string                 `protobuf:"bytes,13,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	VenueId       string                 `protobuf:"bytes,14,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Visibility    EventVisibility        `protobuf:"varint,15,opt,name=visibility,proto3,enum=federated_meetup.product.v1.EventVisibility" json:"visibility,omitempty"`
	Capacity      uint64                 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Package       Package                `protobuf:"varint,8,opt,name=package,proto3,enum=federated_meetup.product.v1.Package" json:"package,omitempty"`
	Paid          bool                   `protobuf:"varint,9,opt,name=paid,proto3" json:"paid,omitempty"`
	Slug          string                 `protobuf:"bytes,11,opt,name=slug,proto3" json:"slug,omitempty"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	Recurrence    *RecurrenceRule        `protobuf:"bytes,10,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Event) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Event) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Event) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *Event) GetVisibility() EventVisibility {
	if x != nil {
		return x.Visibility
	}
	return EventVisibility_EVENT_VISIBILITY_UNSPECIFIED
}

func (x *Event) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Event) GetPackage() Package {
	if x != nil {
		return x.Package
	}
	return Package_PACKAGE_UNSPECIFIED
}

func (x *Event) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *Event) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Event) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *Event) GetRecurrence() *RecurrenceRule {
	if x != nil {
		return x.Recurrence
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	CanonicalName string                 `protobuf:"bytes,1,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	HostingMode   HostingMode            `protobuf:"varint,7,opt,name=hosting_mode,json=hostingMode,proto3,enum=federated_meetup.product.v1.HostingMode" json:"hosting_mode,omitempty"`
	HostingTier   HostingTier            `protobuf:"varint,8,opt,name=hosting_tier,json=hostingTier,proto3,enum=federated_meetup.product.v1.HostingTier" json:"hosting_tier,omitempty"`
	Package       Package                `protobuf:"varint,10,opt,name=package,proto3,enum=federated_meetup.product.v1.Package" json:"package,omitempty"`
	CustomDomain  string                 `protobuf:"bytes,3,opt,name=custom_domain,json=customDomain,proto3" json:"custom_domain,omitempty"`
	MemberCount   uint64                 `protobuf:"varint,9,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{7}
}

func (x *Group) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Group) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *Group) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetHostingMode() HostingMode {
	if x != nil {
		return x.HostingMode
	}
	return HostingMode_HOSTING_MODE_UNSPECIFIED
}

func (x *Group) GetHostingTier() HostingTier {
	if x != nil {
		return x.HostingTier
	}
	return HostingTier_HOSTING_TIER_UNSPECIFIED
}

func (x *Group) GetPackage() Package {
	if x != nil {
		return x.Package
	}
	return Package_PACKAGE_UNSPECIFIED
}

func (x *Group) GetCustomDomain() string {
	if x != nil {
		return x.CustomDomain
	}
	return ""
}

func (x *Group) GetMemberCount() uint64 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Group) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,4,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=federated_meetup.product.v1.Role" json:"role,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{8}
}

func (x *GroupMember) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMember) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *GroupMember) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *GroupMember) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

type Rsvp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,5,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Status        RsvpStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=federated_meetup.product.v1.RsvpStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Attended      bool                   `protobuf:"varint,1,opt,name=attended,proto3" json:"attended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rsvp) Reset() {
	*x = Rsvp{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rsvp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rsvp) ProtoMessage() {}

func (x *Rsvp) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rsvp.ProtoReflect.Descriptor instead.
func (*Rsvp) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{9}
}

func (x *Rsvp) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Rsvp) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *Rsvp) GetStatus() RsvpStatus {
	if x != nil {
		return x.Status
	}
	return RsvpStatus_RSVP_STATUS_UNSPECIFIED
}

func (x *Rsvp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Rsvp) GetAttended() bool {
	if x != nil {
		return x.Attended
	}
	return false
}

type CreateTicketPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TicketId      string                 `protobuf:"bytes,8,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TierType      TicketTierType         `protobuf:"varint,9,opt,name=tier_type,json=tierType,proto3,enum=federated_meetup.product.v1.TicketTierType" json:"tier_type,omitempty"`
	PriceAmount   uint64                 `protobuf:"varint,4,opt,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
	PriceCurrency string                 `protobuf:"bytes,5,opt,name=price_currency,json=priceCurrency,proto3" json:"price_currency,omitempty"`
	Capacity      uint64                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SaleStartsAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sale_starts_at,json=saleStartsAt,proto3" json:"sale_starts_at,omitempty"`
	SaleEndsAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=sale_ends_at,json=saleEndsAt,proto3" json:"sale_ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTicketPayload) Reset() {
	*x = CreateTicketPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTicketPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTicketPayload) ProtoMessage() {}

func (x *CreateTicketPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTicketPayload.ProtoReflect.Descriptor instead.
func (*CreateTicketPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTicketPayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateTicketPayload) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *CreateTicketPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTicketPayload) GetTierType() TicketTierType {
	if x != nil {
		return x.TierType
	}
	return TicketTierType_TICKET_TIER_TYPE_UNSPECIFIED
}

func (x *CreateTicketPayload) GetPriceAmount() uint64 {
	if x != nil {
		return x.PriceAmount
	}
	return 0
}

func (x *CreateTicketPayload) GetPriceCurrency() string {
	if x != nil {
		return x.PriceCurrency
	}
	return ""
}

func (x *CreateTicketPayload) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateTicketPayload) GetSaleStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleStartsAt
	}
	return nil
}

func (x *CreateTicketPayload) GetSaleEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SaleEndsAt
	}
	return nil
}

type UpdateTicketPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,5,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceAmount   uint64                 `protobuf:"varint,3,opt,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
	PriceCurrency string                 `protobuf:"bytes,4,opt,name=price_currency,json=priceCurrency,proto3" json:"price_currency,omitempty"`
	Capacity      uint64                 `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTicketPayload) Reset() {
	*x = UpdateTicketPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTicketPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTicketPayload) ProtoMessage() {}

func (x *UpdateTicketPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTicketPayload.ProtoReflect.Descriptor instead.
func (*UpdateTicketPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTicketPayload) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *UpdateTicketPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTicketPayload) GetPriceAmount() uint64 {
	if x != nil {
		return x.PriceAmount
	}
	return 0
}

func (x *UpdateTicketPayload) GetPriceCurrency() string {
	if x != nil {
		return x.PriceCurrency
	}
	return ""
}

func (x *UpdateTicketPayload) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type PurchaseTicketPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TicketId        string                 `protobuf:"bytes,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	AttendeeEmail   string                 `protobuf:"bytes,1,opt,name=attendee_email,json=attendeeEmail,proto3" json:"attendee_email,omitempty"`
	StripeSessionId string                 `protobuf:"bytes,2,opt,name=stripe_session_id,json=stripeSessionId,proto3" json:"stripe_session_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PurchaseTicketPayload) Reset() {
	*x = PurchaseTicketPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseTicketPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseTicketPayload) ProtoMessage() {}

func (x *PurchaseTicketPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseTicketPayload.ProtoReflect.Descriptor instead.
func (*PurchaseTicketPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{12}
}

func (x *PurchaseTicketPayload) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *PurchaseTicketPayload) GetAttendeeEmail() string {
	if x != nil {
		return x.AttendeeEmail
	}
	return ""
}

func (x *PurchaseTicketPayload) GetStripeSessionId() string {
	if x != nil {
		return x.StripeSessionId
	}
	return ""
}

type RefundOrderPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderPayload) Reset() {
	*x = RefundOrderPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderPayload) ProtoMessage() {}

func (x *RefundOrderPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderPayload.ProtoReflect.Descriptor instead.
func (*RefundOrderPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{13}
}

func (x *RefundOrderPayload) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RefundOrderPayload) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundOrderPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateRecurrencePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Rrule         string                 `protobuf:"bytes,2,opt,name=rrule,proto3" json:"rrule,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecurrencePayload) Reset() {
	*x = CreateRecurrencePayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecurrencePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecurrencePayload) ProtoMessage() {}

func (x *CreateRecurrencePayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecurrencePayload.ProtoReflect.Descriptor instead.
func (*CreateRecurrencePayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRecurrencePayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateRecurrencePayload) GetRrule() string {
	if x != nil {
		return x.Rrule
	}
	return ""
}

func (x *CreateRecurrencePayload) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type AddExceptionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ExceptionDate string                 `protobuf:"bytes,2,opt,name=exception_date,json=exceptionDate,proto3" json:"exception_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExceptionPayload) Reset() {
	*x = AddExceptionPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExceptionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExceptionPayload) ProtoMessage() {}

func (x *AddExceptionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExceptionPayload.ProtoReflect.Descriptor instead.
func (*AddExceptionPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{15}
}

func (x *AddExceptionPayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AddExceptionPayload) GetExceptionDate() string {
	if x != nil {
		return x.ExceptionDate
	}
	return ""
}

type SetGroupPackagePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Package       Package                `protobuf:"varint,2,opt,name=package,proto3,enum=federated_meetup.product.v1.Package" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGroupPackagePayload) Reset() {
	*x = SetGroupPackagePayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGroupPackagePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGroupPackagePayload) ProtoMessage() {}

func (x *SetGroupPackagePayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGroupPackagePayload.ProtoReflect.Descriptor instead.
func (*SetGroupPackagePayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{16}
}

func (x *SetGroupPackagePayload) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetGroupPackagePayload) GetPackage() Package {
	if x != nil {
		return x.Package
	}
	return Package_PACKAGE_UNSPECIFIED
}

type SetHostingTierPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Tier          HostingTier            `protobuf:"varint,2,opt,name=tier,proto3,enum=federated_meetup.product.v1.HostingTier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHostingTierPayload) Reset() {
	*x = SetHostingTierPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHostingTierPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHostingTierPayload) ProtoMessage() {}

func (x *SetHostingTierPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHostingTierPayload.ProtoReflect.Descriptor instead.
func (*SetHostingTierPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{17}
}

func (x *SetHostingTierPayload) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetHostingTierPayload) GetTier() HostingTier {
	if x != nil {
		return x.Tier
	}
	return HostingTier_HOSTING_TIER_UNSPECIFIED
}

type UpdateVisibilityPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Visibility    EventVisibility        `protobuf:"varint,2,opt,name=visibility,proto3,enum=federated_meetup.product.v1.EventVisibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVisibilityPayload) Reset() {
	*x = UpdateVisibilityPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVisibilityPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVisibilityPayload) ProtoMessage() {}

func (x *UpdateVisibilityPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVisibilityPayload.ProtoReflect.Descriptor instead.
func (*UpdateVisibilityPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateVisibilityPayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateVisibilityPayload) GetVisibility() EventVisibility {
	if x != nil {
		return x.Visibility
	}
	return EventVisibility_EVENT_VISIBILITY_UNSPECIFIED
}

type SetMemberRolePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=federated_meetup.product.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRolePayload) Reset() {
	*x = SetMemberRolePayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRolePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRolePayload) ProtoMessage() {}

func (x *SetMemberRolePayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRolePayload.ProtoReflect.Descriptor instead.
func (*SetMemberRolePayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{19}
}

func (x *SetMemberRolePayload) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetMemberRolePayload) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SetMemberRolePayload) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

type MarkAttendedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Attended      bool                   `protobuf:"varint,1,opt,name=attended,proto3" json:"attended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAttendedPayload) Reset() {
	*x = MarkAttendedPayload{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAttendedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAttendedPayload) ProtoMessage() {}

func (x *MarkAttendedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAttendedPayload.ProtoReflect.Descriptor instead.
func (*MarkAttendedPayload) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{20}
}

func (x *MarkAttendedPayload) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MarkAttendedPayload) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *MarkAttendedPayload) GetAttended() bool {
	if x != nil {
		return x.Attended
	}
	return false
}

type ProductTransition struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    ProductTransitionType  `protobuf:"varint,1,opt,name=type,proto3,enum=federated_meetup.product.v1.ProductTransitionType" json:"type,omitempty"`
	GroupId string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Hlc     []byte                 `protobuf:"bytes,3,opt,name=hlc,proto3" json:"hlc,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProductTransition_CreateTicket
	//	*ProductTransition_UpdateTicket
	//	*ProductTransition_PurchaseTicket
	//	*ProductTransition_RefundOrder
	//	*ProductTransition_CreateRecurrence
	//	*ProductTransition_AddException
	//	*ProductTransition_SetGroupPackage
	//	*ProductTransition_SetHostingTier
	//	*ProductTransition_UpdateVisibility
	//	*ProductTransition_SetMemberRole
	//	*ProductTransition_MarkAttended
	Payload       isProductTransition_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductTransition) Reset() {
	*x = ProductTransition{}
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductTransition) ProtoMessage() {}

func (x *ProductTransition) ProtoReflect() protoreflect.Message {
	mi := &file_federated_meetup_product_v1_state_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductTransition.ProtoReflect.Descriptor instead.
func (*ProductTransition) Descriptor() ([]byte, []int) {
	return file_federated_meetup_product_v1_state_proto_rawDescGZIP(), []int{21}
}

func (x *ProductTransition) GetType() ProductTransitionType {
	if x != nil {
		return x.Type
	}
	return ProductTransitionType_PRODUCT_TRANSITION_TYPE_UNSPECIFIED
}

func (x *ProductTransition) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ProductTransition) GetHlc() []byte {
	if x != nil {
		return x.Hlc
	}
	return nil
}

func (x *ProductTransition) GetPayload() isProductTransition_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProductTransition) GetCreateTicket() *CreateTicketPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_CreateTicket); ok {
			return x.CreateTicket
		}
	}
	return nil
}

func (x *ProductTransition) GetUpdateTicket() *UpdateTicketPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_UpdateTicket); ok {
			return x.UpdateTicket
		}
	}
	return nil
}

func (x *ProductTransition) GetPurchaseTicket() *PurchaseTicketPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_PurchaseTicket); ok {
			return x.PurchaseTicket
		}
	}
	return nil
}

func (x *ProductTransition) GetRefundOrder() *RefundOrderPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_RefundOrder); ok {
			return x.RefundOrder
		}
	}
	return nil
}

func (x *ProductTransition) GetCreateRecurrence() *CreateRecurrencePayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_CreateRecurrence); ok {
			return x.CreateRecurrence
		}
	}
	return nil
}

func (x *ProductTransition) GetAddException() *AddExceptionPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_AddException); ok {
			return x.AddException
		}
	}
	return nil
}

func (x *ProductTransition) GetSetGroupPackage() *SetGroupPackagePayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_SetGroupPackage); ok {
			return x.SetGroupPackage
		}
	}
	return nil
}

func (x *ProductTransition) GetSetHostingTier() *SetHostingTierPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_SetHostingTier); ok {
			return x.SetHostingTier
		}
	}
	return nil
}

func (x *ProductTransition) GetUpdateVisibility() *UpdateVisibilityPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_UpdateVisibility); ok {
			return x.UpdateVisibility
		}
	}
	return nil
}

func (x *ProductTransition) GetSetMemberRole() *SetMemberRolePayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_SetMemberRole); ok {
			return x.SetMemberRole
		}
	}
	return nil
}

func (x *ProductTransition) GetMarkAttended() *MarkAttendedPayload {
	if x != nil {
		if x, ok := x.Payload.(*ProductTransition_MarkAttended); ok {
			return x.MarkAttended
		}
	}
	return nil
}

type isProductTransition_Payload interface {
	isProductTransition_Payload()
}

type ProductTransition_CreateTicket struct {
	CreateTicket *CreateTicketPayload `protobuf:"bytes,10,opt,name=create_ticket,json=createTicket,proto3,oneof"`
}

type ProductTransition_UpdateTicket struct {
	UpdateTicket *UpdateTicketPayload `protobuf:"bytes,11,opt,name=update_ticket,json=updateTicket,proto3,oneof"`
}

type ProductTransition_PurchaseTicket struct {
	PurchaseTicket *PurchaseTicketPayload `protobuf:"bytes,12,opt,name=purchase_ticket,json=purchaseTicket,proto3,oneof"`
}

type ProductTransition_RefundOrder struct {
	RefundOrder *RefundOrderPayload `protobuf:"bytes,13,opt,name=refund_order,json=refundOrder,proto3,oneof"`
}

type ProductTransition_CreateRecurrence struct {
	CreateRecurrence *CreateRecurrencePayload `protobuf:"bytes,14,opt,name=create_recurrence,json=createRecurrence,proto3,oneof"`
}

type ProductTransition_AddException struct {
	AddException *AddExceptionPayload `protobuf:"bytes,15,opt,name=add_exception,json=addException,proto3,oneof"`
}

type ProductTransition_SetGroupPackage struct {
	SetGroupPackage *SetGroupPackagePayload `protobuf:"bytes,16,opt,name=set_group_package,json=setGroupPackage,proto3,oneof"`
}

type ProductTransition_SetHostingTier struct {
	SetHostingTier *SetHostingTierPayload `protobuf:"bytes,17,opt,name=set_hosting_tier,json=setHostingTier,proto3,oneof"`
}

type ProductTransition_UpdateVisibility struct {
	UpdateVisibility *UpdateVisibilityPayload `protobuf:"bytes,18,opt,name=update_visibility,json=updateVisibility,proto3,oneof"`
}

type ProductTransition_SetMemberRole struct {
	SetMemberRole *SetMemberRolePayload `protobuf:"bytes,19,opt,name=set_member_role,json=setMemberRole,proto3,oneof"`
}

type ProductTransition_MarkAttended struct {
	MarkAttended *MarkAttendedPayload `protobuf:"bytes,20,opt,name=mark_attended,json=markAttended,proto3,oneof"`
}

func (*ProductTransition_CreateTicket) isProductTransition_Payload() {}

func (*ProductTransition_UpdateTicket) isProductTransition_Payload() {}

func (*ProductTransition_PurchaseTicket) isProductTransition_Payload() {}

func (*ProductTransition_RefundOrder) isProductTransition_Payload() {}

func (*ProductTransition_CreateRecurrence) isProductTransition_Payload() {}

func (*ProductTransition_AddException) isProductTransition_Payload() {}

func (*ProductTransition_SetGroupPackage) isProductTransition_Payload() {}

func (*ProductTransition_SetHostingTier) isProductTransition_Payload() {}

func (*ProductTransition_UpdateVisibility) isProductTransition_Payload() {}

func (*ProductTransition_SetMemberRole) isProductTransition_Payload() {}

func (*ProductTransition_MarkAttended) isProductTransition_Payload() {}

var File_federated_meetup_product_v1_state_proto protoreflect.FileDescriptor

const file_federated_meetup_product_v1_state_proto_rawDesc = "" +
	"\n" +
	"'federated_meetup/product/v1/state.proto\x12\x1bfederated_meetup.product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xed\x02\n" +
	"\x06Ticket\x12\x1b\n" +
	"\tticket_id\x18\a \x01(\tR\bticketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12H\n" +
	"\ttier_type\x18\b \x01(\x0e2+.federated_meetup.product.v1.TicketTierTypeR\btierType\x128\n" +
	"\x05price\x18\x03 \x01(\v2\".federated_meetup.product.v1.MoneyR\x05price\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x04R\bcapacity\x12\x12\n" +
	"\x04sold\x18\x06 \x01(\x04R\x04sold\x12@\n" +
	"\x0esale_starts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fsaleStartsAt\x12<\n" +
	"\fsale_ends_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"saleEndsAt\"\xde\x03\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x04 \x01(\tR\aorderId\x12\x1b\n" +
	"\tticket_id\x18\b \x01(\tR\bticketId\x12%\n" +
	"\x0eattendee_email\x18\x02 \x01(\tR\rattendeeEmail\x12@\n" +
	"\x06status\x18\x06 \x01(\x0e2(.federated_meetup.product.v1.OrderStatusR\x06status\x12*\n" +
	"\x11stripe_session_id\x18\a \x01(\tR\x0fstripeSessionId\x12C\n" +
	"\vamount_paid\x18\x01 \x01(\v2\".federated_meetup.product.v1.MoneyR\n" +
	"amountPaid\x12K\n" +
	"\x0frefunded_amount\x18\t \x01(\v2\".federated_meetup.product.v1.MoneyR\x0erefundedAmount\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vrefunded_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"refundedAt\"b\n" +
	"\x0eRecurrenceRule\x12\x14\n" +
	"\x05rrule\x18\x02 \x01(\tR\x05rrule\x12\x1e\n" +
	"\n" +
	"exceptions\x18\x01 \x03(\tR\n" +
	"exceptions\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"\xd5\x01\n" +
	"\x06Vendor\x12\x1b\n" +
	"\tvendor_id\x18\x05 \x01(\tR\bvendorId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x18\n" +
	"\awebsite\x18\a \x01(\tR\awebsite\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x04R\x06rating\x12\x1a\n" +
	"\bverified\x18\x06 \x01(\bR\bverified\x120\n" +
	"\x14referral_fee_percent\x18\x04 \x01(\x04R\x12referralFeePercent\"\xb2\x01\n" +
	"\vSponsorship\x12\x1d\n" +
	"\n" +
	"sponsor_id\x18\x04 \x01(\tR\tsponsorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x12\x19\n" +
	"\blogo_url\x18\x02 \x01(\tR\alogoUrl\x12\x18\n" +
	"\awebsite\x18\x06 \x01(\tR\awebsite\x12'\n" +
	"\x0fattendee_access\x18\x01 \x01(\bR\x0eattendeeAccess\"\xd7\x04\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12\x14\n" +
	"\x05title\x18\r \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\tstarts_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x19\n" +
	"\bvenue_id\x18\x0e \x01(\tR\avenueId\x12L\n" +
	"\n" +
	"visibility\x18\x0f \x01(\x0e2,.federated_meetup.product.v1.EventVisibilityR\n" +
	"visibility\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x04R\bcapacity\x12>\n" +
	"\apackage\x18\b \x01(\x0e2$.federated_meetup.product.v1.PackageR\apackage\x12\x12\n" +
	"\x04paid\x18\t \x01(\bR\x04paid\x12\x12\n" +
	"\x04slug\x18\v \x01(\tR\x04slug\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12K\n" +
	"\n" +
	"recurrence\x18\n" +
	" \x01(\v2+.federated_meetup.product.v1.RecurrenceRuleR\n" +
	"recurrence\"\xeb\x03\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12%\n" +
	"\x0ecanonical_name\x18\x01 \x01(\tR\rcanonicalName\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12K\n" +
	"\fhosting_mode\x18\a \x01(\x0e2(.federated_meetup.product.v1.HostingModeR\vhostingMode\x12K\n" +
	"\fhosting_tier\x18\b \x01(\x0e2(.federated_meetup.product.v1.HostingTierR\vhostingTier\x12>\n" +
	"\apackage\x18\n" +
	" \x01(\x0e2$.federated_meetup.product.v1.PackageR\apackage\x12#\n" +
	"\rcustom_domain\x18\x03 \x01(\tR\fcustomDomain\x12!\n" +
	"\fmember_count\x18\t \x01(\x04R\vmemberCount\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb7\x01\n" +
	"\vGroupMember\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x04 \x01(\tR\tuserEmail\x125\n" +
	"\x04role\x18\x03 \x01(\x0e2!.federated_meetup.product.v1.RoleR\x04role\x127\n" +
	"\tjoined_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\"\xd8\x01\n" +
	"\x04Rsvp\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x05 \x01(\tR\tuserEmail\x12?\n" +
	"\x06status\x18\x04 \x01(\x0e2'.federated_meetup.product.v1.RsvpStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\battended\x18\x01 \x01(\bR\battended\"\x91\x03\n" +
	"\x13CreateTicketPayload\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\tticket_id\x18\b \x01(\tR\bticketId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12H\n" +
	"\ttier_type\x18\t \x01(\x0e2+.federated_meetup.product.v1.TicketTierTypeR\btierType\x12!\n" +
	"\fprice_amount\x18\x04 \x01(\x04R\vpriceAmount\x12%\n" +
	"\x0eprice_currency\x18\x05 \x01(\tR\rpriceCurrency\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x04R\bcapacity\x12@\n" +
	"\x0esale_starts_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fsaleStartsAt\x12<\n" +
	"\fsale_ends_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"saleEndsAt\"\xac\x01\n" +
	"\x13UpdateTicketPayload\x12\x1b\n" +
	"\tticket_id\x18\x05 \x01(\tR\bticketId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fprice_amount\x18\x03 \x01(\x04R\vpriceAmount\x12%\n" +
	"\x0eprice_currency\x18\x04 \x01(\tR\rpriceCurrency\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x04R\bcapacity\"\x87\x01\n" +
	"\x15PurchaseTicketPayload\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\tR\bticketId\x12%\n" +
	"\x0eattendee_email\x18\x01 \x01(\tR\rattendeeEmail\x12*\n" +
	"\x11stripe_session_id\x18\x02 \x01(\tR\x0fstripeSessionId\"_\n" +
	"\x12RefundOrderPayload\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"f\n" +
	"\x17CreateRecurrencePayload\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05rrule\x18\x02 \x01(\tR\x05rrule\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\"W\n" +
	"\x13AddExceptionPayload\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12%\n" +
	"\x0eexception_date\x18\x02 \x01(\tR\rexceptionDate\"s\n" +
	"\x16SetGroupPackagePayload\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12>\n" +
	"\apackage\x18\x02 \x01(\x0e2$.federated_meetup.product.v1.PackageR\apackage\"p\n" +
	"\x15SetHostingTierPayload\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12<\n" +
	"\x04tier\x18\x02 \x01(\x0e2(.federated_meetup.product.v1.HostingTierR\x04tier\"\x82\x01\n" +
	"\x17UpdateVisibilityPayload\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12L\n" +
	"\n" +
	"visibility\x18\x02 \x01(\x0e2,.federated_meetup.product.v1.EventVisibilityR\n" +
	"visibility\"\x87\x01\n" +
	"\x14SetMemberRolePayload\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x125\n" +
	"\x04role\x18\x02 \x01(\x0e2!.federated_meetup.product.v1.RoleR\x04role\"k\n" +
	"\x13MarkAttendedPayload\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x12\x1a\n" +
	"\battended\x18\x01 \x01(\bR\battended\"\x96\t\n" +
	"\x11ProductTransition\x12F\n" +
	"\x04type\x18\x01 \x01(\x0e22.federated_meetup.product.v1.ProductTransitionTypeR\x04type\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x10\n" +
	"\x03hlc\x18\x03 \x01(\fR\x03hlc\x12W\n" +
	"\rcreate_ticket\x18\n" +
	" \x01(\v20.federated_meetup.product.v1.CreateTicketPayloadH\x00R\fcreateTicket\x12W\n" +
	"\rupdate_ticket\x18\v \x01(\v20.federated_meetup.product.v1.UpdateTicketPayloadH\x00R\fupdateTicket\x12]\n" +
	"\x0fpurchase_ticket\x18\f \x01(\v22.federated_meetup.product.v1.PurchaseTicketPayloadH\x00R\x0epurchaseTicket\x12T\n" +
	"\frefund_order\x18\r \x01(\v2/.federated_meetup.product.v1.RefundOrderPayloadH\x00R\vrefundOrder\x12c\n" +
	"\x11create_recurrence\x18\x0e \x01(\v24.federated_meetup.product.v1.CreateRecurrencePayloadH\x00R\x10createRecurrence\x12W\n" +
	"\radd_exception\x18\x0f \x01(\v20.federated_meetup.product.v1.AddExceptionPayloadH\x00R\faddException\x12a\n" +
	"\x11set_group_package\x18\x10 \x01(\v23.federated_meetup.product.v1.SetGroupPackagePayloadH\x00R\x0fsetGroupPackage\x12^\n" +
	"\x10set_hosting_tier\x18\x11 \x01(\v22.federated_meetup.product.v1.SetHostingTierPayloadH\x00R\x0esetHostingTier\x12c\n" +
	"\x11update_visibility\x18\x12 \x01(\v24.federated_meetup.product.v1.UpdateVisibilityPayloadH\x00R\x10updateVisibility\x12[\n" +
	"\x0fset_member_role\x18\x13 \x01(\v21.federated_meetup.product.v1.SetMemberRolePayloadH\x00R\rsetMemberRole\x12W\n" +
	"\rmark_attended\x18\x14 \x01(\v20.federated_meetup.product.v1.MarkAttendedPayloadH\x00R\fmarkAttendedB\t\n" +
	"\apayload*\x91\x01\n" +
	"\aPackage\x12\x17\n" +
	"\x13PACKAGE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PACKAGE_FREE_COMMUNITY\x10\x01\x12\x1a\n" +
	"\x16PACKAGE_RECURRING_CLUB\x10\x02\x12\x1d\n" +
	"\x19PACKAGE_TICKETED_WORKSHOP\x10\x03\x12\x16\n" +
	"\x12PACKAGE_CONFERENCE\x10\x04*c\n" +
	"\vHostingMode\x12\x1c\n" +
	"\x18HOSTING_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16HOSTING_MODE_SELF_HOST\x10\x01\x12\x1a\n" +
	"\x16HOSTING_MODE_PAID_HOST\x10\x02*\x8d\x01\n" +
	"\vHostingTier\x12\x1c\n" +
	"\x18HOSTING_TIER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11HOSTING_TIER_FREE\x10\x01\x12\x1a\n" +
	"\x16HOSTING_TIER_COMMUNITY\x10\x02\x12\x14\n" +
	"\x10HOSTING_TIER_PRO\x10\x03\x12\x17\n" +
	"\x13HOSTING_TIER_STUDIO\x10\x04*\xaf\x01\n" +
	"\x0fEventVisibility\x12 \n" +
	"\x1cEVENT_VISIBILITY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_VISIBILITY_PUBLIC\x10\x01\x12\x1d\n" +
	"\x19EVENT_VISIBILITY_UNLISTED\x10\x02\x12\x1c\n" +
	"\x18EVENT_VISIBILITY_PRIVATE\x10\x03\x12 \n" +
	"\x1cEVENT_VISIBILITY_INVITE_ONLY\x10\x04*\x8b\x01\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x01\x12\x12\n" +
	"\x0eROLE_ORGANIZER\x10\x02\x12\x12\n" +
	"\x0eROLE_MODERATOR\x10\x03\x12\x12\n" +
	"\x0eROLE_TREASURER\x10\x04\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x05\x12\x10\n" +
	"\fROLE_PENDING\x10\x06*\xae\x01\n" +
	"\x0eTicketTierType\x12 \n" +
	"\x1cTICKET_TIER_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTICKET_TIER_TYPE_EARLY_BIRD\x10\x01\x12\x1c\n" +
	"\x18TICKET_TIER_TYPE_REGULAR\x10\x02\x12\x1e\n" +
	"\x1aTICKET_TIER_TYPE_SUPPORTER\x10\x03\x12\x1b\n" +
	"\x17TICKET_TIER_TYPE_CUSTOM\x10\x04*\xd5\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x02\x12\x19\n" +
	"\x15ORDER_STATUS_REFUNDED\x10\x03\x12#\n" +
	"\x1fORDER_STATUS_PARTIALLY_REFUNDED\x10\x04\x12\x19\n" +
	"\x15ORDER_STATUS_DISPUTED\x10\x05\x12\x17\n" +
	"\x13ORDER_STATUS_FAILED\x10\x06*\x8c\x01\n" +
	"\n" +
	"RsvpStatus\x12\x1b\n" +
	"\x17RSVP_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RSVP_STATUS_GOING\x10\x01\x12\x18\n" +
	"\x14RSVP_STATUS_WAITLIST\x10\x02\x12\x15\n" +
	"\x11RSVP_STATUS_MAYBE\x10\x03\x12\x19\n" +
	"\x15RSVP_STATUS_NOT_GOING\x10\x04*\xab\x04\n" +
	"\x15ProductTransitionType\x12'\n" +
	"#PRODUCT_TRANSITION_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%PRODUCT_TRANSITION_TYPE_CREATE_TICKET\x10\x01\x12)\n" +
	"%PRODUCT_TRANSITION_TYPE_UPDATE_TICKET\x10\x02\x12+\n" +
	"'PRODUCT_TRANSITION_TYPE_PURCHASE_TICKET\x10\x03\x12(\n" +
	"$PRODUCT_TRANSITION_TYPE_REFUND_ORDER\x10\x04\x12-\n" +
	")PRODUCT_TRANSITION_TYPE_CREATE_RECURRENCE\x10\x05\x12)\n" +
	"%PRODUCT_TRANSITION_TYPE_ADD_EXCEPTION\x10\x06\x12-\n" +
	")PRODUCT_TRANSITION_TYPE_SET_GROUP_PACKAGE\x10\a\x12,\n" +
	"(PRODUCT_TRANSITION_TYPE_SET_HOSTING_TIER\x10\b\x12-\n" +
	")PRODUCT_TRANSITION_TYPE_UPDATE_VISIBILITY\x10\t\x12+\n" +
	"'PRODUCT_TRANSITION_TYPE_SET_MEMBER_ROLE\x10\n" +
	"\x12)\n" +
	"%PRODUCT_TRANSITION_TYPE_MARK_ATTENDED\x10\vB`Z^github.com/sscoble/federated-meetup/proto/federated_meetup/product/v1;federatedmeetupproductv1b\x06proto3"

var (
	file_federated_meetup_product_v1_state_proto_rawDescOnce sync.Once
	file_federated_meetup_product_v1_state_proto_rawDescData []byte
)

func file_federated_meetup_product_v1_state_proto_rawDescGZIP() []byte {
	file_federated_meetup_product_v1_state_proto_rawDescOnce.Do(func() {
		file_federated_meetup_product_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federated_meetup_product_v1_state_proto_rawDesc), len(file_federated_meetup_product_v1_state_proto_rawDesc)))
	})
	return file_federated_meetup_product_v1_state_proto_rawDescData
}

var file_federated_meetup_product_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_federated_meetup_product_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_federated_meetup_product_v1_state_proto_goTypes = []any{
	(Package)(0),                    // 0: federated_meetup.product.v1.Package
	(HostingMode)(0),                // 1: federated_meetup.product.v1.HostingMode
	(HostingTier)(0),                // 2: federated_meetup.product.v1.HostingTier
	(EventVisibility)(0),            // 3: federated_meetup.product.v1.EventVisibility
	(Role)(0),                       // 4: federated_meetup.product.v1.Role
	(TicketTierType)(0),             // 5: federated_meetup.product.v1.TicketTierType
	(OrderStatus)(0),                // 6: federated_meetup.product.v1.OrderStatus
	(RsvpStatus)(0),                 // 7: federated_meetup.product.v1.RsvpStatus
	(ProductTransitionType)(0),      // 8: federated_meetup.product.v1.ProductTransitionType
	(*Money)(nil),                   // 9: federated_meetup.product.v1.Money
	(*Ticket)(nil),                  // 10: federated_meetup.product.v1.Ticket
	(*Order)(nil),                   // 11: federated_meetup.product.v1.Order
	(*RecurrenceRule)(nil),          // 12: federated_meetup.product.v1.RecurrenceRule
	(*Vendor)(nil),                  // 13: federated_meetup.product.v1.Vendor
	(*Sponsorship)(nil),             // 14: federated_meetup.product.v1.Sponsorship
	(*Event)(nil),                   // 15: federated_meetup.product.v1.Event
	(*Group)(nil),                   // 16: federated_meetup.product.v1.Group
	(*GroupMember)(nil),             // 17: federated_meetup.product.v1.GroupMember
	(*Rsvp)(nil),                    // 18: federated_meetup.product.v1.Rsvp
	(*CreateTicketPayload)(nil),     // 19: federated_meetup.product.v1.CreateTicketPayload
	(*UpdateTicketPayload)(nil),     // 20: federated_meetup.product.v1.UpdateTicketPayload
	(*PurchaseTicketPayload)(nil),   // 21: federated_meetup.product.v1.PurchaseTicketPayload
	(*RefundOrderPayload)(nil),      // 22: federated_meetup.product.v1.RefundOrderPayload
	(*CreateRecurrencePayload)(nil), // 23: federated_meetup.product.v1.CreateRecurrencePayload
	(*AddExceptionPayload)(nil),     // 24: federated_meetup.product.v1.AddExceptionPayload
	(*SetGroupPackagePayload)(nil),  // 25: federated_meetup.product.v1.SetGroupPackagePayload
	(*SetHostingTierPayload)(nil),   // 26: federated_meetup.product.v1.SetHostingTierPayload
	(*UpdateVisibilityPayload)(nil), // 27: federated_meetup.product.v1.UpdateVisibilityPayload
	(*SetMemberRolePayload)(nil),    // 28: federated_meetup.product.v1.SetMemberRolePayload
	(*MarkAttendedPayload)(nil),     // 29: federated_meetup.product.v1.MarkAttendedPayload
	(*ProductTransition)(nil),       // 30: federated_meetup.product.v1.ProductTransition
	(*timestamppb.Timestamp)(nil),   // 31: google.protobuf.Timestamp
}
var file_federated_meetup_product_v1_state_proto_depIdxs = []int32{
	5,  // 0: federated_meetup.product.v1.Ticket.tier_type:type_name -> federated_meetup.product.v1.TicketTierType
	9,  // 1: federated_meetup.product.v1.Ticket.price:type_name -> federated_meetup.product.v1.Money
	31, // 2: federated_meetup.product.v1.Ticket.sale_starts_at:type_name -> google.protobuf.Timestamp
	31, // 3: federated_meetup.product.v1.Ticket.sale_ends_at:type_name -> google.protobuf.Timestamp
	6,  // 4: federated_meetup.product.v1.Order.status:type_name -> federated_meetup.product.v1.OrderStatus
	9,  // 5: federated_meetup.product.v1.Order.amount_paid:type_name -> federated_meetup.product.v1.Money
	9,  // 6: federated_meetup.product.v1.Order.refunded_amount:type_name -> federated_meetup.product.v1.Money
	31, // 7: federated_meetup.product.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	31, // 8: federated_meetup.product.v1.Order.refunded_at:type_name -> google.protobuf.Timestamp
	31, // 9: federated_meetup.product.v1.Event.starts_at:type_name -> google.protobuf.Timestamp
	31, // 10: federated_meetup.product.v1.Event.ends_at:type_name -> google.protobuf.Timestamp
	3,  // 11: federated_meetup.product.v1.Event.visibility:type_name -> federated_meetup.product.v1.EventVisibility
	0,  // 12: federated_meetup.product.v1.Event.package:type_name -> federated_meetup.product.v1.Package
	12, // 13: federated_meetup.product.v1.Event.recurrence:type_name -> federated_meetup.product.v1.RecurrenceRule
	1,  // 14: federated_meetup.product.v1.Group.hosting_mode:type_name -> federated_meetup.product.v1.HostingMode
	2,  // 15: federated_meetup.product.v1.Group.hosting_tier:type_name -> federated_meetup.product.v1.HostingTier
	0,  // 16: federated_meetup.product.v1.Group.package:type_name -> federated_meetup.product.v1.Package
	31, // 17: federated_meetup.product.v1.Group.created_at:type_name -> google.protobuf.Timestamp
	4,  // 18: federated_meetup.product.v1.GroupMember.role:type_name -> federated_meetup.product.v1.Role
	31, // 19: federated_meetup.product.v1.GroupMember.joined_at:type_name -> google.protobuf.Timestamp
	7,  // 20: federated_meetup.product.v1.Rsvp.status:type_name -> federated_meetup.product.v1.RsvpStatus
	31, // 21: federated_meetup.product.v1.Rsvp.created_at:type_name -> google.protobuf.Timestamp
	5,  // 22: federated_meetup.product.v1.CreateTicketPayload.tier_type:type_name -> federated_meetup.product.v1.TicketTierType
	31, // 23: federated_meetup.product.v1.CreateTicketPayload.sale_starts_at:type_name -> google.protobuf.Timestamp
	31, // 24: federated_meetup.product.v1.CreateTicketPayload.sale_ends_at:type_name -> google.protobuf.Timestamp
	0,  // 25: federated_meetup.product.v1.SetGroupPackagePayload.package:type_name -> federated_meetup.product.v1.Package
	2,  // 26: federated_meetup.product.v1.SetHostingTierPayload.tier:type_name -> federated_meetup.product.v1.HostingTier
	3,  // 27: federated_meetup.product.v1.UpdateVisibilityPayload.visibility:type_name -> federated_meetup.product.v1.EventVisibility
	4,  // 28: federated_meetup.product.v1.SetMemberRolePayload.role:type_name -> federated_meetup.product.v1.Role
	8,  // 29: federated_meetup.product.v1.ProductTransition.type:type_name -> federated_meetup.product.v1.ProductTransitionType
	19, // 30: federated_meetup.product.v1.ProductTransition.create_ticket:type_name -> federated_meetup.product.v1.CreateTicketPayload
	20, // 31: federated_meetup.product.v1.ProductTransition.update_ticket:type_name -> federated_meetup.product.v1.UpdateTicketPayload
	21, // 32: federated_meetup.product.v1.ProductTransition.purchase_ticket:type_name -> federated_meetup.product.v1.PurchaseTicketPayload
	22, // 33: federated_meetup.product.v1.ProductTransition.refund_order:type_name -> federated_meetup.product.v1.RefundOrderPayload
	23, // 34: federated_meetup.product.v1.ProductTransition.create_recurrence:type_name -> federated_meetup.product.v1.CreateRecurrencePayload
	24, // 35: federated_meetup.product.v1.ProductTransition.add_exception:type_name -> federated_meetup.product.v1.AddExceptionPayload
	25, // 36: federated_meetup.product.v1.ProductTransition.set_group_package:type_name -> federated_meetup.product.v1.SetGroupPackagePayload
	26, // 37: federated_meetup.product.v1.ProductTransition.set_hosting_tier:type_name -> federated_meetup.product.v1.SetHostingTierPayload
	27, // 38: federated_meetup.product.v1.ProductTransition.update_visibility:type_name -> federated_meetup.product.v1.UpdateVisibilityPayload
	28, // 39: federated_meetup.product.v1.ProductTransition.set_member_role:type_name -> federated_meetup.product.v1.SetMemberRolePayload
	29, // 40: federated_meetup.product.v1.ProductTransition.mark_attended:type_name -> federated_meetup.product.v1.MarkAttendedPayload
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_federated_meetup_product_v1_state_proto_init() }
func file_federated_meetup_product_v1_state_proto_init() {
	if File_federated_meetup_product_v1_state_proto != nil {
		return
	}
	file_federated_meetup_product_v1_state_proto_msgTypes[21].OneofWrappers = []any{
		(*ProductTransition_CreateTicket)(nil),
		(*ProductTransition_UpdateTicket)(nil),
		(*ProductTransition_PurchaseTicket)(nil),
		(*ProductTransition_RefundOrder)(nil),
		(*ProductTransition_CreateRecurrence)(nil),
		(*ProductTransition_AddException)(nil),
		(*ProductTransition_SetGroupPackage)(nil),
		(*ProductTransition_SetHostingTier)(nil),
		(*ProductTransition_UpdateVisibility)(nil),
		(*ProductTransition_SetMemberRole)(nil),
		(*ProductTransition_MarkAttended)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federated_meetup_product_v1_state_proto_rawDesc), len(file_federated_meetup_product_v1_state_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_federated_meetup_product_v1_state_proto_goTypes,
		DependencyIndexes: file_federated_meetup_product_v1_state_proto_depIdxs,
		EnumInfos:         file_federated_meetup_product_v1_state_proto_enumTypes,
		MessageInfos:      file_federated_meetup_product_v1_state_proto_msgTypes,
	}.Build()
	File_federated_meetup_product_v1_state_proto = out.File
	file_federated_meetup_product_v1_state_proto_goTypes = nil
	file_federated_meetup_product_v1_state_proto_depIdxs = nil
}
