// SPDX-License-Identifier: AGPL-3.0
//
// federated-meetup client RPC surface — the open client protobuf standard.
//
// ConnectRPC (https://connectrpc.com) over HTTP/2. Implementations:
//   - Client: any ConnectRPC client. We ship a Go reference impl (OSS).
//   - Server: any host that speaks the protocol. We ship a Go reference impl
//     (OSS for the wire layer; closed-source for the product features).
//
// Server-to-server federation traffic uses a SEPARATE WireGuard-only transport.
// It is intentionally NOT exposed here. See docs/02-PROTOCOL.md section 5.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: federated_meetup/v1/rpc.proto

package federatedmeetupv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wscoble/federated-meetup/proto/federated_meetup/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HostServiceName is the fully-qualified name of the HostService service.
	HostServiceName = "federated_meetup.v1.HostService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HostServiceGetGroupProcedure is the fully-qualified name of the HostService's GetGroup RPC.
	HostServiceGetGroupProcedure = "/federated_meetup.v1.HostService/GetGroup"
	// HostServiceGetEventProcedure is the fully-qualified name of the HostService's GetEvent RPC.
	HostServiceGetEventProcedure = "/federated_meetup.v1.HostService/GetEvent"
	// HostServiceListEventsProcedure is the fully-qualified name of the HostService's ListEvents RPC.
	HostServiceListEventsProcedure = "/federated_meetup.v1.HostService/ListEvents"
	// HostServiceListGroupsProcedure is the fully-qualified name of the HostService's ListGroups RPC.
	HostServiceListGroupsProcedure = "/federated_meetup.v1.HostService/ListGroups"
	// HostServiceGetLogProcedure is the fully-qualified name of the HostService's GetLog RPC.
	HostServiceGetLogProcedure = "/federated_meetup.v1.HostService/GetLog"
	// HostServiceGetSnapshotProcedure is the fully-qualified name of the HostService's GetSnapshot RPC.
	HostServiceGetSnapshotProcedure = "/federated_meetup.v1.HostService/GetSnapshot"
	// HostServiceSubmitTransitionProcedure is the fully-qualified name of the HostService's
	// SubmitTransition RPC.
	HostServiceSubmitTransitionProcedure = "/federated_meetup.v1.HostService/SubmitTransition"
	// HostServiceSubmitUserActionProcedure is the fully-qualified name of the HostService's
	// SubmitUserAction RPC.
	HostServiceSubmitUserActionProcedure = "/federated_meetup.v1.HostService/SubmitUserAction"
	// HostServiceResolveNameProcedure is the fully-qualified name of the HostService's ResolveName RPC.
	HostServiceResolveNameProcedure = "/federated_meetup.v1.HostService/ResolveName"
	// HostServiceSubscribeProcedure is the fully-qualified name of the HostService's Subscribe RPC.
	HostServiceSubscribeProcedure = "/federated_meetup.v1.HostService/Subscribe"
	// HostServiceSubmitEvidenceProcedure is the fully-qualified name of the HostService's
	// SubmitEvidence RPC.
	HostServiceSubmitEvidenceProcedure = "/federated_meetup.v1.HostService/SubmitEvidence"
)

// HostServiceClient is a client for the federated_meetup.v1.HostService service.
type HostServiceClient interface {
	// Reads.
	GetGroup(context.Context, *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error)
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	ListGroups(context.Context, *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error)
	GetLog(context.Context, *connect.Request[v1.GetLogRequest]) (*connect.Response[v1.GetLogResponse], error)
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error)
	// Writes. SubmitTransition is for steward-signed transitions (CREATE_GROUP,
	// ADD_STEWARD, FORK, MIGRATE, etc.). SubmitUserAction is for user-signed
	// actions (RSVP, ATTEST).
	SubmitTransition(context.Context, *connect.Request[v1.SubmitTransitionRequest]) (*connect.Response[v1.SubmitTransitionResponse], error)
	SubmitUserAction(context.Context, *connect.Request[v1.SubmitUserActionRequest]) (*connect.Response[v1.SubmitUserActionResponse], error)
	// Discovery.
	ResolveName(context.Context, *connect.Request[v1.ResolveNameRequest]) (*connect.Response[v1.ResolveNameResponse], error)
	// Streaming. Subscribe delivers live transition events as they are
	// applied. Clients can resume after disconnect via since_index.
	// The stream is per-group; clients wanting multiple groups open
	// one Subscribe per group.
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.TransitionEvent], error)
	// Federation. SubmitEvidence lets a peer gossip equivocation
	// evidence to this host. The host stores it for SLASH_STEWARD
	// submission and forwards to its own peers.
	SubmitEvidence(context.Context, *connect.Request[v1.EvidenceEnvelope]) (*connect.Response[v1.Ack], error)
}

// NewHostServiceClient constructs a client for the federated_meetup.v1.HostService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHostServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HostServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	hostServiceMethods := v1.File_federated_meetup_v1_rpc_proto.Services().ByName("HostService").Methods()
	return &hostServiceClient{
		getGroup: connect.NewClient[v1.GetGroupRequest, v1.GetGroupResponse](
			httpClient,
			baseURL+HostServiceGetGroupProcedure,
			connect.WithSchema(hostServiceMethods.ByName("GetGroup")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[v1.GetEventRequest, v1.GetEventResponse](
			httpClient,
			baseURL+HostServiceGetEventProcedure,
			connect.WithSchema(hostServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[v1.ListEventsRequest, v1.ListEventsResponse](
			httpClient,
			baseURL+HostServiceListEventsProcedure,
			connect.WithSchema(hostServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		listGroups: connect.NewClient[v1.ListGroupsRequest, v1.ListGroupsResponse](
			httpClient,
			baseURL+HostServiceListGroupsProcedure,
			connect.WithSchema(hostServiceMethods.ByName("ListGroups")),
			connect.WithClientOptions(opts...),
		),
		getLog: connect.NewClient[v1.GetLogRequest, v1.GetLogResponse](
			httpClient,
			baseURL+HostServiceGetLogProcedure,
			connect.WithSchema(hostServiceMethods.ByName("GetLog")),
			connect.WithClientOptions(opts...),
		),
		getSnapshot: connect.NewClient[v1.GetSnapshotRequest, v1.GetSnapshotResponse](
			httpClient,
			baseURL+HostServiceGetSnapshotProcedure,
			connect.WithSchema(hostServiceMethods.ByName("GetSnapshot")),
			connect.WithClientOptions(opts...),
		),
		submitTransition: connect.NewClient[v1.SubmitTransitionRequest, v1.SubmitTransitionResponse](
			httpClient,
			baseURL+HostServiceSubmitTransitionProcedure,
			connect.WithSchema(hostServiceMethods.ByName("SubmitTransition")),
			connect.WithClientOptions(opts...),
		),
		submitUserAction: connect.NewClient[v1.SubmitUserActionRequest, v1.SubmitUserActionResponse](
			httpClient,
			baseURL+HostServiceSubmitUserActionProcedure,
			connect.WithSchema(hostServiceMethods.ByName("SubmitUserAction")),
			connect.WithClientOptions(opts...),
		),
		resolveName: connect.NewClient[v1.ResolveNameRequest, v1.ResolveNameResponse](
			httpClient,
			baseURL+HostServiceResolveNameProcedure,
			connect.WithSchema(hostServiceMethods.ByName("ResolveName")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.TransitionEvent](
			httpClient,
			baseURL+HostServiceSubscribeProcedure,
			connect.WithSchema(hostServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		submitEvidence: connect.NewClient[v1.EvidenceEnvelope, v1.Ack](
			httpClient,
			baseURL+HostServiceSubmitEvidenceProcedure,
			connect.WithSchema(hostServiceMethods.ByName("SubmitEvidence")),
			connect.WithClientOptions(opts...),
		),
	}
}

// hostServiceClient implements HostServiceClient.
type hostServiceClient struct {
	getGroup         *connect.Client[v1.GetGroupRequest, v1.GetGroupResponse]
	getEvent         *connect.Client[v1.GetEventRequest, v1.GetEventResponse]
	listEvents       *connect.Client[v1.ListEventsRequest, v1.ListEventsResponse]
	listGroups       *connect.Client[v1.ListGroupsRequest, v1.ListGroupsResponse]
	getLog           *connect.Client[v1.GetLogRequest, v1.GetLogResponse]
	getSnapshot      *connect.Client[v1.GetSnapshotRequest, v1.GetSnapshotResponse]
	submitTransition *connect.Client[v1.SubmitTransitionRequest, v1.SubmitTransitionResponse]
	submitUserAction *connect.Client[v1.SubmitUserActionRequest, v1.SubmitUserActionResponse]
	resolveName      *connect.Client[v1.ResolveNameRequest, v1.ResolveNameResponse]
	subscribe        *connect.Client[v1.SubscribeRequest, v1.TransitionEvent]
	submitEvidence   *connect.Client[v1.EvidenceEnvelope, v1.Ack]
}

// GetGroup calls federated_meetup.v1.HostService.GetGroup.
func (c *hostServiceClient) GetGroup(ctx context.Context, req *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error) {
	return c.getGroup.CallUnary(ctx, req)
}

// GetEvent calls federated_meetup.v1.HostService.GetEvent.
func (c *hostServiceClient) GetEvent(ctx context.Context, req *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// ListEvents calls federated_meetup.v1.HostService.ListEvents.
func (c *hostServiceClient) ListEvents(ctx context.Context, req *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// ListGroups calls federated_meetup.v1.HostService.ListGroups.
func (c *hostServiceClient) ListGroups(ctx context.Context, req *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error) {
	return c.listGroups.CallUnary(ctx, req)
}

// GetLog calls federated_meetup.v1.HostService.GetLog.
func (c *hostServiceClient) GetLog(ctx context.Context, req *connect.Request[v1.GetLogRequest]) (*connect.Response[v1.GetLogResponse], error) {
	return c.getLog.CallUnary(ctx, req)
}

// GetSnapshot calls federated_meetup.v1.HostService.GetSnapshot.
func (c *hostServiceClient) GetSnapshot(ctx context.Context, req *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error) {
	return c.getSnapshot.CallUnary(ctx, req)
}

// SubmitTransition calls federated_meetup.v1.HostService.SubmitTransition.
func (c *hostServiceClient) SubmitTransition(ctx context.Context, req *connect.Request[v1.SubmitTransitionRequest]) (*connect.Response[v1.SubmitTransitionResponse], error) {
	return c.submitTransition.CallUnary(ctx, req)
}

// SubmitUserAction calls federated_meetup.v1.HostService.SubmitUserAction.
func (c *hostServiceClient) SubmitUserAction(ctx context.Context, req *connect.Request[v1.SubmitUserActionRequest]) (*connect.Response[v1.SubmitUserActionResponse], error) {
	return c.submitUserAction.CallUnary(ctx, req)
}

// ResolveName calls federated_meetup.v1.HostService.ResolveName.
func (c *hostServiceClient) ResolveName(ctx context.Context, req *connect.Request[v1.ResolveNameRequest]) (*connect.Response[v1.ResolveNameResponse], error) {
	return c.resolveName.CallUnary(ctx, req)
}

// Subscribe calls federated_meetup.v1.HostService.Subscribe.
func (c *hostServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.TransitionEvent], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// SubmitEvidence calls federated_meetup.v1.HostService.SubmitEvidence.
func (c *hostServiceClient) SubmitEvidence(ctx context.Context, req *connect.Request[v1.EvidenceEnvelope]) (*connect.Response[v1.Ack], error) {
	return c.submitEvidence.CallUnary(ctx, req)
}

// HostServiceHandler is an implementation of the federated_meetup.v1.HostService service.
type HostServiceHandler interface {
	// Reads.
	GetGroup(context.Context, *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error)
	GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error)
	ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error)
	ListGroups(context.Context, *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error)
	GetLog(context.Context, *connect.Request[v1.GetLogRequest]) (*connect.Response[v1.GetLogResponse], error)
	GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error)
	// Writes. SubmitTransition is for steward-signed transitions (CREATE_GROUP,
	// ADD_STEWARD, FORK, MIGRATE, etc.). SubmitUserAction is for user-signed
	// actions (RSVP, ATTEST).
	SubmitTransition(context.Context, *connect.Request[v1.SubmitTransitionRequest]) (*connect.Response[v1.SubmitTransitionResponse], error)
	SubmitUserAction(context.Context, *connect.Request[v1.SubmitUserActionRequest]) (*connect.Response[v1.SubmitUserActionResponse], error)
	// Discovery.
	ResolveName(context.Context, *connect.Request[v1.ResolveNameRequest]) (*connect.Response[v1.ResolveNameResponse], error)
	// Streaming. Subscribe delivers live transition events as they are
	// applied. Clients can resume after disconnect via since_index.
	// The stream is per-group; clients wanting multiple groups open
	// one Subscribe per group.
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.TransitionEvent]) error
	// Federation. SubmitEvidence lets a peer gossip equivocation
	// evidence to this host. The host stores it for SLASH_STEWARD
	// submission and forwards to its own peers.
	SubmitEvidence(context.Context, *connect.Request[v1.EvidenceEnvelope]) (*connect.Response[v1.Ack], error)
}

// NewHostServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHostServiceHandler(svc HostServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	hostServiceMethods := v1.File_federated_meetup_v1_rpc_proto.Services().ByName("HostService").Methods()
	hostServiceGetGroupHandler := connect.NewUnaryHandler(
		HostServiceGetGroupProcedure,
		svc.GetGroup,
		connect.WithSchema(hostServiceMethods.ByName("GetGroup")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceGetEventHandler := connect.NewUnaryHandler(
		HostServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(hostServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceListEventsHandler := connect.NewUnaryHandler(
		HostServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(hostServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceListGroupsHandler := connect.NewUnaryHandler(
		HostServiceListGroupsProcedure,
		svc.ListGroups,
		connect.WithSchema(hostServiceMethods.ByName("ListGroups")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceGetLogHandler := connect.NewUnaryHandler(
		HostServiceGetLogProcedure,
		svc.GetLog,
		connect.WithSchema(hostServiceMethods.ByName("GetLog")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceGetSnapshotHandler := connect.NewUnaryHandler(
		HostServiceGetSnapshotProcedure,
		svc.GetSnapshot,
		connect.WithSchema(hostServiceMethods.ByName("GetSnapshot")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceSubmitTransitionHandler := connect.NewUnaryHandler(
		HostServiceSubmitTransitionProcedure,
		svc.SubmitTransition,
		connect.WithSchema(hostServiceMethods.ByName("SubmitTransition")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceSubmitUserActionHandler := connect.NewUnaryHandler(
		HostServiceSubmitUserActionProcedure,
		svc.SubmitUserAction,
		connect.WithSchema(hostServiceMethods.ByName("SubmitUserAction")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceResolveNameHandler := connect.NewUnaryHandler(
		HostServiceResolveNameProcedure,
		svc.ResolveName,
		connect.WithSchema(hostServiceMethods.ByName("ResolveName")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceSubscribeHandler := connect.NewServerStreamHandler(
		HostServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(hostServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	hostServiceSubmitEvidenceHandler := connect.NewUnaryHandler(
		HostServiceSubmitEvidenceProcedure,
		svc.SubmitEvidence,
		connect.WithSchema(hostServiceMethods.ByName("SubmitEvidence")),
		connect.WithHandlerOptions(opts...),
	)
	return "/federated_meetup.v1.HostService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HostServiceGetGroupProcedure:
			hostServiceGetGroupHandler.ServeHTTP(w, r)
		case HostServiceGetEventProcedure:
			hostServiceGetEventHandler.ServeHTTP(w, r)
		case HostServiceListEventsProcedure:
			hostServiceListEventsHandler.ServeHTTP(w, r)
		case HostServiceListGroupsProcedure:
			hostServiceListGroupsHandler.ServeHTTP(w, r)
		case HostServiceGetLogProcedure:
			hostServiceGetLogHandler.ServeHTTP(w, r)
		case HostServiceGetSnapshotProcedure:
			hostServiceGetSnapshotHandler.ServeHTTP(w, r)
		case HostServiceSubmitTransitionProcedure:
			hostServiceSubmitTransitionHandler.ServeHTTP(w, r)
		case HostServiceSubmitUserActionProcedure:
			hostServiceSubmitUserActionHandler.ServeHTTP(w, r)
		case HostServiceResolveNameProcedure:
			hostServiceResolveNameHandler.ServeHTTP(w, r)
		case HostServiceSubscribeProcedure:
			hostServiceSubscribeHandler.ServeHTTP(w, r)
		case HostServiceSubmitEvidenceProcedure:
			hostServiceSubmitEvidenceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHostServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHostServiceHandler struct{}

func (UnimplementedHostServiceHandler) GetGroup(context.Context, *connect.Request[v1.GetGroupRequest]) (*connect.Response[v1.GetGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.GetGroup is not implemented"))
}

func (UnimplementedHostServiceHandler) GetEvent(context.Context, *connect.Request[v1.GetEventRequest]) (*connect.Response[v1.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.GetEvent is not implemented"))
}

func (UnimplementedHostServiceHandler) ListEvents(context.Context, *connect.Request[v1.ListEventsRequest]) (*connect.Response[v1.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.ListEvents is not implemented"))
}

func (UnimplementedHostServiceHandler) ListGroups(context.Context, *connect.Request[v1.ListGroupsRequest]) (*connect.Response[v1.ListGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.ListGroups is not implemented"))
}

func (UnimplementedHostServiceHandler) GetLog(context.Context, *connect.Request[v1.GetLogRequest]) (*connect.Response[v1.GetLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.GetLog is not implemented"))
}

func (UnimplementedHostServiceHandler) GetSnapshot(context.Context, *connect.Request[v1.GetSnapshotRequest]) (*connect.Response[v1.GetSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.GetSnapshot is not implemented"))
}

func (UnimplementedHostServiceHandler) SubmitTransition(context.Context, *connect.Request[v1.SubmitTransitionRequest]) (*connect.Response[v1.SubmitTransitionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.SubmitTransition is not implemented"))
}

func (UnimplementedHostServiceHandler) SubmitUserAction(context.Context, *connect.Request[v1.SubmitUserActionRequest]) (*connect.Response[v1.SubmitUserActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.SubmitUserAction is not implemented"))
}

func (UnimplementedHostServiceHandler) ResolveName(context.Context, *connect.Request[v1.ResolveNameRequest]) (*connect.Response[v1.ResolveNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.ResolveName is not implemented"))
}

func (UnimplementedHostServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.TransitionEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.Subscribe is not implemented"))
}

func (UnimplementedHostServiceHandler) SubmitEvidence(context.Context, *connect.Request[v1.EvidenceEnvelope]) (*connect.Response[v1.Ack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("federated_meetup.v1.HostService.SubmitEvidence is not implemented"))
}
