// SPDX-License-Identifier: MIT
//
// fedmeetup is the federated-meetup host daemon. It serves the open
// ConnectRPC API defined in proto/federated_meetup/v1/rpc.proto.
//
// The HTTP handler is GENERATED by protoc-gen-connect-go. This main
// package is a thin bootstrap: load config, build a *host.Service,
// mount the generated handler, run the server. No handler code is
// hand-written here — the generated HostServiceHandler interface is
// implemented in internal/host/service.go.
//
// v0: in-memory state only. The group identity comes from env config.
//     No persistence, no auto-bootstrap, no signing key — operators
//     submit CREATE_GROUP via the wire, or fork the state from a peer
//     over the server-to-server transport (cycle 71+ work).
//
// v0 config (all from env):
//   HOSTD_ADDR         listen address (default ":8080")
//   HOSTD_GROUP_KEY    hex-encoded 32-byte group public key (required)
//   HOSTD_NAME         canonical name this host advertises (default "hostd")
//   HOSTD_STEWARDS     comma-separated hex keys (initial stewards; v0 unused)
//   HOSTD_THRESHOLD    initial threshold (default 0; v0 unused)
package main

import (
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/sscoble/federated-meetup/proto/federated_meetup/v1/federatedmeetupv1connect"

	"github.com/sscoble/federated-meetup/internal/group"
	"github.com/sscoble/federated-meetup/internal/host"
	"github.com/sscoble/federated-meetup/internal/types"
)

// config holds the runtime configuration of fedmeetup. All values come
// from environment variables (see package doc).
type config struct {
	addr      string
	groupKey  types.PublicKey
	name      string
	threshold uint32
}

func loadConfig() (*config, error) {
	cfg := &config{
		addr: getEnv("HOSTD_ADDR", ":8080"),
		name: getEnv("HOSTD_NAME", "hostd"),
	}

	gkHex := os.Getenv("HOSTD_GROUP_KEY")
	if gkHex == "" {
		return nil, errors.New("HOSTD_GROUP_KEY is required (hex 32 bytes)")
	}
	gkBytes, err := hex.DecodeString(strings.TrimPrefix(gkHex, "0x"))
	if err != nil {
		return nil, fmt.Errorf("HOSTD_GROUP_KEY: %w", err)
	}
	if len(gkBytes) != 32 {
		return nil, fmt.Errorf("HOSTD_GROUP_KEY: got %d bytes, want 32", len(gkBytes))
	}
	copy(cfg.groupKey[:], gkBytes)

	if t := os.Getenv("HOSTD_THRESHOLD"); t != "" {
		v, err := strconv.ParseUint(t, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("HOSTD_THRESHOLD: %w", err)
		}
		cfg.threshold = uint32(v)
	}
	_ = os.Getenv("HOSTD_STEWARDS") // v0: parsed but unused.
	return cfg, nil
}

func getEnv(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func main() {
	cfg, err := loadConfig()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	state := group.NewState(cfg.groupKey)
	svc := host.NewService(state, cfg.name)

	mux := http.NewServeMux()
	path, handler := federatedmeetupv1connect.NewHostServiceHandler(svc)
	mux.Handle(path, handler)
	// Health endpoint — not part of the protobuf surface; just for liveness probes.
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok\n"))
	})
	// Dump the public key for ops + clients that want to verify the binding.
	mux.HandleFunc("/identity", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("content-type", "application/json")
		fmt.Fprintf(w, `{"group_key":"0x%s","name":%q,"threshold":%d}`+"\n",
			hex.EncodeToString(cfg.groupKey[:]), cfg.name, cfg.threshold)
	})

	srv := &http.Server{
		Addr:              cfg.addr,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
		// ConnectRPC uses HTTP/2; net/http auto-negotiates with TLS.
		// For v0 we serve plaintext HTTP/1.1; TLS termination is a
		// deployment concern (fronted by a reverse proxy or added in
		// cycle 72+).
	}

	idleConnsClosed := make(chan struct{})
	go func() {
		sigint := make(chan os.Signal, 1)
		signal.Notify(sigint, os.Interrupt, syscall.SIGTERM)
		<-sigint

		log.Printf("shutdown: draining connections for up to 10s")
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := srv.Shutdown(ctx); err != nil {
			log.Printf("shutdown: %v", err)
		}
		close(idleConnsClosed)
	}()

	log.Printf("fedmeetup: listening on %s, group_key=0x%s, name=%q, threshold=%d, mount=%s",
		cfg.addr, hex.EncodeToString(cfg.groupKey[:]), cfg.name, cfg.threshold, path)
	log.Printf("fedmeetup: HostService=%s", federatedmeetupv1connect.HostServiceName)
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatalf("listen: %v", err)
	}
	<-idleConnsClosed
	log.Printf("fedmeetup: stopped")
}
