// SPDX-License-Identifier: AGPL-3.0
//
// fedmeetup is the federated-meetup host daemon. It serves the open
// ConnectRPC API, MCP discovery endpoints, and the server-rendered web
// UI — all on a single port.
//
// The ConnectRPC handler is GENERATED by protoc-gen-connect-go. The web
// UI, MCP server, and discovery endpoints are wired in alongside it.
//
// v0: in-memory protocol state, SQLite for web cache/RSVPs/sessions.
//     The group identity comes from env config. No persistence for the
//     protocol log yet — operators submit CREATE_GROUP via the wire, or
//     fork the state from a peer over the server-to-server transport.
//
// v0 config (all from env):
//   HOSTD_ADDR         listen address (default ":8080")
//   HOSTD_GROUP_KEY    hex-encoded 32-byte group public key (required)
//   HOSTD_NAME         canonical name this host advertises (default "hostd")
//   HOSTD_STEWARDS     comma-separated hex keys (initial stewards; v0 unused)
//   HOSTD_THRESHOLD    initial threshold (default 0; v0 unused)
//   HOSTD_BASE_URL     public base URL for absolute links/JSON-LD (e.g. "https://fm.scoble.me")
//   HOSTD_DB_PATH      SQLite path for web store (default "fedmeetup.db")
//   HOSTD_DESCRIPTION  host description for discovery endpoints
//   HOSTD_AREA         geographic area for discovery (e.g. "Las Vegas, NV")
package main

import (
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/sscoble/federated-meetup/proto/federated_meetup/v1/federatedmeetupv1connect"

	"github.com/sscoble/federated-meetup/internal/group"
	"github.com/sscoble/federated-meetup/internal/host"
	"github.com/sscoble/federated-meetup/internal/mcp"
	"github.com/sscoble/federated-meetup/internal/product"
	"github.com/sscoble/federated-meetup/internal/types"
	"github.com/sscoble/federated-meetup/internal/web"
)

// config holds the runtime configuration of fedmeetup. All values come
// from environment variables (see package doc).
type config struct {
	addr        string
	groupKey    types.PublicKey
	name        string
	threshold   uint32
	baseURL     string
	dbPath      string
	description string
	area        string
}

func loadConfig() (*config, error) {
	cfg := &config{
		addr:        getEnv("HOSTD_ADDR", ":8080"),
		name:        getEnv("HOSTD_NAME", "hostd"),
		baseURL:     getEnv("HOSTD_BASE_URL", "http://localhost:8080"),
		dbPath:      getEnv("HOSTD_DB_PATH", "fedmeetup.db"),
		description: getEnv("HOSTD_DESCRIPTION", "Federated Meetup host"),
		area:        getEnv("HOSTD_AREA", ""),
	}

	gkHex := os.Getenv("HOSTD_GROUP_KEY")
	if gkHex == "" {
		return nil, errors.New("HOSTD_GROUP_KEY is required (hex 32 bytes)")
	}
	gkBytes, err := hex.DecodeString(strings.TrimPrefix(gkHex, "0x"))
	if err != nil {
		return nil, fmt.Errorf("HOSTD_GROUP_KEY: %w", err)
	}
	if len(gkBytes) != 32 {
		return nil, fmt.Errorf("HOSTD_GROUP_KEY: got %d bytes, want 32", len(gkBytes))
	}
	copy(cfg.groupKey[:], gkBytes)

	if t := os.Getenv("HOSTD_THRESHOLD"); t != "" {
		v, err := strconv.ParseUint(t, 10, 32)
		if err != nil {
			return nil, fmt.Errorf("HOSTD_THRESHOLD: %w", err)
		}
		cfg.threshold = uint32(v)
	}
	_ = os.Getenv("HOSTD_STEWARDS") // v0: parsed but unused.
	return cfg, nil
}

func getEnv(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

func main() {
	cfg, err := loadConfig()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	// ---- Protocol layer (ConnectRPC) ----
	state := group.NewState(cfg.groupKey)
	svc := host.NewService(cfg.name, state)

	// ---- Product layer (ticketing, orders, auth) ----
	prodStore := product.NewStore()
	prodSvc := product.NewService(prodStore, nil)

	// ---- Web layer (HTMX + SQLite) ----
	dsn := fmt.Sprintf("file:%s?_journal_mode=WAL&_busy_timeout=5000", cfg.dbPath)
	webStore, err := web.NewStore(dsn)
	if err != nil {
		log.Fatalf("web store: %v", err)
	}
	defer webStore.Close()

	webSrv, err := web.NewServer(svc, prodSvc, webStore)
	if err != nil {
		log.Fatalf("web server: %v", err)
	}

	// Seed demo data if the product store is empty (idempotent).
	webSrv.SeedData()

	// ---- MCP discovery layer ----
	mcpCfg := mcp.HostConfig{
		Name:           cfg.name,
		URL:            cfg.baseURL,
		Description:    cfg.description,
		GeographicArea: cfg.area,
	}

	// ---- Single mux: ConnectRPC + MCP + discovery + web UI ----
	mux := http.NewServeMux()

	// ConnectRPC
	rpcPath, rpcHandler := federatedmeetupv1connect.NewHostServiceHandler(svc)
	mux.Handle(rpcPath, rpcHandler)

	// MCP + discovery endpoints
	mcp.RegisterEndpoints(mux, svc, mcpCfg)

	// Web UI (all routes: /, /groups/, /events/, /dashboard/, /rsvp/, /checkout/, /static/)
	mux.Handle("/", webSrv.Routes())

	// Health + identity (protocol ops)
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok\n"))
	})
	mux.HandleFunc("/identity", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("content-type", "application/json")
		fmt.Fprintf(w, `{"group_key":"0x%s","name":%q,"threshold":%d}`+"\n",
			hex.EncodeToString(cfg.groupKey[:]), cfg.name, cfg.threshold)
	})

	srv := &http.Server{
		Addr:              cfg.addr,
		Handler:           mux,
		ReadHeaderTimeout: 5 * time.Second,
		// ConnectRPC uses HTTP/2; net/http auto-negotiates with TLS.
		// For v0 we serve plaintext HTTP/1.1; TLS termination is a
		// deployment concern (fronted by a reverse proxy or added in
		// cycle 72+).
	}

	idleConnsClosed := make(chan struct{})
	go func() {
		sigint := make(chan os.Signal, 1)
		signal.Notify(sigint, os.Interrupt, syscall.SIGTERM)
		<-sigint

		log.Printf("shutdown: draining connections for up to 10s")
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		if err := srv.Shutdown(ctx); err != nil {
			log.Printf("shutdown: %v", err)
		}
		close(idleConnsClosed)
	}()

	log.Printf("fedmeetup: listening on %s, group_key=0x%s, name=%q, threshold=%d, mount=%s",
		cfg.addr, hex.EncodeToString(cfg.groupKey[:]), cfg.name, cfg.threshold, rpcPath)
	log.Printf("fedmeetup: HostService=%s", federatedmeetupv1connect.HostServiceName)
	log.Printf("fedmeetup: web UI at %s, base_url=%s, db=%s", cfg.addr, cfg.baseURL, cfg.dbPath)
	if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatalf("listen: %v", err)
	}
	<-idleConnsClosed
	log.Printf("fedmeetup: stopped")
}
