// Package host is the ConnectRPC service implementation for the
// federated-meetup client surface.
//
// The handler interface (HostServiceHandler) is GENERATED by
// protoc-gen-connect-go from proto/federated_meetup/v1/rpc.proto.
// This file is the only place domain code touches protobuf types —
// every method body is a thin bridge that:
//   1. Decodes the request (a few bytes → domain types).
//   2. Calls into internal/group, internal/types.
//   3. Encodes the response (domain types → a few bytes).
//
// No handler boilerplate is hand-written. To add or change a method:
//   - Edit rpc.proto (or the Speckl .speckdl, which regenerates the .proto).
//   - Run `scripts/proto.sh` (buf generate).
//   - Update the method body here to match the new request/response shape.
//
// SPDX-License-Identifier: MIT
package host

import (
	"context"
	"fmt"
	"time"

	"connectrpc.com/connect"

	pb "github.com/sscoble/federated-meetup/proto/federated_meetup/v1"
	"github.com/sscoble/federated-meetup/proto/federated_meetup/v1/federatedmeetupv1connect"

	"github.com/sscoble/federated-meetup/internal/group"
	"github.com/sscoble/federated-meetup/internal/types"
)

// Service implements federatedmeetupv1connect.HostServiceHandler.
//
// The host runs multiple groups; each request is routed to the right
// *group.State via the MultiGroup registry. At v0 the registry is
// populated at construction time; future cycles will populate it
// dynamically (gossip, peer sync, on-disk persistence).
type Service struct {
	// groups is the host's "which groups am I currently serving" registry.
	groups *MultiGroup
	// name is the canonical name this host uses to advertise itself in
	// ResolveName responses.
	name string
	// now is overridable for tests. Defaults to time.Now in NewService.
	now func() time.Time
}

// Compile-time assertion: Service satisfies the generated handler interface.
var _ federatedmeetupv1connect.HostServiceHandler = (*Service)(nil)

// NewService constructs a Service bound to a MultiGroup registry.
//
// name is the host's canonical name (used in ResolveName responses).
// states are the *group.State instances this host serves (one per
// group). Each state machine's GroupID() is the registry key; a
// nil entry is silently skipped.
//
// For backward compatibility with the single-group v0 callers, you
// can also construct a Service via NewServiceSingle, which wraps a
// single state in a one-entry MultiGroup.
func NewService(name string, states ...*group.State) *Service {
	return &Service{
		groups: NewMultiGroup(name, states...),
		name:   name,
		now:    time.Now,
	}
}

// NewServiceSingle is a convenience constructor for the single-group
// case. Equivalent to NewService(name, state).
func NewServiceSingle(state *group.State, name string) *Service {
	return NewService(name, state)
}

// SetClock overrides the time source. Test-only.
func (s *Service) SetClock(now func() time.Time) { s.now = now }

// Groups returns the underlying MultiGroup registry. Read-only access
// for tests; production callers should go through the service methods.
func (s *Service) Groups() *MultiGroup { return s.groups }

// ----- Reads ---------------------------------------------------------------

// GetGroup returns the current state snapshot for a group.
//
// Identifier is one of: PublicKey (preferred) or CanonicalName (resolved
// locally for v0 — future cycles may delegate to a directory host).
func (s *Service) GetGroup(
	ctx context.Context,
	req *connect.Request[pb.GetGroupRequest],
) (*connect.Response[pb.GetGroupResponse], error) {
	r := req.Msg
	if r == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("nil request"))
	}
	var groupKey types.PublicKey
	switch id := r.Identifier.(type) {
	case *pb.GetGroupRequest_GroupKey:
		if id.GroupKey == nil {
			return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("group_key is nil"))
		}
		groupKey = bytesToKey(id.GroupKey.Raw)
	case *pb.GetGroupRequest_CanonicalName:
		// v0: no name directory yet. Reject so clients learn to use GroupKey.
		return nil, connect.NewError(connect.CodeUnimplemented, fmt.Errorf("canonical_name resolution not wired in v0; use group_key"))
	default:
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("missing identifier"))
	}
	state, err := s.lookup(groupKey)
	if err != nil {
		return nil, err
	}
	resp := &pb.GetGroupResponse{
		Snapshot:  stateSnapshotToProto(state.Snapshot(), state.Root()),
		Stewards:  stewardsToProto(state.Stewards()),
		Threshold: state.Threshold(),
	}
	return connect.NewResponse(resp), nil
}

// GetEvent returns a single event by (group, event_id).
func (s *Service) GetEvent(
	ctx context.Context,
	req *connect.Request[pb.GetEventRequest],
) (*connect.Response[pb.GetEventResponse], error) {
	r := req.Msg
	if r == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("nil request"))
	}
	if r.GroupKey == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("group_key is nil"))
	}
	if r.EventId == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("event_id is empty"))
	}
	state, err := s.lookup(bytesToKey(r.GroupKey.Raw))
	if err != nil {
		return nil, err
	}
	// Walk the log looking for CREATE_EVENT with matching event_id.
	for _, t := range state.Log() {
		if t == nil || t.Proto == nil {
			continue
		}
		if t.Type() != pb.TransitionType_TRANSITION_TYPE_CREATE_EVENT {
			continue
		}
		p := t.Proto.GetCreateEvent()
		if p != nil && p.EventId == r.EventId {
			return connect.NewResponse(&pb.GetEventResponse{
				Event:     p,
				Rsvps:     nil,
				Cancelled: false,
			}), nil
		}
	}
	return nil, connect.NewError(connect.CodeNotFound, fmt.Errorf("event %q not found", r.EventId))
}

// ListEvents pages through a group's event log.
func (s *Service) ListEvents(
	ctx context.Context,
	req *connect.Request[pb.ListEventsRequest],
) (*connect.Response[pb.ListEventsResponse], error) {
	r := req.Msg
	if r == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("nil request"))
	}
	if r.GroupKey == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("group_key is nil"))
	}
	state, err := s.lookup(bytesToKey(r.GroupKey.Raw))
	if err != nil {
		return nil, err
	}

	pageSize := int(r.PageSize)
	if pageSize <= 0 || pageSize > 200 {
		pageSize = 50
	}

	startIdx := uint64(0)
	if r.Cursor != "" {
		if _, err := fmt.Sscan(r.Cursor, &startIdx); err != nil {
			return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("bad cursor: %w", err))
		}
	}

	log := state.Log()
	endIdx := uint64(len(log))
	if r.Cursor != "" {
		if startIdx > endIdx {
			startIdx = endIdx
		}
		endIdx = endIdx - startIdx
	}

	events := make([]*pb.CreateEventPayload, 0, pageSize)
	nextCursor := ""
	for i := endIdx; i > 0 && len(events) < pageSize; i-- {
		t := log[i-1]
		if t == nil || t.Proto == nil {
			continue
		}
		if t.Type() != pb.TransitionType_TRANSITION_TYPE_CREATE_EVENT {
			continue
		}
		if p := t.Proto.GetCreateEvent(); p != nil {
			events = append(events, p)
		}
	}
	if uint64(len(log)) > 0 && len(events) == pageSize {
		nextCursor = fmt.Sprintf("%d", len(log))
	}
	return connect.NewResponse(&pb.ListEventsResponse{
		Events:     events,
		NextCursor: nextCursor,
	}), nil
}

// ListGroups lists all groups hosted by this host.
func (s *Service) ListGroups(
	ctx context.Context,
	req *connect.Request[pb.ListGroupsRequest],
) (*connect.Response[pb.ListGroupsResponse], error) {
	_ = req
	gids := s.groups.All()
	summaries := make([]*pb.ListGroupsResponse_GroupSummary, 0, len(gids))
	for _, gid := range gids {
		summaries = append(summaries, &pb.ListGroupsResponse_GroupSummary{
			GroupKey: keyToProto(gid),
		})
	}
	return connect.NewResponse(&pb.ListGroupsResponse{
		Groups:     summaries,
		NextCursor: "",
	}), nil
}

// ----- Writes --------------------------------------------------------------

// SubmitTransition applies a steward-signed transition to a group's
// state machine. The transition is verified against the current state
// by internal/group: cosigner signatures, multisig threshold,
// equivocation, and state invariants.
func (s *Service) SubmitTransition(
	ctx context.Context,
	req *connect.Request[pb.SubmitTransitionRequest],
) (*connect.Response[pb.SubmitTransitionResponse], error) {
	r := req.Msg
	if r == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("nil request"))
	}
	if r.GroupKey == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("group_key is nil"))
	}
	if r.Transition == nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("transition is nil"))
	}
	groupKey := bytesToKey(r.GroupKey.Raw)
	state, err := s.lookup(groupKey)
	if err != nil {
		return nil, err
	}
	t, err := group.NewTransition(r.Transition, groupKey)
	if err != nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("invalid transition: %w", err))
	}
	idx := state.TransitionCount()
	if err := state.Apply(t, s.now()); err != nil {
		return nil, connect.NewError(connect.CodeFailedPrecondition, fmt.Errorf("apply: %w", err))
	}
	return connect.NewResponse(&pb.SubmitTransitionResponse{
		NewSnapshot:     stateSnapshotToProto(state.Snapshot(), state.Root()),
		TransitionIndex: idx,
	}), nil
}

// SubmitUserAction applies a user-signed action (RSVP, ATTEST, CANCEL_RSVP).
//
// v0: this is a stub that rejects with Unimplemented. Wiring user-signed
// actions into the apply switch is cycle 80+ work.
func (s *Service) SubmitUserAction(
	ctx context.Context,
	req *connect.Request[pb.SubmitUserActionRequest],
) (*connect.Response[pb.SubmitUserActionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, fmt.Errorf("SubmitUserAction not wired in v0"))
}

// ResolveName resolves a canonical name to the group key + hosting URLs.
//
// v0: returns the FIRST hosted group + this host's name. A future cycle
// will add a name directory and a real name → GroupID mapping.
func (s *Service) ResolveName(
	ctx context.Context,
	req *connect.Request[pb.ResolveNameRequest],
) (*connect.Response[pb.ResolveNameResponse], error) {
	r := req.Msg
	if r == nil || r.CanonicalName == "" {
		return nil, connect.NewError(connect.CodeInvalidArgument, fmt.Errorf("canonical_name is empty"))
	}
	gids := s.groups.All()
	if len(gids) == 0 {
		return nil, connect.NewError(connect.CodeNotFound, fmt.Errorf("no groups hosted here"))
	}
	hosts := []string{}
	if s.name != "" {
		hosts = append(hosts, s.name)
	}
	return connect.NewResponse(&pb.ResolveNameResponse{
		GroupKey: keyToProto(gids[0]),
		Hosts:    hosts,
	}), nil
}

// ----- Internal helpers ----------------------------------------------------

// lookup resolves a group public key to a *group.State. Returns
// (nil, NotFound) if this host does not serve that group.
func (s *Service) lookup(gid types.PublicKey) (*group.State, error) {
	st, ok := s.groups.Get(gid)
	if !ok {
		return nil, connect.NewError(connect.CodeNotFound, fmt.Errorf("group not hosted here"))
	}
	return st, nil
}

// ----- Type bridges --------------------------------------------------------

// bytesToKey converts a raw byte slice to a types.PublicKey. Returns the
// zero key if the slice is the wrong length.
func bytesToKey(b []byte) types.PublicKey {
	var k types.PublicKey
	copy(k[:], b)
	return k
}

// keyToProto converts a types.PublicKey to *pb.PublicKey.
func keyToProto(k types.PublicKey) *pb.PublicKey {
	return &pb.PublicKey{Raw: k[:]}
}

// stewardsToProto converts a slice of Steward to a slice of *pb.PublicKey.
func stewardsToProto(stewards []group.Steward) []*pb.PublicKey {
	out := make([]*pb.PublicKey, 0, len(stewards))
	for _, st := range stewards {
		out = append(out, keyToProto(st.Key))
	}
	return out
}

// stateSnapshotToProto converts a types.StateSnapshot to *pb.StateSnapshot.
//
// The root is passed separately because types.StateSnapshot does not embed
// its own root (it is computed from the entries on demand).
func stateSnapshotToProto(snap types.StateSnapshot, root types.Hash) *pb.StateSnapshot {
	entries := make([]*pb.StateEntry, 0, len(snap.Entries))
	for _, e := range snap.Entries {
		entries = append(entries, &pb.StateEntry{
			Key:   e.Key,
			Value: e.Value,
		})
	}
	return &pb.StateSnapshot{
		Root: &pb.StateRoot{
			Hash: root[:],
		},
		Entries: entries,
	}
}
